// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: abilities_create.sql

package database

import (
	"context"
	"database/sql"
)

const createAbilitiesBattleInteractionsJunction = `-- name: CreateAbilitiesBattleInteractionsJunction :exec
INSERT INTO j_abilities_battle_interactions (data_hash, ability_id, battle_interaction_id)
VALUES($1, $2, $3)
ON CONFLICT(data_hash) DO NOTHING
`

type CreateAbilitiesBattleInteractionsJunctionParams struct {
	DataHash            string
	AbilityID           int32
	BattleInteractionID int32
}

func (q *Queries) CreateAbilitiesBattleInteractionsJunction(ctx context.Context, arg CreateAbilitiesBattleInteractionsJunctionParams) error {
	_, err := q.db.ExecContext(ctx, createAbilitiesBattleInteractionsJunction, arg.DataHash, arg.AbilityID, arg.BattleInteractionID)
	return err
}

const createAbility = `-- name: CreateAbility :one
INSERT INTO abilities (data_hash, name, version, specification, attributes_id, type)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT(data_hash) DO UPDATE SET data_hash = abilities.data_hash
RETURNING id, data_hash, name, version, specification, attributes_id, type
`

type CreateAbilityParams struct {
	DataHash      string
	Name          string
	Version       sql.NullInt32
	Specification sql.NullString
	AttributesID  sql.NullInt32
	Type          AbilityType
}

func (q *Queries) CreateAbility(ctx context.Context, arg CreateAbilityParams) (Ability, error) {
	row := q.db.QueryRowContext(ctx, createAbility,
		arg.DataHash,
		arg.Name,
		arg.Version,
		arg.Specification,
		arg.AttributesID,
		arg.Type,
	)
	var i Ability
	err := row.Scan(
		&i.ID,
		&i.DataHash,
		&i.Name,
		&i.Version,
		&i.Specification,
		&i.AttributesID,
		&i.Type,
	)
	return i, err
}

const createAbilityAttributes = `-- name: CreateAbilityAttributes :one
INSERT INTO ability_attributes (data_hash, rank, appears_in_help_bar, can_copycat)
VALUES ($1, $2, $3, $4)
ON CONFLICT(data_hash) DO UPDATE SET data_hash = ability_attributes.data_hash
RETURNING id, data_hash, rank, appears_in_help_bar, can_copycat
`

type CreateAbilityAttributesParams struct {
	DataHash         string
	Rank             sql.NullInt32
	AppearsInHelpBar bool
	CanCopycat       bool
}

func (q *Queries) CreateAbilityAttributes(ctx context.Context, arg CreateAbilityAttributesParams) (AbilityAttribute, error) {
	row := q.db.QueryRowContext(ctx, createAbilityAttributes,
		arg.DataHash,
		arg.Rank,
		arg.AppearsInHelpBar,
		arg.CanCopycat,
	)
	var i AbilityAttribute
	err := row.Scan(
		&i.ID,
		&i.DataHash,
		&i.Rank,
		&i.AppearsInHelpBar,
		&i.CanCopycat,
	)
	return i, err
}

const createEnemyAbility = `-- name: CreateEnemyAbility :one
INSERT INTO enemy_abilities (data_hash, ability_id, effect)
VALUES ($1, $2, $3)
ON CONFLICT(data_hash) DO UPDATE SET data_hash = enemy_abilities.data_hash
RETURNING id, data_hash, ability_id, effect
`

type CreateEnemyAbilityParams struct {
	DataHash  string
	AbilityID int32
	Effect    sql.NullString
}

func (q *Queries) CreateEnemyAbility(ctx context.Context, arg CreateEnemyAbilityParams) (EnemyAbility, error) {
	row := q.db.QueryRowContext(ctx, createEnemyAbility, arg.DataHash, arg.AbilityID, arg.Effect)
	var i EnemyAbility
	err := row.Scan(
		&i.ID,
		&i.DataHash,
		&i.AbilityID,
		&i.Effect,
	)
	return i, err
}

const createGenericAbilitiesLearnedByJunction = `-- name: CreateGenericAbilitiesLearnedByJunction :exec
INSERT INTO j_generic_abilities_learned_by (data_hash, generic_ability_id, character_class_id)
VALUES ($1, $2, $3)
ON CONFLICT(data_hash) DO NOTHING
`

type CreateGenericAbilitiesLearnedByJunctionParams struct {
	DataHash         string
	GenericAbilityID int32
	CharacterClassID int32
}

func (q *Queries) CreateGenericAbilitiesLearnedByJunction(ctx context.Context, arg CreateGenericAbilitiesLearnedByJunctionParams) error {
	_, err := q.db.ExecContext(ctx, createGenericAbilitiesLearnedByJunction, arg.DataHash, arg.GenericAbilityID, arg.CharacterClassID)
	return err
}

const createGenericAbilitiesRelatedStatsJunction = `-- name: CreateGenericAbilitiesRelatedStatsJunction :exec
INSERT INTO j_generic_abilities_related_stats (data_hash, generic_ability_id, stat_id)
VALUES ($1, $2, $3)
ON CONFLICT(data_hash) DO NOTHING
`

type CreateGenericAbilitiesRelatedStatsJunctionParams struct {
	DataHash         string
	GenericAbilityID int32
	StatID           int32
}

func (q *Queries) CreateGenericAbilitiesRelatedStatsJunction(ctx context.Context, arg CreateGenericAbilitiesRelatedStatsJunctionParams) error {
	_, err := q.db.ExecContext(ctx, createGenericAbilitiesRelatedStatsJunction, arg.DataHash, arg.GenericAbilityID, arg.StatID)
	return err
}

const createGenericAbility = `-- name: CreateGenericAbility :one
INSERT INTO generic_abilities (data_hash, ability_id, description, effect, topmenu, cursor)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT(data_hash) DO UPDATE SET data_hash = generic_abilities.data_hash
RETURNING id, data_hash, ability_id, description, effect, topmenu, cursor, submenu_id, open_submenu_id
`

type CreateGenericAbilityParams struct {
	DataHash    string
	AbilityID   int32
	Description sql.NullString
	Effect      string
	Topmenu     NullTopmenuType
	Cursor      NullTargetType
}

func (q *Queries) CreateGenericAbility(ctx context.Context, arg CreateGenericAbilityParams) (GenericAbility, error) {
	row := q.db.QueryRowContext(ctx, createGenericAbility,
		arg.DataHash,
		arg.AbilityID,
		arg.Description,
		arg.Effect,
		arg.Topmenu,
		arg.Cursor,
	)
	var i GenericAbility
	err := row.Scan(
		&i.ID,
		&i.DataHash,
		&i.AbilityID,
		&i.Description,
		&i.Effect,
		&i.Topmenu,
		&i.Cursor,
		&i.SubmenuID,
		&i.OpenSubmenuID,
	)
	return i, err
}

const createOverdrive = `-- name: CreateOverdrive :one
INSERT INTO overdrives (data_hash, name, version, description, effect, topmenu, attributes_id, unlock_condition, countdown_in_sec, cursor)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT(data_hash) DO UPDATE SET data_hash = overdrives.data_hash
RETURNING id, data_hash, name, version, description, effect, topmenu, attributes_id, unlock_condition, countdown_in_sec, cursor, od_command_id, character_class_id
`

type CreateOverdriveParams struct {
	DataHash        string
	Name            string
	Version         sql.NullInt32
	Description     string
	Effect          string
	Topmenu         NullTopmenuType
	AttributesID    int32
	UnlockCondition sql.NullString
	CountdownInSec  sql.NullInt32
	Cursor          NullTargetType
}

func (q *Queries) CreateOverdrive(ctx context.Context, arg CreateOverdriveParams) (Overdrife, error) {
	row := q.db.QueryRowContext(ctx, createOverdrive,
		arg.DataHash,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Effect,
		arg.Topmenu,
		arg.AttributesID,
		arg.UnlockCondition,
		arg.CountdownInSec,
		arg.Cursor,
	)
	var i Overdrife
	err := row.Scan(
		&i.ID,
		&i.DataHash,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Effect,
		&i.Topmenu,
		&i.AttributesID,
		&i.UnlockCondition,
		&i.CountdownInSec,
		&i.Cursor,
		&i.OdCommandID,
		&i.CharacterClassID,
	)
	return i, err
}

const createOverdriveAbilitiesRelatedStatsJunction = `-- name: CreateOverdriveAbilitiesRelatedStatsJunction :exec
INSERT INTO j_overdrive_abilities_related_stats (data_hash, overdrive_ability_id, stat_id)
VALUES ($1, $2, $3)
ON CONFLICT(data_hash) DO NOTHING
`

type CreateOverdriveAbilitiesRelatedStatsJunctionParams struct {
	DataHash           string
	OverdriveAbilityID int32
	StatID             int32
}

func (q *Queries) CreateOverdriveAbilitiesRelatedStatsJunction(ctx context.Context, arg CreateOverdriveAbilitiesRelatedStatsJunctionParams) error {
	_, err := q.db.ExecContext(ctx, createOverdriveAbilitiesRelatedStatsJunction, arg.DataHash, arg.OverdriveAbilityID, arg.StatID)
	return err
}

const createOverdriveAbility = `-- name: CreateOverdriveAbility :one
INSERT INTO overdrive_abilities (data_hash, ability_id)
VALUES ($1, $2)
ON CONFLICT(data_hash) DO UPDATE SET data_hash = overdrive_abilities.data_hash
RETURNING id, data_hash, ability_id
`

type CreateOverdriveAbilityParams struct {
	DataHash  string
	AbilityID int32
}

func (q *Queries) CreateOverdriveAbility(ctx context.Context, arg CreateOverdriveAbilityParams) (OverdriveAbility, error) {
	row := q.db.QueryRowContext(ctx, createOverdriveAbility, arg.DataHash, arg.AbilityID)
	var i OverdriveAbility
	err := row.Scan(&i.ID, &i.DataHash, &i.AbilityID)
	return i, err
}

const createOverdrivesOverdriveAbilitiesJunction = `-- name: CreateOverdrivesOverdriveAbilitiesJunction :exec
INSERT INTO j_overdrives_overdrive_abilities (data_hash, overdrive_id, overdrive_ability_id)
VALUES($1, $2, $3)
ON CONFLICT(data_hash) DO NOTHING
`

type CreateOverdrivesOverdriveAbilitiesJunctionParams struct {
	DataHash           string
	OverdriveID        int32
	OverdriveAbilityID int32
}

func (q *Queries) CreateOverdrivesOverdriveAbilitiesJunction(ctx context.Context, arg CreateOverdrivesOverdriveAbilitiesJunctionParams) error {
	_, err := q.db.ExecContext(ctx, createOverdrivesOverdriveAbilitiesJunction, arg.DataHash, arg.OverdriveID, arg.OverdriveAbilityID)
	return err
}

const createPlayerAbilitiesLearnedByJunction = `-- name: CreatePlayerAbilitiesLearnedByJunction :exec
INSERT INTO j_player_abilities_learned_by (data_hash, player_ability_id, character_class_id)
VALUES ($1, $2, $3)
ON CONFLICT(data_hash) DO NOTHING
`

type CreatePlayerAbilitiesLearnedByJunctionParams struct {
	DataHash         string
	PlayerAbilityID  int32
	CharacterClassID int32
}

func (q *Queries) CreatePlayerAbilitiesLearnedByJunction(ctx context.Context, arg CreatePlayerAbilitiesLearnedByJunctionParams) error {
	_, err := q.db.ExecContext(ctx, createPlayerAbilitiesLearnedByJunction, arg.DataHash, arg.PlayerAbilityID, arg.CharacterClassID)
	return err
}

const createPlayerAbilitiesRelatedStatsJunction = `-- name: CreatePlayerAbilitiesRelatedStatsJunction :exec
INSERT INTO j_player_abilities_related_stats (data_hash, player_ability_id, stat_id)
VALUES ($1, $2, $3)
ON CONFLICT(data_hash) DO NOTHING
`

type CreatePlayerAbilitiesRelatedStatsJunctionParams struct {
	DataHash        string
	PlayerAbilityID int32
	StatID          int32
}

func (q *Queries) CreatePlayerAbilitiesRelatedStatsJunction(ctx context.Context, arg CreatePlayerAbilitiesRelatedStatsJunctionParams) error {
	_, err := q.db.ExecContext(ctx, createPlayerAbilitiesRelatedStatsJunction, arg.DataHash, arg.PlayerAbilityID, arg.StatID)
	return err
}

const createPlayerAbility = `-- name: CreatePlayerAbility :one
INSERT INTO player_abilities (data_hash, ability_id, description, effect, topmenu, can_use_outside_battle, mp_cost, cursor)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(data_hash) DO UPDATE SET data_hash = player_abilities.data_hash
RETURNING id, data_hash, ability_id, description, effect, topmenu, can_use_outside_battle, mp_cost, cursor, submenu_id, open_submenu_id, standard_grid_char_id, expert_grid_char_id, aeon_learn_item_id
`

type CreatePlayerAbilityParams struct {
	DataHash            string
	AbilityID           int32
	Description         sql.NullString
	Effect              string
	Topmenu             NullTopmenuType
	CanUseOutsideBattle bool
	MpCost              sql.NullInt32
	Cursor              NullTargetType
}

func (q *Queries) CreatePlayerAbility(ctx context.Context, arg CreatePlayerAbilityParams) (PlayerAbility, error) {
	row := q.db.QueryRowContext(ctx, createPlayerAbility,
		arg.DataHash,
		arg.AbilityID,
		arg.Description,
		arg.Effect,
		arg.Topmenu,
		arg.CanUseOutsideBattle,
		arg.MpCost,
		arg.Cursor,
	)
	var i PlayerAbility
	err := row.Scan(
		&i.ID,
		&i.DataHash,
		&i.AbilityID,
		&i.Description,
		&i.Effect,
		&i.Topmenu,
		&i.CanUseOutsideBattle,
		&i.MpCost,
		&i.Cursor,
		&i.SubmenuID,
		&i.OpenSubmenuID,
		&i.StandardGridCharID,
		&i.ExpertGridCharID,
		&i.AeonLearnItemID,
	)
	return i, err
}

const createRonsoRage = `-- name: CreateRonsoRage :one
INSERT INTO ronso_rages (data_hash, overdrive_id)
VALUES ($1, $2)
ON CONFLICT(data_hash) DO UPDATE SET data_hash = ronso_rages.data_hash
RETURNING id, data_hash, overdrive_id
`

type CreateRonsoRageParams struct {
	DataHash    string
	OverdriveID int32
}

func (q *Queries) CreateRonsoRage(ctx context.Context, arg CreateRonsoRageParams) (RonsoRage, error) {
	row := q.db.QueryRowContext(ctx, createRonsoRage, arg.DataHash, arg.OverdriveID)
	var i RonsoRage
	err := row.Scan(&i.ID, &i.DataHash, &i.OverdriveID)
	return i, err
}

const createTriggerCommand = `-- name: CreateTriggerCommand :one
INSERT INTO trigger_commands (data_hash, ability_id, description, effect, topmenu, cursor)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT(data_hash) DO UPDATE SET data_hash = trigger_commands.data_hash
RETURNING id, data_hash, ability_id, description, effect, topmenu, cursor
`

type CreateTriggerCommandParams struct {
	DataHash    string
	AbilityID   int32
	Description string
	Effect      string
	Topmenu     TopmenuType
	Cursor      TargetType
}

func (q *Queries) CreateTriggerCommand(ctx context.Context, arg CreateTriggerCommandParams) (TriggerCommand, error) {
	row := q.db.QueryRowContext(ctx, createTriggerCommand,
		arg.DataHash,
		arg.AbilityID,
		arg.Description,
		arg.Effect,
		arg.Topmenu,
		arg.Cursor,
	)
	var i TriggerCommand
	err := row.Scan(
		&i.ID,
		&i.DataHash,
		&i.AbilityID,
		&i.Description,
		&i.Effect,
		&i.Topmenu,
		&i.Cursor,
	)
	return i, err
}

const createTriggerCommandsRelatedStatsJunction = `-- name: CreateTriggerCommandsRelatedStatsJunction :exec
INSERT INTO j_trigger_commands_related_stats (data_hash, trigger_command_id, stat_id)
VALUES ($1, $2, $3)
ON CONFLICT(data_hash) DO NOTHING
`

type CreateTriggerCommandsRelatedStatsJunctionParams struct {
	DataHash         string
	TriggerCommandID int32
	StatID           int32
}

func (q *Queries) CreateTriggerCommandsRelatedStatsJunction(ctx context.Context, arg CreateTriggerCommandsRelatedStatsJunctionParams) error {
	_, err := q.db.ExecContext(ctx, createTriggerCommandsRelatedStatsJunction, arg.DataHash, arg.TriggerCommandID, arg.StatID)
	return err
}

const updateGenericAbility = `-- name: UpdateGenericAbility :exec
UPDATE generic_abilities
SET data_hash = $1,
    submenu_id = $2,
    open_submenu_id = $3
WHERE id = $4
`

type UpdateGenericAbilityParams struct {
	DataHash      string
	SubmenuID     sql.NullInt32
	OpenSubmenuID sql.NullInt32
	ID            int32
}

func (q *Queries) UpdateGenericAbility(ctx context.Context, arg UpdateGenericAbilityParams) error {
	_, err := q.db.ExecContext(ctx, updateGenericAbility,
		arg.DataHash,
		arg.SubmenuID,
		arg.OpenSubmenuID,
		arg.ID,
	)
	return err
}

const updateOverdrive = `-- name: UpdateOverdrive :exec
UPDATE overdrives
SET data_hash = $1,
    od_command_id = $2,
    character_class_id = $3
WHERE id = $4
`

type UpdateOverdriveParams struct {
	DataHash         string
	OdCommandID      sql.NullInt32
	CharacterClassID sql.NullInt32
	ID               int32
}

func (q *Queries) UpdateOverdrive(ctx context.Context, arg UpdateOverdriveParams) error {
	_, err := q.db.ExecContext(ctx, updateOverdrive,
		arg.DataHash,
		arg.OdCommandID,
		arg.CharacterClassID,
		arg.ID,
	)
	return err
}

const updatePlayerAbility = `-- name: UpdatePlayerAbility :exec
UPDATE player_abilities
SET data_hash = $1,
    submenu_id = $2,
    open_submenu_id = $3,
    standard_grid_char_id = $4,
    expert_grid_char_id = $5,
    aeon_learn_item_id = $6
WHERE id = $7
`

type UpdatePlayerAbilityParams struct {
	DataHash           string
	SubmenuID          sql.NullInt32
	OpenSubmenuID      sql.NullInt32
	StandardGridCharID sql.NullInt32
	ExpertGridCharID   sql.NullInt32
	AeonLearnItemID    sql.NullInt32
	ID                 int32
}

func (q *Queries) UpdatePlayerAbility(ctx context.Context, arg UpdatePlayerAbilityParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerAbility,
		arg.DataHash,
		arg.SubmenuID,
		arg.OpenSubmenuID,
		arg.StandardGridCharID,
		arg.ExpertGridCharID,
		arg.AeonLearnItemID,
		arg.ID,
	)
	return err
}
