// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: availability.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const filterAreaIDsByAvailability = `-- name: FilterAreaIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability,
        $3::text[] AS reqs,
        $4::text[] AS excls,
        $5::int AS monster_id,
        $6::int AS key_item_id,
        $7::int AS item_id,
        $8::text[] AS methods,
        $9::boolean AS is_repeatable
),
available_areas AS (
    SELECT
        a.a_id,
        a.avl_self AS current_avl,
        a.is_repeatable_loc AS is_rep,
        'area'::text AS s_type
    FROM mv_availabilities a
    JOIN w ON a.a_id = ANY(w.ids)
    WHERE a.source_type = 'area'

    UNION ALL

    SELECT
        me.area_id,
        me.avl_area AS current_avl,
        me.is_repeatable_loc AS is_rep,
        'monster'::text AS s_type
    FROM mv_monster_encounters me
    JOIN w ON me.area_id = ANY(w.ids)
    WHERE me.monster_id = w.monster_id
      AND (w.availability IS NULL OR me.avl_area = ANY(w.availability))

    UNION ALL

    -- selecting the avl of the item's resource as if it where the area's avl would alter the results
    -- so we select the lowest rank to not raise MAX avl of GROUP BY bucket
    SELECT
        mis.area_id AS a_id,
        'always'::availability_type AS current_avl,
        mis.is_repeatable_loc AS is_rep,
        'item'::text AS s_type
    FROM mv_item_sources mis
    JOIN items i ON mis.master_item_id = i.master_item_id
    JOIN w ON mis.area_id = ANY(w.ids)
    WHERE i.id = w.item_id
      AND (w.availability IS NULL OR mis.avl_area = ANY(w.availability))
      AND (w.methods IS NULL OR mis.source_type = ANY(w.methods))

    UNION ALL

    SELECT
        mis.area_id AS a_id,
        'always'::availability_type AS current_avl,
        mis.is_repeatable_loc AS is_rep,
        'key-item'::text AS s_type
    FROM mv_item_sources mis
    JOIN key_items ki ON mis.master_item_id = ki.master_item_id
    JOIN w ON mis.area_id = ANY(w.ids)
    WHERE ki.id = w.key_item_id
      AND (w.availability IS NULL OR mis.avl_area = ANY(w.availability))

    UNION ALL

    -- can't use alias in where clause,
    -- so we select the non-altering option here and filter in the where clause
    -- this branch selects sources with an area_id that are not areas
    SELECT
        a.a_id,
        'always'::availability_type AS current_avl,
        a.is_repeatable_loc AS is_rep,
        CASE
          WHEN a.sub_type = 'boss' THEN 'boss'::text
          ELSE a.source_type
        END AS s_type
    FROM mv_availabilities a
    JOIN w ON a.a_id = ANY(w.ids)
    WHERE a.source_type != 'area'
      AND (w.availability IS NULL OR CASE
        WHEN a.source_type = 'monster' THEN a.avl_area
        ELSE a.avl_self
      END = ANY(w.availability))
)
SELECT a_id
FROM available_areas
CROSS JOIN w
GROUP BY a_id, w.availability, w.is_repeatable, w.reqs, w.excls
HAVING (w.availability IS NULL OR MAX(current_avl) = ANY(w.availability))
   AND (w.is_repeatable IS NULL OR BOOL_OR(is_rep) = w.is_repeatable)
   AND (w.reqs IS NULL OR ARRAY_AGG(s_type) @> w.reqs)
   AND (w.excls IS NULL OR NOT ARRAY_AGG(s_type) && w.excls)
ORDER BY a_id
`

type FilterAreaIDsByAvailabilityParams struct {
	Ids             []int32
	Availability    []AvailabilityType
	RequiredSources []string
	ExcludedSources []string
	MonsterID       sql.NullInt32
	KeyItemID       sql.NullInt32
	ItemID          sql.NullInt32
	Methods         []string
	IsRepeatable    sql.NullBool
}

func (q *Queries) FilterAreaIDsByAvailability(ctx context.Context, arg FilterAreaIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterAreaIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		pq.Array(arg.RequiredSources),
		pq.Array(arg.ExcludedSources),
		arg.MonsterID,
		arg.KeyItemID,
		arg.ItemID,
		pq.Array(arg.Methods),
		arg.IsRepeatable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var a_id int32
		if err := rows.Scan(&a_id); err != nil {
			return nil, err
		}
		items = append(items, a_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterAutoAbilityIDsByAvailability = `-- name: FilterAutoAbilityIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::availability_type[] AS availability,
        $4::int AS loc_context_id,
        $5::text AS loc_context_type,
        $6::int AS character_id,
        $7::boolean AS is_repeatable,
        $8::boolean AS req_item
),
available_auto_abilities AS (
    SELECT 
        aas.auto_ability_id,
        CASE
            WHEN aas.source_type = 'shop' AND w.avl_type = 'self' THEN aas.avl_context
            WHEN w.avl_type = 'self' THEN aas.avl_self
            WHEN w.avl_type = 'context' THEN aas.avl_context
            WHEN w.avl_type = 'area' THEN aas.avl_area
        END AS current_avl,
        CASE
            WHEN w.loc_context_id IS NOT NULL THEN aas.is_repeatable_loc
            ELSE aas.is_repeatable
        END AS is_rep
    FROM mv_auto_ability_sources aas
    JOIN mv_geography g ON aas.area_id = g.area_id
    CROSS JOIN w
    WHERE (w.req_item IS NULL OR w.req_item = FALSE)
      AND aas.auto_ability_id = ANY(w.ids)
      AND (w.loc_context_id IS NULL OR CASE
           WHEN w.loc_context_type = 'location' THEN g.location_id
           WHEN w.loc_context_type = 'sublocation' THEN g.sublocation_id
           WHEN w.loc_context_type = 'area' THEN g.area_id
          END = w.loc_context_id)
      AND (w.character_id IS NULL OR aas.character_id = w.character_id OR aas.character_id IS NULL)

    UNION ALL

    SELECT
        aa.id AS auto_ability_id,
        CASE
            WHEN mis.source_type = 'shop' AND w.avl_type = 'self' THEN mis.avl_context
            WHEN w.avl_type = 'self' THEN mis.avl_self
            WHEN w.avl_type = 'context' THEN mis.avl_context
            WHEN w.avl_type = 'area' THEN mis.avl_area
        END AS current_avl,
        CASE
            WHEN w.loc_context_id IS NOT NULL THEN mis.is_repeatable_loc
            ELSE mis.is_repeatable
        END AS is_rep
    FROM auto_abilities aa
    JOIN item_amounts ia_req ON aa.required_item_amount_id = ia_req.id
    JOIN mv_item_sources mis ON mis.master_item_id = ia_req.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE w.req_item = TRUE
      AND aa.id = ANY(w.ids)
      AND (w.loc_context_id IS NULL OR CASE
           WHEN w.loc_context_type = 'location' THEN g.location_id
           WHEN w.loc_context_type = 'sublocation' THEN g.sublocation_id
           WHEN w.loc_context_type = 'area' THEN g.area_id
          END = w.loc_context_id)
)
SELECT auto_ability_id
FROM available_auto_abilities
CROSS JOIN w
GROUP BY auto_ability_id, w.availability, w.is_repeatable
HAVING (w.availability IS NULL OR MIN(current_avl) = ANY(w.availability))
   AND (w.is_repeatable IS NULL OR BOOL_OR(is_rep) = w.is_repeatable)
`

type FilterAutoAbilityIDsByAvailabilityParams struct {
	Ids            []int32
	AvlType        string
	Availability   []AvailabilityType
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
	CharacterID    sql.NullInt32
	IsRepeatable   sql.NullBool
	ReqItem        sql.NullBool
}

func (q *Queries) FilterAutoAbilityIDsByAvailability(ctx context.Context, arg FilterAutoAbilityIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterAutoAbilityIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		arg.LocContextID,
		arg.LocContextType,
		arg.CharacterID,
		arg.IsRepeatable,
		arg.ReqItem,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var auto_ability_id int32
		if err := rows.Scan(&auto_ability_id); err != nil {
			return nil, err
		}
		items = append(items, auto_ability_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterItemIDsByAvailability = `-- name: FilterItemIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::availability_type[] AS availability,
        $4::int AS loc_context_id,
        $5::text AS loc_context_type,
        $6::boolean AS is_repeatable
),
available_items AS (
    SELECT 
        i.id AS item_id,
        CASE
            WHEN mis.source_type = 'shop' AND w.avl_type = 'self' THEN mis.avl_context
            WHEN w.avl_type = 'self' THEN mis.avl_self
            WHEN w.avl_type = 'context' THEN mis.avl_context
            WHEN w.avl_type = 'area' THEN mis.avl_area
        END AS current_avl,
        CASE
            WHEN w.loc_context_id IS NOT NULL THEN mis.is_repeatable_loc
            ELSE mis.is_repeatable
        END AS is_rep
    FROM items i
    JOIN mv_item_sources mis ON mis.master_item_id = i.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE i.id = ANY(w.ids)
      AND (w.loc_context_id IS NULL OR CASE
           WHEN w.loc_context_type = 'location' THEN g.location_id
           WHEN w.loc_context_type = 'sublocation' THEN g.sublocation_id
           WHEN w.loc_context_type = 'area' THEN g.area_id
          END = w.loc_context_id)
)
SELECT item_id
FROM available_items
CROSS JOIN w
GROUP BY item_id, w.availability, w.is_repeatable
HAVING (w.availability IS NULL OR MIN(current_avl) = ANY(w.availability))
   AND (w.is_repeatable IS NULL OR BOOL_OR(is_rep) = w.is_repeatable)
`

type FilterItemIDsByAvailabilityParams struct {
	Ids            []int32
	AvlType        string
	Availability   []AvailabilityType
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
	IsRepeatable   sql.NullBool
}

func (q *Queries) FilterItemIDsByAvailability(ctx context.Context, arg FilterItemIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterItemIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		arg.LocContextID,
		arg.LocContextType,
		arg.IsRepeatable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var item_id int32
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterKeyItemIDsByAvailability = `-- name: FilterKeyItemIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability,
        $3::int AS loc_context_id,
        $4::text AS loc_context_type
),
available_key_items AS (
    SELECT 
        ki.id AS key_item_id,
        mis.avl_self AS current_avl
    FROM key_items ki
    JOIN mv_item_sources mis ON mis.master_item_id = ki.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE ki.id = ANY(w.ids)
      AND (w.loc_context_id IS NULL OR CASE
           WHEN w.loc_context_type = 'location' THEN g.location_id
           WHEN w.loc_context_type = 'sublocation' THEN g.sublocation_id
           WHEN w.loc_context_type = 'area' THEN g.area_id
          END = w.loc_context_id)
)
SELECT key_item_id
FROM available_key_items
CROSS JOIN w
GROUP BY key_item_id, w.availability
HAVING MIN(current_avl) = ANY(w.availability)
`

type FilterKeyItemIDsByAvailabilityParams struct {
	Ids            []int32
	Availability   []AvailabilityType
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
}

func (q *Queries) FilterKeyItemIDsByAvailability(ctx context.Context, arg FilterKeyItemIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterKeyItemIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		arg.LocContextID,
		arg.LocContextType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var key_item_id int32
		if err := rows.Scan(&key_item_id); err != nil {
			return nil, err
		}
		items = append(items, key_item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterLocationIDsByAvailability = `-- name: FilterLocationIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability,
        $3::text[] AS reqs,
        $4::text[] AS excls,
        $5::int AS monster_id,
        $6::int AS key_item_id,
        $7::int AS item_id,
        $8::text[] AS methods,
        $9::boolean AS is_repeatable
),
available_locations AS (
    SELECT
        l.id AS location_id,
        l.availability AS current_avl,
        NULL::boolean AS is_rep,
        'location'::text AS s_type
    FROM locations l
    JOIN w ON l.id = ANY(w.ids)

    UNION ALL

    SELECT
        g.location_id,
        me.avl_context AS current_avl,
        me.is_repeatable_loc AS is_rep,
        'monster'::text AS s_type
    FROM mv_monster_encounters me
    JOIN mv_geography g ON me.area_id = g.area_id
    JOIN w ON g.locatoin_id = ANY(w.ids)
    WHERE me.monster_id = w.monster_id
      AND (w.availability IS NULL OR me.avl_context = ANY(w.availability))

    UNION ALL

    SELECT
        g.location_id,
        'always'::availability_type AS current_avl,
        mis.is_repeatable_loc AS is_rep,
        'item'::text AS s_type
    FROM mv_item_sources mis
    JOIN items i ON mis.master_item_id = i.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    JOIN w ON g.location_id = ANY(w.ids)
    WHERE i.id = w.item_id
      AND mis.avl_context = ANY(w.availability)
      AND (w.methods IS NULL OR mis.source_type = ANY(w.methods))

    UNION ALL

    SELECT
        g.location_id,
        'always'::availability_type AS current_avl,
        mis.is_repeatable_loc AS is_rep,
        'key-item'::text AS s_type
    FROM mv_item_sources mis
    JOIN key_items ki ON mis.master_item_id = ki.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    JOIN w ON g.location_id = ANY(w.ids)
    WHERE ki.id = w.key_item_id
      AND mis.avl_context = ANY(w.availability)

    UNION ALL

    SELECT
        g.location_id,
        'always'::availability_type AS current_avl,
        a.is_repeatable_loc AS is_rep,
        CASE
          WHEN a.sub_type = 'boss' THEN 'boss'::text
          ELSE a.source_type
        END AS s_type
    FROM mv_availabilities a
    JOIN mv_geography g ON a.a_id = g.area_id
    JOIN w ON g.location_id = ANY(w.ids)
    WHERE a.source_type != 'area'
      AND CASE
        WHEN a.source_type = 'shop' THEN a.avl_self
        ELSE a.avl_context
      END = ANY(w.availability)
)
SELECT location_id
FROM available_locations
CROSS JOIN w
GROUP BY location_id, w.availability, w.is_repeatable, w.reqs, w.excls
HAVING (w.availability IS NULL OR MAX(current_avl) = ANY(w.availability))
   AND (w.is_repeatable IS NULL OR BOOL_OR(is_rep) = w.is_repeatable)
   AND (w.reqs IS NULL OR ARRAY_AGG(s_type) @> w.reqs)
   AND (w.excls IS NULL OR NOT ARRAY_AGG(s_type) && w.excls)
ORDER BY location_id
`

type FilterLocationIDsByAvailabilityParams struct {
	Ids             []int32
	Availability    []AvailabilityType
	RequiredSources []string
	ExcludedSources []string
	MonsterID       sql.NullInt32
	KeyItemID       sql.NullInt32
	ItemID          sql.NullInt32
	Methods         []string
	IsRepeatable    sql.NullBool
}

func (q *Queries) FilterLocationIDsByAvailability(ctx context.Context, arg FilterLocationIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterLocationIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		pq.Array(arg.RequiredSources),
		pq.Array(arg.ExcludedSources),
		arg.MonsterID,
		arg.KeyItemID,
		arg.ItemID,
		pq.Array(arg.Methods),
		arg.IsRepeatable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var location_id int32
		if err := rows.Scan(&location_id); err != nil {
			return nil, err
		}
		items = append(items, location_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterMasterItemIDsByAvailability = `-- name: FilterMasterItemIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::availability_type[] AS availability,
        $4::int AS loc_context_id,
        $5::text AS loc_context_type,
        $6::boolean AS is_repeatable
),
available_master_items AS (
    SELECT 
        mis.master_item_id,
        CASE
            WHEN mis.source_type = 'shop' AND w.avl_type = 'self' THEN mis.avl_context
            WHEN w.avl_type = 'self' THEN mis.avl_self
            WHEN w.avl_type = 'context' THEN mis.avl_context
            WHEN w.avl_type = 'area' THEN mis.avl_area
        END AS current_avl,
        CASE
            WHEN w.loc_context_id IS NOT NULL THEN mis.is_repeatable_loc
            ELSE mis.is_repeatable
        END AS is_rep
    FROM mv_item_sources mis
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE mis.master_item_id = ANY(w.ids)
      AND (w.loc_context_id IS NULL OR CASE
           WHEN w.loc_context_type = 'location' THEN g.location_id
           WHEN w.loc_context_type = 'sublocation' THEN g.sublocation_id
           WHEN w.loc_context_type = 'area' THEN g.area_id
          END = w.loc_context_id)
)
SELECT master_item_id
FROM available_master_items
CROSS JOIN w
GROUP BY master_item_id, w.availability, w.is_repeatable
HAVING (w.availability IS NULL OR MIN(current_avl) = ANY(w.availability))
   AND (w.is_repeatable IS NULL OR BOOL_OR(is_rep) = w.is_repeatable)
`

type FilterMasterItemIDsByAvailabilityParams struct {
	Ids            []int32
	AvlType        string
	Availability   []AvailabilityType
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
	IsRepeatable   sql.NullBool
}

func (q *Queries) FilterMasterItemIDsByAvailability(ctx context.Context, arg FilterMasterItemIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterMasterItemIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		arg.LocContextID,
		arg.LocContextType,
		arg.IsRepeatable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var master_item_id int32
		if err := rows.Scan(&master_item_id); err != nil {
			return nil, err
		}
		items = append(items, master_item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterMonsterFormationIDsByAvailability = `-- name: FilterMonsterFormationIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability,
        $3::boolean AS is_repeatable,
        $4::text AS avl_type,
        $5::int AS loc_context_id,
        $6::text AS loc_context_type
),
available_formations AS (
    SELECT 
        me.formation_id,
        CASE 
            WHEN w.avl_type = 'self' THEN me.avl_context
            WHEN w.avl_type = 'context' THEN me.avl_context
            WHEN w.avl_type = 'area' THEN me.avl_area
        END AS current_avl,
        me.is_repeatable_loc AS is_rep
    FROM mv_monster_encounters me
    JOIN mv_geography g ON me.area_id = g.area_id
    CROSS JOIN w
    WHERE me.formation_id = ANY(w.ids)
      AND (w.loc_context_id IS NULL OR CASE
           WHEN w.loc_context_type = 'location' THEN g.location_id
           WHEN w.loc_context_type = 'sublocation' THEN g.sublocation_id
           WHEN w.loc_context_type = 'area' THEN g.area_id
          END = w.loc_context_id)
)
SELECT formation_id
FROM available_formations
CROSS JOIN w
GROUP BY formation_id, w.availability, w.is_repeatable
HAVING (w.availability IS NULL OR MIN(current_avl) = ANY(w.availability))
   AND (w.is_repeatable IS NULL OR BOOL_OR(is_rep) = w.is_repeatable)
`

type FilterMonsterFormationIDsByAvailabilityParams struct {
	Ids            []int32
	Availability   []AvailabilityType
	IsRepeatable   sql.NullBool
	AvlType        string
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
}

func (q *Queries) FilterMonsterFormationIDsByAvailability(ctx context.Context, arg FilterMonsterFormationIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterMonsterFormationIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.AvlType,
		arg.LocContextID,
		arg.LocContextType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var formation_id int32
		if err := rows.Scan(&formation_id); err != nil {
			return nil, err
		}
		items = append(items, formation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterMonsterIDsByAvailability = `-- name: FilterMonsterIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability,
        $3::boolean AS is_repeatable,
        $4::text AS avl_type,
        $5::int AS loc_context_id,
        $6::text AS loc_context_type
),
available_monsters AS (
    SELECT 
        me.monster_id,
        CASE 
            WHEN w.avl_type = 'self' THEN me.avl_self
            WHEN w.avl_type = 'context' THEN me.avl_context
            WHEN w.avl_type = 'area' THEN me.avl_area
        END AS current_avl,
        CASE
            WHEN w.loc_context_id IS NOT NULL THEN me.is_repeatable_loc
            ELSE me.is_repeatable
        END AS is_rep
    FROM mv_monster_encounters me
    JOIN mv_geography g ON me.area_id = g.area_id
    CROSS JOIN w
    WHERE me.monster_id = ANY(w.ids)
      AND (w.loc_context_id IS NULL OR CASE
           WHEN w.loc_context_type = 'location' THEN g.location_id
           WHEN w.loc_context_type = 'sublocation' THEN g.sublocation_id
           WHEN w.loc_context_type = 'area' THEN g.area_id
          END = w.loc_context_id)
)
SELECT monster_id
FROM available_monsters
CROSS JOIN w
GROUP BY monster_id, w.availability, w.is_repeatable
HAVING (w.availability IS NULL OR MIN(current_avl) = ANY(w.availability))
   AND (w.is_repeatable IS NULL OR BOOL_OR(is_rep) = w.is_repeatable)
`

type FilterMonsterIDsByAvailabilityParams struct {
	Ids            []int32
	Availability   []AvailabilityType
	IsRepeatable   sql.NullBool
	AvlType        string
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
}

func (q *Queries) FilterMonsterIDsByAvailability(ctx context.Context, arg FilterMonsterIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterMonsterIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.AvlType,
		arg.LocContextID,
		arg.LocContextType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var monster_id int32
		if err := rows.Scan(&monster_id); err != nil {
			return nil, err
		}
		items = append(items, monster_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterPrimerIDsByAvailability = `-- name: FilterPrimerIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability
),
available_primers AS (
    SELECT 
        p.id AS primer_id,
        mis.avl_self AS current_avl
    FROM primers p
    JOIN key_items ki ON p.key_item_id = ki.id
    JOIN mv_item_sources mis ON mis.master_item_id = ki.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE p.id = ANY(w.ids)
)
SELECT primer_id
FROM available_primers
CROSS JOIN w
GROUP BY primer_id, w.availability
HAVING MIN(current_avl) = ANY(w.availability)
`

type FilterPrimerIDsByAvailabilityParams struct {
	Ids          []int32
	Availability []AvailabilityType
}

func (q *Queries) FilterPrimerIDsByAvailability(ctx context.Context, arg FilterPrimerIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterPrimerIDsByAvailability, pq.Array(arg.Ids), pq.Array(arg.Availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var primer_id int32
		if err := rows.Scan(&primer_id); err != nil {
			return nil, err
		}
		items = append(items, primer_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterQuestIDsByAvailability = `-- name: FilterQuestIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability,
        $3::boolean AS is_repeatable
)
SELECT DISTINCT a.s_id
FROM quests q
JOIN mv_availabilities a ON q.id = a.s_id AND a.source_type = 'quest'
CROSS JOIN w
WHERE a.s_id = ANY(w.ids)
  AND (w.availability IS NULL OR a.avl_self = ANY(w.availability))
  AND (w.is_repeatable IS NULL OR q.is_repeatable = w.is_repeatable)
ORDER BY a.s_id
`

type FilterQuestIDsByAvailabilityParams struct {
	Ids          []int32
	Availability []AvailabilityType
	IsRepeatable sql.NullBool
}

func (q *Queries) FilterQuestIDsByAvailability(ctx context.Context, arg FilterQuestIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterQuestIDsByAvailability, pq.Array(arg.Ids), pq.Array(arg.Availability), arg.IsRepeatable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var s_id int32
		if err := rows.Scan(&s_id); err != nil {
			return nil, err
		}
		items = append(items, s_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterShopIDsByAvailability = `-- name: FilterShopIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::availability_type[] AS availability,
        $4::text[] AS reqs,
        $5::text[] AS excls,
        $6::int AS auto_ability_id,
        $7::int[] AS empty_slots,
        $8::int AS character_id
),
available_shops AS (
    SELECT 
        a.s_id AS shop_id,
        CASE 
            WHEN w.avl_type = 'self' THEN a.avl_self
            WHEN w.avl_type = 'context' THEN a.avl_context
            WHEN w.avl_type = 'area' THEN a.avl_area
        END AS current_avl,
        a.sub_type AS s_type
    FROM mv_availabilities a
    JOIN w ON a.s_id = ANY(w.ids)
    WHERE a.source_type = 'shop'

    UNION ALL

    SELECT 
        es.source_id AS shop_id,
        CASE 
            WHEN w.avl_type = 'self' THEN es.avl_self
            WHEN w.avl_type = 'context' THEN es.avl_context
            WHEN w.avl_type = 'area' THEN es.avl_area
        END AS current_avl,
        'equip_filter' AS s_type
    FROM mv_equipment_sources es
    JOIN w ON es.source_id = ANY(w.ids)
    WHERE es.source_type = 'shop'
      AND (w.auto_ability_id IS NULL OR es.auto_ability_id = w.auto_ability_id)
      AND (w.empty_slots IS NULL OR es.empty_slots_amount::int = ANY(w.empty_slots))
      AND (w.character_id IS NULL OR es.character_id = w.character_id)
)
SELECT shop_id
FROM available_shops
CROSS JOIN w
GROUP BY shop_id, w.availability, w.reqs, w.excls, w.auto_ability_id, w.empty_slots, w.character_id
HAVING (w.availability IS NULL OR MIN(current_avl) = ANY(w.availability))
   AND (w.reqs IS NULL OR ARRAY_AGG(s_type) @> w.reqs)
   AND (w.excls IS NULL OR NOT ARRAY_AGG(s_type) && w.excls)
ORDER BY shop_id
`

type FilterShopIDsByAvailabilityParams struct {
	Ids             []int32
	AvlType         string
	Availability    []AvailabilityType
	RequiredSources []string
	ExcludedSources []string
	AutoAbilityID   sql.NullInt32
	EmptySlots      []int32
	CharacterID     sql.NullInt32
}

func (q *Queries) FilterShopIDsByAvailability(ctx context.Context, arg FilterShopIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterShopIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		pq.Array(arg.RequiredSources),
		pq.Array(arg.ExcludedSources),
		arg.AutoAbilityID,
		pq.Array(arg.EmptySlots),
		arg.CharacterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var shop_id int32
		if err := rows.Scan(&shop_id); err != nil {
			return nil, err
		}
		items = append(items, shop_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterSidequestIDsByAvailability = `-- name: FilterSidequestIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability,
        $3::boolean AS is_repeatable
)
SELECT DISTINCT s.id
FROM sidequests s
JOIN quests q ON s.quest_id = q.id
JOIN mv_availabilities a ON q.id = a.s_id AND a.source_type = 'quest'
CROSS JOIN w
WHERE s.id = ANY(w.ids)
  AND (w.availability IS NULL OR a.avl_self = ANY(w.availability))
  AND (w.is_repeatable IS NULL OR q.is_repeatable = w.is_repeatable)
ORDER BY s.id
`

type FilterSidequestIDsByAvailabilityParams struct {
	Ids          []int32
	Availability []AvailabilityType
	IsRepeatable sql.NullBool
}

func (q *Queries) FilterSidequestIDsByAvailability(ctx context.Context, arg FilterSidequestIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterSidequestIDsByAvailability, pq.Array(arg.Ids), pq.Array(arg.Availability), arg.IsRepeatable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterSphereIDsByAvailability = `-- name: FilterSphereIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::availability_type[] AS availability,
        $4::int AS loc_context_id,
        $5::text AS loc_context_type,
        $6::boolean AS is_repeatable
),
available_spheres AS (
    SELECT 
        s.id AS sphere_id,
        CASE
            WHEN mis.source_type = 'shop' AND w.avl_type = 'self' THEN mis.avl_context
            WHEN w.avl_type = 'self' THEN mis.avl_self
            WHEN w.avl_type = 'context' THEN mis.avl_context
            WHEN w.avl_type = 'area' THEN mis.avl_area
        END AS current_avl,
        CASE
            WHEN w.loc_context_id IS NOT NULL THEN mis.is_repeatable_loc
            ELSE mis.is_repeatable
        END AS is_rep
    FROM spheres s
    JOIN items i ON s.item_id = i.id
    JOIN mv_item_sources mis ON mis.master_item_id = i.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE s.id = ANY(w.ids)
      AND (w.loc_context_id IS NULL OR CASE
           WHEN w.loc_context_type = 'location' THEN g.location_id
           WHEN w.loc_context_type = 'sublocation' THEN g.sublocation_id
           WHEN w.loc_context_type = 'area' THEN g.area_id
          END = w.loc_context_id)
)
SELECT sphere_id
FROM available_spheres
CROSS JOIN w
GROUP BY sphere_id, w.availability, w.is_repeatable
HAVING (w.availability IS NULL OR MIN(current_avl) = ANY(w.availability))
   AND (w.is_repeatable IS NULL OR BOOL_OR(is_rep) = w.is_repeatable)
`

type FilterSphereIDsByAvailabilityParams struct {
	Ids            []int32
	AvlType        string
	Availability   []AvailabilityType
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
	IsRepeatable   sql.NullBool
}

func (q *Queries) FilterSphereIDsByAvailability(ctx context.Context, arg FilterSphereIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterSphereIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		arg.LocContextID,
		arg.LocContextType,
		arg.IsRepeatable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var sphere_id int32
		if err := rows.Scan(&sphere_id); err != nil {
			return nil, err
		}
		items = append(items, sphere_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterSublocationIDsByAvailability = `-- name: FilterSublocationIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability,
        $3::text[] AS reqs,
        $4::text[] AS excls,
        $5::int AS monster_id,
        $6::int AS key_item_id,
        $7::int AS item_id,
        $8::text[] AS methods,
        $9::boolean AS is_repeatable
),
available_sublocations AS (
    SELECT
        s.id AS sublocation_id,
        s.availability AS current_avl,
        NULL::boolean AS is_rep,
        'sublocation'::text AS s_type
    FROM sublocations s
    JOIN w ON s.id = ANY(w.ids)

    UNION ALL

    SELECT
        g.sublocation_id,
        me.avl_context AS current_avl,
        me.is_repeatable_loc AS is_rep,
        'monster'::text AS s_type
    FROM mv_monster_encounters me
    JOIN mv_geography g ON me.area_id = g.area_id
    JOIN w ON g.sublocation_id = ANY(w.ids)
    WHERE me.monster_id = w.monster_id
      AND (w.availability IS NULL OR me.avl_context = ANY(w.availability))

    UNION ALL

    SELECT
        g.sublocation_id,
        'always'::availability_type AS current_avl,
        mis.is_repeatable_loc AS is_rep,
        'item'::text AS s_type
    FROM mv_item_sources mis
    JOIN items i ON mis.master_item_id = i.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    JOIN w ON g.sublocation_id = ANY(w.ids)
    WHERE i.id = w.item_id
      AND mis.avl_context = ANY(w.availability)
      AND (w.methods IS NULL OR mis.source_type = ANY(w.methods))

    UNION ALL

    SELECT
        g.sublocation_id,
        'always'::availability_type AS current_avl, 
        mis.is_repeatable_loc AS is_rep,
        'key-item'::text AS s_type
    FROM mv_item_sources mis
    JOIN key_items ki ON mis.master_item_id = ki.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    JOIN w ON g.sublocation_id = ANY(w.ids)
    WHERE ki.id = w.key_item_id
      AND mis.avl_context = ANY(w.availability)

    UNION ALL

    SELECT
        g.sublocation_id,
        'always'::availability_type AS current_avl,
        a.is_repeatable_loc AS is_rep,
        CASE
          WHEN a.sub_type = 'boss' THEN 'boss'::text
          ELSE a.source_type
        END AS s_type
    FROM mv_availabilities a
    JOIN mv_geography g ON a.a_id = g.area_id
    JOIN w ON g.sublocation_id = ANY(w.ids)
    WHERE a.source_type != 'area'
      AND CASE
        WHEN a.source_type = 'shop' THEN a.avl_self
        ELSE a.avl_context
      END = ANY(w.availability)
)
SELECT sublocation_id
FROM available_sublocations
CROSS JOIN w
GROUP BY sublocation_id, w.availability, w.is_repeatable, w.reqs, w.excls
HAVING (w.availability IS NULL OR MAX(current_avl) = ANY(w.availability))
   AND (w.is_repeatable IS NULL OR BOOL_OR(is_rep) = w.is_repeatable)
   AND (w.reqs IS NULL OR ARRAY_AGG(s_type) @> w.reqs)
   AND (w.excls IS NULL OR NOT ARRAY_AGG(s_type) && w.excls)
ORDER BY sublocation_id
`

type FilterSublocationIDsByAvailabilityParams struct {
	Ids             []int32
	Availability    []AvailabilityType
	RequiredSources []string
	ExcludedSources []string
	MonsterID       sql.NullInt32
	KeyItemID       sql.NullInt32
	ItemID          sql.NullInt32
	Methods         []string
	IsRepeatable    sql.NullBool
}

func (q *Queries) FilterSublocationIDsByAvailability(ctx context.Context, arg FilterSublocationIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterSublocationIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		pq.Array(arg.RequiredSources),
		pq.Array(arg.ExcludedSources),
		arg.MonsterID,
		arg.KeyItemID,
		arg.ItemID,
		pq.Array(arg.Methods),
		arg.IsRepeatable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var sublocation_id int32
		if err := rows.Scan(&sublocation_id); err != nil {
			return nil, err
		}
		items = append(items, sublocation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterSubquestIDsByAvailability = `-- name: FilterSubquestIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability,
        $3::boolean AS is_repeatable
)
SELECT DISTINCT s.id
FROM subquests s
JOIN quests q ON s.quest_id = q.id
JOIN mv_availabilities a ON q.id = a.s_id AND a.source_type = 'quest'
CROSS JOIN w
WHERE s.id = ANY(w.ids)
  AND (w.availability IS NULL OR a.avl_self = ANY(w.availability))
  AND (w.is_repeatable IS NULL OR q.is_repeatable = w.is_repeatable)
ORDER BY s.id
`

type FilterSubquestIDsByAvailabilityParams struct {
	Ids          []int32
	Availability []AvailabilityType
	IsRepeatable sql.NullBool
}

func (q *Queries) FilterSubquestIDsByAvailability(ctx context.Context, arg FilterSubquestIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterSubquestIDsByAvailability, pq.Array(arg.Ids), pq.Array(arg.Availability), arg.IsRepeatable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterTreasureIDsByAvailability = `-- name: FilterTreasureIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability
)
SELECT DISTINCT a.s_id
FROM mv_availabilities a
CROSS JOIN w
WHERE a.source_type = 'treasure'
  AND a.s_id = ANY(w.ids)
  AND a.avl_self = ANY(w.availability)
ORDER BY a.s_id
`

type FilterTreasureIDsByAvailabilityParams struct {
	Ids          []int32
	Availability []AvailabilityType
}

func (q *Queries) FilterTreasureIDsByAvailability(ctx context.Context, arg FilterTreasureIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterTreasureIDsByAvailability, pq.Array(arg.Ids), pq.Array(arg.Availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var s_id int32
		if err := rows.Scan(&s_id); err != nil {
			return nil, err
		}
		items = append(items, s_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
