// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: availability.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const filterAreaIDsByAvailability = `-- name: FilterAreaIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::int[] AS availability,
        $3::boolean AS is_repeatable,
        $4::boolean AS pre_airship,
        $5::text[] AS reqs,
        $6::text[] AS excls,
        $7::int AS monster_id,
        $8::int AS key_item_id,
        $9::int AS item_id,
        $10::int AS auto_ability_id,
        $11::text[] AS methods
),
all_areas AS (
    SELECT id AS area_id, 'area' AS s_type 
    FROM areas
    CROSS JOIN w
    WHERE id = ANY(w.ids)
),
raw_res_areas AS (
    SELECT
        me.area_id,
        'monster-single'::text AS s_type,
        get_avl_rank(me.avl_context_2, w.pre_airship) AS current_avl,
        me.is_repeatable_loc AS is_rep
    FROM mv_monster_encounters me
    CROSS JOIN w
    WHERE me.area_id = ANY(w.ids)
        AND me.monster_id = w.monster_id

    UNION ALL

    SELECT
        mis.area_id,
        'item'::text AS s_type,
        get_avl_rank(mis.avl_context_2, w.pre_airship) AS current_avl,
        mis.is_repeatable_loc AS is_rep
    FROM mv_item_sources mis
    JOIN items i ON mis.master_item_id = i.master_item_id
    CROSS JOIN w
    WHERE mis.area_id = ANY(w.ids)
        AND i.id = w.item_id
        AND (w.methods IS NULL OR mis.source_type = ANY(w.methods))

    UNION ALL

    SELECT
        mis.area_id,
        'key-item'::text AS s_type,
        get_avl_rank(mis.avl_context_2, w.pre_airship) AS current_avl,
        mis.is_repeatable_loc AS is_rep
    FROM mv_item_sources mis
    JOIN key_items ki ON mis.master_item_id = ki.master_item_id
    CROSS JOIN w
    WHERE mis.area_id = ANY(w.ids)
        AND ki.id = w.key_item_id

    UNION ALL

    SELECT
        aas.area_id,
        'auto-ability'::text AS s_type,
        get_avl_rank(aas.avl_context_2, w.pre_airship) AS current_avl,
        aas.is_repeatable_loc AS is_rep
    FROM mv_auto_ability_sources aas
    CROSS JOIN w
    WHERE aas.area_id = ANY(w.ids)
        AND aas.auto_ability_id = w.auto_ability_id
),
raw_res_areas_rep AS (
    SELECT
        area_id,
        s_type,
        current_avl,
        BOOL_OR(is_rep) AS is_rep
    FROM raw_res_areas
    GROUP BY area_id, s_type, current_avl
),
filtered_res_areas AS (
    SELECT a.area_id, a.s_type
    FROM raw_res_areas_rep a
    CROSS JOIN w
    GROUP BY a.area_id, a.s_type, w.availability, w.is_repeatable
    HAVING filter_avl_rep(
        MIN(a.current_avl),
        BOOL_OR(a.is_rep = w.is_repeatable),
        MIN(a.current_avl) FILTER (WHERE a.is_rep = w.is_repeatable),
        BOOL_OR(a.is_rep) FILTER (WHERE a.current_avl = ANY(w.availability)),
        MIN(a.current_avl) FILTER (WHERE a.is_rep = FALSE),
        w.availability,
        w.is_repeatable
    )
),
content_areas AS (
    SELECT area_id, s_type FROM (
        SELECT
            a.a_id AS area_id,
            a.s_id AS source_id,
            a.source_type AS s_type,
            get_avl_rank_condition(a.avl_context_2, a.avl_self, w.pre_airship, (a.source_type = 'monster')) AS current_avl
        FROM mv_availabilities a
        CROSS JOIN w
        WHERE a.a_id = ANY(w.ids)
          AND a.source_type != 'area'

        UNION ALL

        SELECT
            a.a_id as area_id,
            a.s_id as source_id,
            a.sub_type AS s_type,
            get_avl_rank(a.avl_context_2, w.pre_airship) AS current_avl
        FROM mv_availabilities a
        CROSS JOIN w
        WHERE a.a_id = ANY(w.ids)
          AND a.sub_type = 'boss'
    ) as c
    CROSS JOIN w
    GROUP BY area_id, source_id, s_type, w.availability
    HAVING w.availability IS NULL OR MIN(current_avl) = ANY(w.availability)
),
final_combination AS (
    SELECT area_id, s_type FROM all_areas
    UNION ALL
    SELECT area_id, s_type FROM filtered_res_areas
    UNION ALL
    SELECT area_id, s_type FROM content_areas
)
SELECT area_id
FROM final_combination
CROSS JOIN w
GROUP BY area_id, w.reqs, w.excls
HAVING ARRAY_AGG(s_type) @> w.reqs
   AND (w.excls IS NULL OR NOT ARRAY_AGG(s_type) && w.excls)
ORDER BY area_id
`

type FilterAreaIDsByAvailabilityParams struct {
	Ids             []int32
	Availability    []int32
	IsRepeatable    sql.NullBool
	PreAirship      bool
	RequiredSources []string
	ExcludedSources []string
	MonsterID       sql.NullInt32
	KeyItemID       sql.NullInt32
	ItemID          sql.NullInt32
	AutoAbilityID   sql.NullInt32
	Methods         []string
}

func (q *Queries) FilterAreaIDsByAvailability(ctx context.Context, arg FilterAreaIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterAreaIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.PreAirship,
		pq.Array(arg.RequiredSources),
		pq.Array(arg.ExcludedSources),
		arg.MonsterID,
		arg.KeyItemID,
		arg.ItemID,
		arg.AutoAbilityID,
		pq.Array(arg.Methods),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var area_id int32
		if err := rows.Scan(&area_id); err != nil {
			return nil, err
		}
		items = append(items, area_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterAreaIDsByAvailabilitySoft = `-- name: FilterAreaIDsByAvailabilitySoft :many
SELECT DISTINCT id FROM areas WHERE get_avl_rank(availability, false) = ANY($1::int[]) ORDER BY id
`

func (q *Queries) FilterAreaIDsByAvailabilitySoft(ctx context.Context, availability []int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterAreaIDsByAvailabilitySoft, pq.Array(availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterAutoAbilityIDsByAvailability = `-- name: FilterAutoAbilityIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::int[] AS availability,
        $4::boolean AS is_repeatable,
        $5::boolean AS pre_airship,
        $6::int AS loc_context_id,
        $7::text AS loc_context_type,
        $8::int AS character_id,
        $9::text[] AS methods,
        $10::boolean AS customize
),
raw_auto_abilities AS (
    SELECT
        aas.auto_ability_id,
        get_avl_rank_auto_ability(aas.source_type, w.avl_type, w.loc_context_type, aas.character_id, w.pre_airship, aas.avl_self, aas.avl_context, aas.avl_context_2, aas.avl_shop_loc, aas.avl_shop_subloc, aas.avl_shop_area, aas.avl_shop_loc_char, aas.avl_shop_subloc_char, aas.avl_shop_area_char) AS current_avl,
        get_is_rep(w.loc_context_id, aas.is_repeatable, aas.is_repeatable_loc) AS is_rep
    FROM mv_auto_ability_sources aas
    JOIN mv_geography g ON aas.area_id = g.area_id
    CROSS JOIN w
    WHERE aas.auto_ability_id = ANY(w.ids)
    AND w.customize = FALSE
    AND (w.character_id IS NULL OR aas.character_id = w.character_id OR aas.character_id IS NULL)
    AND (w.methods IS NULL OR aas.source_type = ANY(w.methods))
    AND (w.loc_context_id IS NULL OR get_loc_ctx_id(w.loc_context_type, g.location_id, g.sublocation_id, g.area_id) = w.loc_context_id)

    UNION ALL

    SELECT sub.auto_ability_id, sub.current_avl, sub.is_rep FROM (
        SELECT
            calc.auto_ability_id,
            calc.current_avl,
            calc.is_rep,
            BOOL_OR(calc.is_rep) FILTER (WHERE w.availability IS NULL OR calc.current_avl = ANY(w.availability)) 
                OVER (PARTITION BY calc.auto_ability_id) AS group_is_rep,
            SUM(calc.amount) FILTER (WHERE NOT calc.is_rep AND (w.availability IS NULL OR calc.current_avl = ANY(w.availability)))
                OVER (PARTITION BY calc.auto_ability_id) AS group_total_amt,
            calc.req_amount
        FROM (
            SELECT
                aa.id AS auto_ability_id,
                mis.amount,
                ia_req.amount AS req_amount,
                get_avl_rank_item(mis.source_type, w.avl_type, w.loc_context_type, w.pre_airship, mis.avl_self, mis.avl_context, mis.avl_context_2, mis.avl_shop_loc, mis.avl_shop_subloc, mis.avl_shop_area) AS current_avl,
                get_is_rep(w.loc_context_id, mis.is_repeatable, mis.is_repeatable_loc) AS is_rep
            FROM auto_abilities aa
            JOIN item_amounts ia_req ON aa.required_item_amount_id = ia_req.id
            JOIN mv_item_sources mis ON mis.master_item_id = ia_req.master_item_id
            JOIN mv_geography g ON mis.area_id = g.area_id
            CROSS JOIN w
            WHERE aa.id = ANY(w.ids)
            AND w.customize = TRUE
            AND (w.loc_context_id IS NULL OR get_loc_ctx_id(w.loc_context_type, g.location_id, g.sublocation_id, g.area_id) = w.loc_context_id)
        ) AS calc
        CROSS JOIN w
    ) AS sub
    WHERE sub.group_is_rep OR (COALESCE(sub.group_total_amt, 0) >= sub.req_amount)
),
auto_abilities_rep AS (
    SELECT
        auto_ability_id,
        current_avl,
        BOOL_OR(is_rep) AS is_rep
    FROM raw_auto_abilities
    GROUP BY auto_ability_id, current_avl
)
SELECT a.auto_ability_id
FROM auto_abilities_rep a
CROSS JOIN w
GROUP BY a.auto_ability_id, w.availability, w.is_repeatable
HAVING filter_avl_rep(
    MIN(a.current_avl),
    BOOL_OR(a.is_rep = w.is_repeatable),
    MIN(a.current_avl) FILTER (WHERE a.is_rep = w.is_repeatable),
    BOOL_OR(a.is_rep) FILTER (WHERE a.current_avl = ANY(w.availability)),
    MIN(a.current_avl) FILTER (WHERE a.is_rep = FALSE),
    w.availability,
    w.is_repeatable
)
ORDER BY a.auto_ability_id
`

type FilterAutoAbilityIDsByAvailabilityParams struct {
	Ids            []int32
	AvlType        string
	Availability   []int32
	IsRepeatable   sql.NullBool
	PreAirship     bool
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
	CharacterID    sql.NullInt32
	Methods        []string
	Customize      bool
}

func (q *Queries) FilterAutoAbilityIDsByAvailability(ctx context.Context, arg FilterAutoAbilityIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterAutoAbilityIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.PreAirship,
		arg.LocContextID,
		arg.LocContextType,
		arg.CharacterID,
		pq.Array(arg.Methods),
		arg.Customize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var auto_ability_id int32
		if err := rows.Scan(&auto_ability_id); err != nil {
			return nil, err
		}
		items = append(items, auto_ability_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterItemIDsByAvailability = `-- name: FilterItemIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::int[] AS availability,
        $4::boolean AS is_repeatable,
        $5::boolean AS pre_airship,
        $6::int AS loc_context_id,
        $7::text AS loc_context_type,
        $8::text[] AS methods
),
raw_items AS (
    SELECT
        i.id AS item_id,
        get_avl_rank_item(mis.source_type, w.avl_type, w.loc_context_type, w.pre_airship, mis.avl_self, mis.avl_context, mis.avl_context_2, mis.avl_shop_loc, mis.avl_shop_subloc, mis.avl_shop_area) AS current_avl,
        get_is_rep(w.loc_context_id, mis.is_repeatable, mis.is_repeatable_loc) AS is_rep
    FROM items i
    JOIN mv_item_sources mis ON mis.master_item_id = i.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE i.id = ANY(w.ids)
    AND (w.methods IS NULL OR mis.source_type = ANY(w.methods))
    AND (w.loc_context_id IS NULL OR get_loc_ctx_id(w.loc_context_type, g.location_id, g.sublocation_id, g.area_id) = w.loc_context_id)
),
items_rep AS (
    SELECT
        item_id,
        current_avl,
        BOOL_OR(is_rep) AS is_rep
    FROM raw_items
    GROUP BY item_id, current_avl
)
SELECT i.item_id
FROM items_rep i
CROSS JOIN w
GROUP BY i.item_id, w.availability, w.is_repeatable
HAVING filter_avl_rep(
    MIN(i.current_avl),
    BOOL_OR(i.is_rep = w.is_repeatable),
    MIN(i.current_avl) FILTER (WHERE i.is_rep = w.is_repeatable),
    BOOL_OR(i.is_rep) FILTER (WHERE i.current_avl = ANY(w.availability)),
    MIN(i.current_avl) FILTER (WHERE i.is_rep = FALSE),
    w.availability,
    w.is_repeatable
)
ORDER BY i.item_id
`

type FilterItemIDsByAvailabilityParams struct {
	Ids            []int32
	AvlType        string
	Availability   []int32
	IsRepeatable   sql.NullBool
	PreAirship     bool
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
	Methods        []string
}

func (q *Queries) FilterItemIDsByAvailability(ctx context.Context, arg FilterItemIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterItemIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.PreAirship,
		arg.LocContextID,
		arg.LocContextType,
		pq.Array(arg.Methods),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var item_id int32
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterKeyItemIDsByAvailability = `-- name: FilterKeyItemIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::int[] AS availability,
        $3::boolean AS pre_airship,
        $4::int AS loc_context_id,
        $5::text AS loc_context_type,
        $6::text[] AS methods
)
SELECT ki.id
FROM key_items ki
JOIN mv_item_sources mis ON mis.master_item_id = ki.master_item_id
JOIN mv_geography g ON mis.area_id = g.area_id
CROSS JOIN w
WHERE ki.id = ANY(w.ids)
  AND (w.methods IS NULL OR mis.source_type = ANY(w.methods))
  AND (w.loc_context_id IS NULL OR get_loc_ctx_id(w.loc_context_type, g.location_id, g.sublocation_id, g.area_id) = w.loc_context_id)
GROUP BY ki.id, w.availability, w.pre_airship
HAVING MIN(get_avl_rank(mis.avl_self, w.pre_airship)) = ANY(w.availability)
ORDER BY ki.id
`

type FilterKeyItemIDsByAvailabilityParams struct {
	Ids            []int32
	Availability   []int32
	PreAirship     bool
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
	Methods        []string
}

func (q *Queries) FilterKeyItemIDsByAvailability(ctx context.Context, arg FilterKeyItemIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterKeyItemIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		arg.PreAirship,
		arg.LocContextID,
		arg.LocContextType,
		pq.Array(arg.Methods),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterLocationIDsByAvailability = `-- name: FilterLocationIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::int[] AS availability,
        $3::boolean AS is_repeatable,
        $4::boolean AS pre_airship,
        $5::text[] AS reqs,
        $6::text[] AS excls,
        $7::int AS monster_id,
        $8::int AS key_item_id,
        $9::int AS item_id,
        $10::int AS auto_ability_id,
        $11::text[] AS methods
),
all_locations AS (
    SELECT id AS location_id, 'location' AS s_type 
    FROM locations
    CROSS JOIN w
    WHERE id = ANY(w.ids)
),
raw_res_locations AS (
    SELECT
        g.location_id,
        'monster-single'::text AS s_type,
        get_avl_rank(me.avl_context, w.pre_airship) AS current_avl,
        me.is_repeatable_loc AS is_rep
    FROM mv_monster_encounters me
    JOIN mv_geography g ON me.area_id = g.area_id
    CROSS JOIN w
    WHERE g.location_id = ANY(w.ids)
        AND me.monster_id = w.monster_id

    UNION ALL

    SELECT
        g.location_id,
        'item'::text AS s_type,
        get_avl_rank(mis.avl_context, w.pre_airship) AS current_avl,
        mis.is_repeatable_loc AS is_rep
    FROM mv_item_sources mis
    JOIN items i ON mis.master_item_id = i.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE g.location_id = ANY(w.ids)
        AND i.id = w.item_id
        AND (w.methods IS NULL OR mis.source_type = ANY(w.methods))

    UNION ALL

    SELECT
        g.location_id,
        'key-item'::text AS s_type,
        get_avl_rank(mis.avl_context, w.pre_airship) AS current_avl,
        mis.is_repeatable_loc AS is_rep
    FROM mv_item_sources mis
    JOIN key_items ki ON mis.master_item_id = ki.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE g.location_id = ANY(w.ids)
        AND ki.id = w.key_item_id

    UNION ALL

    SELECT
        g.location_id,
        'auto-ability'::text AS s_type,
        get_avl_rank(aas.avl_context, w.pre_airship) AS current_avl,
        aas.is_repeatable_loc AS is_rep
    FROM mv_auto_ability_sources aas
    JOIN mv_geography g ON aas.area_id = g.area_id
    CROSS JOIN w
    WHERE g.location_id = ANY(w.ids)
        AND aas.auto_ability_id = w.auto_ability_id
),
raw_res_locations_rep AS (
    SELECT
        location_id,
        s_type,
        current_avl,
        BOOL_OR(is_rep) AS is_rep
    FROM raw_res_locations
    GROUP BY location_id, s_type, current_avl
),
filtered_res_locations AS (
    SELECT l.location_id, l.s_type
    FROM raw_res_locations_rep l
    CROSS JOIN w
    GROUP BY l.location_id, l.s_type, w.availability, w.is_repeatable
    HAVING filter_avl_rep(
        MIN(l.current_avl),
        BOOL_OR(l.is_rep = w.is_repeatable),
        MIN(l.current_avl) FILTER (WHERE l.is_rep = w.is_repeatable),
        BOOL_OR(l.is_rep) FILTER (WHERE l.current_avl = ANY(w.availability)),
        MIN(l.current_avl) FILTER (WHERE l.is_rep = FALSE),
        w.availability,
        w.is_repeatable
    )
),
content_locations AS (
    SELECT location_id, s_type FROM (
        SELECT
            g.location_id,
            a.s_id as source_id, 
            a.source_type AS s_type,
            get_avl_rank_condition(a.avl_self, a.avl_context, w.pre_airship, (a.source_type = 'shop')) AS current_avl
        FROM mv_availabilities a
        JOIN mv_geography g ON a.a_id = g.area_id
        CROSS JOIN w
        WHERE g.location_id = ANY(w.ids)
          AND a.source_type != 'area'

        UNION ALL

        SELECT
            g.location_id,
            a.s_id as source_id,
            a.sub_type AS s_type,
            get_avl_rank(a.avl_context, w.pre_airship) AS current_avl
        FROM mv_availabilities a
        JOIN mv_geography g ON a.a_id = g.area_id
        CROSS JOIN w
        WHERE g.location_id = ANY(w.ids)
          AND a.sub_type = 'boss'
    ) as c
    CROSS JOIN w
    GROUP BY location_id, source_id, s_type, w.availability
    HAVING w.availability IS NULL OR MIN(current_avl) = ANY(w.availability)
),
final_combination AS (
    SELECT location_id, s_type FROM all_locations
    UNION ALL
    SELECT location_id, s_type FROM filtered_res_locations
    UNION ALL
    SELECT location_id, s_type FROM content_locations
)
SELECT location_id
FROM final_combination
CROSS JOIN w
GROUP BY location_id, w.reqs, w.excls
HAVING ARRAY_AGG(s_type) @> w.reqs
   AND (w.excls IS NULL OR NOT ARRAY_AGG(s_type) && w.excls)
ORDER BY location_id
`

type FilterLocationIDsByAvailabilityParams struct {
	Ids             []int32
	Availability    []int32
	IsRepeatable    sql.NullBool
	PreAirship      bool
	RequiredSources []string
	ExcludedSources []string
	MonsterID       sql.NullInt32
	KeyItemID       sql.NullInt32
	ItemID          sql.NullInt32
	AutoAbilityID   sql.NullInt32
	Methods         []string
}

func (q *Queries) FilterLocationIDsByAvailability(ctx context.Context, arg FilterLocationIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterLocationIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.PreAirship,
		pq.Array(arg.RequiredSources),
		pq.Array(arg.ExcludedSources),
		arg.MonsterID,
		arg.KeyItemID,
		arg.ItemID,
		arg.AutoAbilityID,
		pq.Array(arg.Methods),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var location_id int32
		if err := rows.Scan(&location_id); err != nil {
			return nil, err
		}
		items = append(items, location_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterLocationIDsByAvailabilitySoft = `-- name: FilterLocationIDsByAvailabilitySoft :many
SELECT DISTINCT id FROM locations WHERE get_avl_rank(availability, false) = ANY($1::int[]) ORDER BY id
`

func (q *Queries) FilterLocationIDsByAvailabilitySoft(ctx context.Context, availability []int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterLocationIDsByAvailabilitySoft, pq.Array(availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterMasterItemIDsByAvailability = `-- name: FilterMasterItemIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::int[] AS availability,
        $4::boolean AS is_repeatable,
        $5::boolean AS pre_airship,
        $6::int AS loc_context_id,
        $7::text AS loc_context_type,
        $8::text[] AS methods
),
raw_master_items AS (
    SELECT
        mis.master_item_id,
        get_avl_rank_item(mis.source_type, w.avl_type, w.loc_context_type, w.pre_airship, mis.avl_self, mis.avl_context, mis.avl_context_2, mis.avl_shop_loc, mis.avl_shop_subloc, mis.avl_shop_area) AS current_avl,
        get_is_rep(w.loc_context_id, mis.is_repeatable, mis.is_repeatable_loc) AS is_rep
    FROM mv_item_sources mis
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE mis.master_item_id = ANY(w.ids)
    AND (w.methods IS NULL OR mis.source_type = ANY(w.methods))
    AND (w.loc_context_id IS NULL OR get_loc_ctx_id(w.loc_context_type, g.location_id, g.sublocation_id, g.area_id) = w.loc_context_id)
),
master_items_rep AS (
    SELECT
        master_item_id,
        current_avl,
        BOOL_OR(is_rep) AS is_rep
    FROM raw_master_items
    GROUP BY master_item_id, current_avl
)
SELECT mi.master_item_id
FROM master_items_rep mi
CROSS JOIN w
GROUP BY mi.master_item_id, w.availability, w.is_repeatable
HAVING filter_avl_rep(
    MIN(mi.current_avl),
    BOOL_OR(mi.is_rep = w.is_repeatable),
    MIN(mi.current_avl) FILTER (WHERE mi.is_rep = w.is_repeatable),
    BOOL_OR(mi.is_rep) FILTER (WHERE mi.current_avl = ANY(w.availability)),
    MIN(mi.current_avl) FILTER (WHERE mi.is_rep = FALSE),
    w.availability,
    w.is_repeatable
)
ORDER BY mi.master_item_id
`

type FilterMasterItemIDsByAvailabilityParams struct {
	Ids            []int32
	AvlType        string
	Availability   []int32
	IsRepeatable   sql.NullBool
	PreAirship     bool
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
	Methods        []string
}

func (q *Queries) FilterMasterItemIDsByAvailability(ctx context.Context, arg FilterMasterItemIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterMasterItemIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.PreAirship,
		arg.LocContextID,
		arg.LocContextType,
		pq.Array(arg.Methods),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var master_item_id int32
		if err := rows.Scan(&master_item_id); err != nil {
			return nil, err
		}
		items = append(items, master_item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterMonsterFormationIDsByAvailability = `-- name: FilterMonsterFormationIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::int[] AS availability,
        $3::boolean AS is_repeatable,
        $4::boolean AS pre_airship,
        $5::text AS avl_type,
        $6::int AS loc_context_id,
        $7::text AS loc_context_type
),
raw_formations AS (
    SELECT
        me.formation_id,
        get_avl_rank(select_avl(w.avl_type, me.avl_context, me.avl_context, me.avl_context_2), w.pre_airship) AS current_avl,
        me.is_repeatable_loc AS is_rep
    FROM mv_monster_encounters me
    JOIN mv_geography g ON me.area_id = g.area_id
    CROSS JOIN w
    WHERE me.formation_id = ANY(w.ids)
    AND (w.loc_context_id IS NULL OR get_loc_ctx_id(w.loc_context_type, g.location_id, g.sublocation_id, g.area_id) = w.loc_context_id)
),
formations_rep AS (
    SELECT
        formation_id,
        current_avl,
        BOOL_OR(is_rep) AS is_rep
    FROM raw_formations
    GROUP BY formation_id, current_avl
)
SELECT mf.formation_id
FROM formations_rep mf
CROSS JOIN w
GROUP BY mf.formation_id, w.availability, w.is_repeatable
HAVING filter_avl_rep(
    MIN(mf.current_avl),
    BOOL_OR(mf.is_rep = w.is_repeatable),
    MIN(mf.current_avl) FILTER (WHERE mf.is_rep = w.is_repeatable),
    BOOL_OR(mf.is_rep) FILTER (WHERE mf.current_avl = ANY(w.availability)),
    MIN(mf.current_avl) FILTER (WHERE mf.is_rep = FALSE),
    w.availability,
    w.is_repeatable
)
ORDER BY mf.formation_id
`

type FilterMonsterFormationIDsByAvailabilityParams struct {
	Ids            []int32
	Availability   []int32
	IsRepeatable   sql.NullBool
	PreAirship     bool
	AvlType        string
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
}

func (q *Queries) FilterMonsterFormationIDsByAvailability(ctx context.Context, arg FilterMonsterFormationIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterMonsterFormationIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.PreAirship,
		arg.AvlType,
		arg.LocContextID,
		arg.LocContextType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var formation_id int32
		if err := rows.Scan(&formation_id); err != nil {
			return nil, err
		}
		items = append(items, formation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterMonsterIDsByAvailability = `-- name: FilterMonsterIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::int[] AS availability,
        $3::boolean AS is_repeatable,
        $4::boolean AS pre_airship,
        $5::text AS avl_type,
        $6::int AS loc_context_id,
        $7::text AS loc_context_type
),
raw_monsters AS (
    SELECT
        me.monster_id,
        get_avl_rank(select_avl(w.avl_type, me.avl_self, me.avl_context, me.avl_context_2), w.pre_airship) AS current_avl,
        get_is_rep(w.loc_context_id, me.is_repeatable, me.is_repeatable_loc) AS is_rep
    FROM mv_monster_encounters me
    JOIN mv_geography g ON me.area_id = g.area_id
    CROSS JOIN w
    WHERE me.monster_id = ANY(w.ids)
    AND (w.loc_context_id IS NULL OR get_loc_ctx_id(w.loc_context_type, g.location_id, g.sublocation_id, g.area_id) = w.loc_context_id)
),
monsters_rep AS (
    SELECT
        monster_id,
        current_avl,
        BOOL_OR(is_rep) AS is_rep
    FROM raw_monsters
    GROUP BY monster_id, current_avl
)
SELECT m.monster_id
FROM monsters_rep m
CROSS JOIN w
GROUP BY m.monster_id, w.availability, w.is_repeatable
HAVING filter_avl_rep(
    MIN(m.current_avl),
    BOOL_OR(m.is_rep = w.is_repeatable),
    MIN(m.current_avl) FILTER (WHERE m.is_rep = w.is_repeatable),
    BOOL_OR(m.is_rep) FILTER (WHERE m.current_avl = ANY(w.availability)),
    MIN(m.current_avl) FILTER (WHERE m.is_rep = FALSE),
    w.availability,
    w.is_repeatable
)
ORDER BY m.monster_id
`

type FilterMonsterIDsByAvailabilityParams struct {
	Ids            []int32
	Availability   []int32
	IsRepeatable   sql.NullBool
	PreAirship     bool
	AvlType        string
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
}

func (q *Queries) FilterMonsterIDsByAvailability(ctx context.Context, arg FilterMonsterIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterMonsterIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.PreAirship,
		arg.AvlType,
		arg.LocContextID,
		arg.LocContextType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var monster_id int32
		if err := rows.Scan(&monster_id); err != nil {
			return nil, err
		}
		items = append(items, monster_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterPrimerIDsByAvailability = `-- name: FilterPrimerIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::int[] AS availability,
        $3::boolean AS pre_airship
)
SELECT p.id
FROM primers p
JOIN key_items ki ON p.key_item_id = ki.id
JOIN mv_item_sources mis ON mis.master_item_id = ki.master_item_id
CROSS JOIN w
WHERE p.id = ANY(w.ids)
GROUP BY p.id, w.availability, w.pre_airship
HAVING MIN(get_avl_rank(mis.avl_self, w.pre_airship)) = ANY(w.availability)
ORDER BY p.id
`

type FilterPrimerIDsByAvailabilityParams struct {
	Ids          []int32
	Availability []int32
	PreAirship   bool
}

func (q *Queries) FilterPrimerIDsByAvailability(ctx context.Context, arg FilterPrimerIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterPrimerIDsByAvailability, pq.Array(arg.Ids), pq.Array(arg.Availability), arg.PreAirship)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterQuestIDsByAvailability = `-- name: FilterQuestIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::int[] AS availability,
        $3::boolean AS is_repeatable,
        $4::boolean AS pre_airship
)
SELECT DISTINCT a.s_id
FROM quests q
JOIN mv_availabilities a ON q.id = a.s_id AND a.source_type = 'quest'
CROSS JOIN w
WHERE a.s_id = ANY(w.ids)
  AND (w.availability IS NULL OR get_avl_rank(a.avl_self, w.pre_airship) = ANY(w.availability))
  AND (w.is_repeatable IS NULL OR q.is_repeatable = w.is_repeatable)
ORDER BY a.s_id
`

type FilterQuestIDsByAvailabilityParams struct {
	Ids          []int32
	Availability []int32
	IsRepeatable sql.NullBool
	PreAirship   bool
}

func (q *Queries) FilterQuestIDsByAvailability(ctx context.Context, arg FilterQuestIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterQuestIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.PreAirship,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var s_id int32
		if err := rows.Scan(&s_id); err != nil {
			return nil, err
		}
		items = append(items, s_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterShopIDsByAvailability = `-- name: FilterShopIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::int[] AS availability,
        $4::int AS loc_context_id,
        $5::text AS loc_context_type,
        $6::text[] AS reqs,
        $7::text[] AS excls,
        $8::int AS auto_ability_id,
        $9::int[] AS empty_slots,
        $10::int AS character_id
),
available_shops AS (
    SELECT shop_id, s_type
    FROM (
        SELECT
            a.s_id AS shop_id,
            get_avl_rank(select_avl(w.avl_type, a.avl_self, a.avl_context, a.avl_context_2), FALSE) AS current_avl,
            a.sub_type AS s_type
        FROM mv_availabilities a
        JOIN mv_geography g ON a.a_id = g.area_id
        CROSS JOIN w
        WHERE a.s_id = ANY(w.ids)
          AND (w.auto_ability_id IS NULL AND w.empty_slots IS NULL AND w.character_id IS NULL)
          AND a.source_type = 'shop'
          AND (w.loc_context_id IS NULL OR get_loc_ctx_id(w.loc_context_type, g.location_id, g.sublocation_id, g.area_id) = w.loc_context_id)

        UNION ALL

        SELECT
            sa.shop_id,
            get_avl_rank(select_shop_equip_avl(w.auto_ability_id, w.character_id, w.empty_slots, sa.avl_acs, sa.avl_ac, sa.avl_as, sa.avl_cs, sa.avl_a, sa.avl_c, sa.avl_s, sa.avl_self), FALSE) AS current_avl,
            'equip-filter' AS s_type
        FROM mv_shop_equip_avls sa
        JOIN mv_geography g ON sa.area_id = g.area_id
        CROSS JOIN w
        WHERE sa.shop_id = ANY(w.ids)
        AND (w.auto_ability_id IS NOT NULL OR w.empty_slots IS NOT NULL OR w.character_id IS NOT NULL)
        AND (w.auto_ability_id IS NULL OR sa.auto_ability_id = w.auto_ability_id)
        AND (w.empty_slots IS NULL OR sa.empty_slots_amount::int = ANY(w.empty_slots))
        AND (w.character_id IS NULL OR sa.character_id = w.character_id)
        AND (w.loc_context_id IS NULL OR get_loc_ctx_id(w.loc_context_type, g.location_id, g.sublocation_id, g.area_id) = w.loc_context_id)
    ) AS raw_sources
    CROSS JOIN w
    GROUP BY shop_id, s_type, w.availability
    HAVING (w.availability IS NULL OR MIN(current_avl) = ANY(w.availability))
)
SELECT shop_id
FROM available_shops
CROSS JOIN w
GROUP BY shop_id, w.reqs, w.excls
HAVING (w.reqs IS NULL OR ARRAY_AGG(s_type) @> w.reqs)
   AND (w.excls IS NULL OR NOT ARRAY_AGG(s_type) && w.excls)
ORDER BY shop_id
`

type FilterShopIDsByAvailabilityParams struct {
	Ids             []int32
	AvlType         string
	Availability    []int32
	LocContextID    sql.NullInt32
	LocContextType  sql.NullString
	RequiredSources []string
	ExcludedSources []string
	AutoAbilityID   sql.NullInt32
	EmptySlots      []int32
	CharacterID     sql.NullInt32
}

func (q *Queries) FilterShopIDsByAvailability(ctx context.Context, arg FilterShopIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterShopIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		arg.LocContextID,
		arg.LocContextType,
		pq.Array(arg.RequiredSources),
		pq.Array(arg.ExcludedSources),
		arg.AutoAbilityID,
		pq.Array(arg.EmptySlots),
		arg.CharacterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var shop_id int32
		if err := rows.Scan(&shop_id); err != nil {
			return nil, err
		}
		items = append(items, shop_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterSidequestIDsByAvailability = `-- name: FilterSidequestIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::int[] AS availability,
        $3::boolean AS pre_airship
)
SELECT DISTINCT s.id
FROM sidequests s
JOIN quests q ON s.quest_id = q.id
JOIN mv_availabilities a ON q.id = a.s_id AND a.source_type = 'quest'
CROSS JOIN w
WHERE s.id = ANY(w.ids)
  AND (w.availability IS NULL OR get_avl_rank(a.avl_self, w.pre_airship) = ANY(w.availability))
ORDER BY s.id
`

type FilterSidequestIDsByAvailabilityParams struct {
	Ids          []int32
	Availability []int32
	PreAirship   bool
}

func (q *Queries) FilterSidequestIDsByAvailability(ctx context.Context, arg FilterSidequestIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterSidequestIDsByAvailability, pq.Array(arg.Ids), pq.Array(arg.Availability), arg.PreAirship)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterSphereIDsByAvailability = `-- name: FilterSphereIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::int[] AS availability,
        $4::boolean AS is_repeatable,
        $5::boolean AS pre_airship,
        $6::int AS loc_context_id,
        $7::text AS loc_context_type,
        $8::text[] AS methods
),
raw_spheres AS (
    SELECT
        s.id AS sphere_id,
        get_avl_rank_item(mis.source_type, w.avl_type, w.loc_context_type, w.pre_airship, mis.avl_self, mis.avl_context, mis.avl_context_2, mis.avl_shop_loc, mis.avl_shop_subloc, mis.avl_shop_area) AS current_avl,
        get_is_rep(w.loc_context_id, mis.is_repeatable, mis.is_repeatable_loc) AS is_rep
    FROM spheres s
    JOIN items i ON s.item_id = i.id
    JOIN mv_item_sources mis ON mis.master_item_id = i.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE s.id = ANY(w.ids)
    AND (w.methods IS NULL OR mis.source_type = ANY(w.methods))
    AND (w.loc_context_id IS NULL OR get_loc_ctx_id(w.loc_context_type, g.location_id, g.sublocation_id, g.area_id) = w.loc_context_id)
),
spheres_rep AS (
    SELECT
        sphere_id,
        current_avl,
        BOOL_OR(is_rep) AS is_rep
    FROM raw_spheres
    GROUP BY sphere_id, current_avl
)
SELECT s.sphere_id
FROM spheres_rep s
CROSS JOIN w
GROUP BY s.sphere_id, w.availability, w.is_repeatable
HAVING filter_avl_rep(
    MIN(s.current_avl),
    BOOL_OR(s.is_rep = w.is_repeatable),
    MIN(s.current_avl) FILTER (WHERE s.is_rep = w.is_repeatable),
    BOOL_OR(s.is_rep) FILTER (WHERE s.current_avl = ANY(w.availability)),
    MIN(s.current_avl) FILTER (WHERE s.is_rep = FALSE),
    w.availability,
    w.is_repeatable
)
ORDER BY s.sphere_id
`

type FilterSphereIDsByAvailabilityParams struct {
	Ids            []int32
	AvlType        string
	Availability   []int32
	IsRepeatable   sql.NullBool
	PreAirship     bool
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
	Methods        []string
}

func (q *Queries) FilterSphereIDsByAvailability(ctx context.Context, arg FilterSphereIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterSphereIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.PreAirship,
		arg.LocContextID,
		arg.LocContextType,
		pq.Array(arg.Methods),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var sphere_id int32
		if err := rows.Scan(&sphere_id); err != nil {
			return nil, err
		}
		items = append(items, sphere_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterSublocationIDsByAvailability = `-- name: FilterSublocationIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::int[] AS availability,
        $3::boolean AS is_repeatable,
        $4::boolean AS pre_airship,
        $5::text[] AS reqs,
        $6::text[] AS excls,
        $7::int AS monster_id,
        $8::int AS key_item_id,
        $9::int AS item_id,
        $10::int AS auto_ability_id,
        $11::text[] AS methods
),
all_sublocations AS (
    SELECT id AS sublocation_id, 'sublocation' AS s_type 
    FROM sublocations
    CROSS JOIN w
    WHERE id = ANY(w.ids)
),
raw_res_sublocations AS (
    SELECT
        g.sublocation_id,
        'monster-single'::text AS s_type,
        get_avl_rank(me.avl_context, w.pre_airship) AS current_avl,
        me.is_repeatable_loc AS is_rep
    FROM mv_monster_encounters me
    JOIN mv_geography g ON me.area_id = g.area_id
    CROSS JOIN w
    WHERE g.sublocation_id = ANY(w.ids)
        AND me.monster_id = w.monster_id

    UNION ALL

    SELECT
        g.sublocation_id,
        'item'::text AS s_type,
        get_avl_rank(mis.avl_context, w.pre_airship) AS current_avl,
        mis.is_repeatable_loc AS is_rep
    FROM mv_item_sources mis
    JOIN items i ON mis.master_item_id = i.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE g.sublocation_id = ANY(w.ids)
        AND i.id = w.item_id
        AND (w.methods IS NULL OR mis.source_type = ANY(w.methods))

    UNION ALL

    SELECT
        g.sublocation_id,
        'key-item'::text AS s_type,
        get_avl_rank(mis.avl_context, w.pre_airship) AS current_avl,
        mis.is_repeatable_loc AS is_rep
    FROM mv_item_sources mis
    JOIN key_items ki ON mis.master_item_id = ki.master_item_id
    JOIN mv_geography g ON mis.area_id = g.area_id
    CROSS JOIN w
    WHERE g.sublocation_id = ANY(w.ids)
        AND ki.id = w.key_item_id

    UNION ALL

    SELECT
        g.sublocation_id,
        'auto-ability'::text AS s_type,
        get_avl_rank(aas.avl_context, w.pre_airship) AS current_avl,
        aas.is_repeatable_loc AS is_rep
    FROM mv_auto_ability_sources aas
    JOIN mv_geography g ON aas.area_id = g.area_id
    CROSS JOIN w
    WHERE g.sublocation_id = ANY(w.ids)
        AND aas.auto_ability_id = w.auto_ability_id
),
raw_res_sublocations_rep AS (
    SELECT
        sublocation_id,
        s_type,
        current_avl,
        BOOL_OR(is_rep) AS is_rep
    FROM raw_res_sublocations
    GROUP BY sublocation_id, s_type, current_avl
),
filtered_res_sublocations AS (
    SELECT s.sublocation_id, s.s_type
    FROM raw_res_sublocations_rep s
    CROSS JOIN w
    GROUP BY s.sublocation_id, s.s_type, w.availability, w.is_repeatable
    HAVING filter_avl_rep(
        MIN(s.current_avl),
        BOOL_OR(s.is_rep = w.is_repeatable),
        MIN(s.current_avl) FILTER (WHERE s.is_rep = w.is_repeatable),
        BOOL_OR(s.is_rep) FILTER (WHERE s.current_avl = ANY(w.availability)),
        MIN(s.current_avl) FILTER (WHERE s.is_rep = FALSE),
        w.availability,
        w.is_repeatable
    )
),
content_sublocations AS (
    SELECT sublocation_id, s_type FROM (
        SELECT
            g.sublocation_id,
            a.s_id as source_id, 
            a.source_type AS s_type,
            get_avl_rank_condition(a.avl_self, a.avl_context, w.pre_airship, (a.source_type = 'shop')) AS current_avl
        FROM mv_availabilities a
        JOIN mv_geography g ON a.a_id = g.area_id
        CROSS JOIN w
        WHERE g.sublocation_id = ANY(w.ids)
          AND a.source_type != 'area'

        UNION ALL

        SELECT
            g.sublocation_id,
            a.s_id as source_id,
            a.sub_type AS s_type,
            get_avl_rank(a.avl_context, w.pre_airship) AS current_avl
        FROM mv_availabilities a
        JOIN mv_geography g ON a.a_id = g.area_id
        CROSS JOIN w
        WHERE g.sublocation_id = ANY(w.ids)
          AND a.sub_type = 'boss'
    ) as c
    CROSS JOIN w
    GROUP BY sublocation_id, source_id, s_type, w.availability
    HAVING w.availability IS NULL OR MIN(current_avl) = ANY(w.availability)
),
final_combination AS (
    SELECT sublocation_id, s_type FROM all_sublocations
    UNION ALL
    SELECT sublocation_id, s_type FROM filtered_res_sublocations
    UNION ALL
    SELECT sublocation_id, s_type FROM content_sublocations
)
SELECT sublocation_id
FROM final_combination
CROSS JOIN w
GROUP BY sublocation_id, w.reqs, w.excls
HAVING ARRAY_AGG(s_type) @> w.reqs
   AND (w.excls IS NULL OR NOT ARRAY_AGG(s_type) && w.excls)
ORDER BY sublocation_id
`

type FilterSublocationIDsByAvailabilityParams struct {
	Ids             []int32
	Availability    []int32
	IsRepeatable    sql.NullBool
	PreAirship      bool
	RequiredSources []string
	ExcludedSources []string
	MonsterID       sql.NullInt32
	KeyItemID       sql.NullInt32
	ItemID          sql.NullInt32
	AutoAbilityID   sql.NullInt32
	Methods         []string
}

func (q *Queries) FilterSublocationIDsByAvailability(ctx context.Context, arg FilterSublocationIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterSublocationIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.PreAirship,
		pq.Array(arg.RequiredSources),
		pq.Array(arg.ExcludedSources),
		arg.MonsterID,
		arg.KeyItemID,
		arg.ItemID,
		arg.AutoAbilityID,
		pq.Array(arg.Methods),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var sublocation_id int32
		if err := rows.Scan(&sublocation_id); err != nil {
			return nil, err
		}
		items = append(items, sublocation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterSublocationIDsByAvailabilitySoft = `-- name: FilterSublocationIDsByAvailabilitySoft :many
SELECT DISTINCT id FROM sublocations WHERE get_avl_rank(availability, false) = ANY($1::int[]) ORDER BY id
`

func (q *Queries) FilterSublocationIDsByAvailabilitySoft(ctx context.Context, availability []int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterSublocationIDsByAvailabilitySoft, pq.Array(availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterSubquestIDsByAvailability = `-- name: FilterSubquestIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::int[] AS availability,
        $3::boolean AS is_repeatable,
        $4::boolean AS pre_airship
)
SELECT DISTINCT s.id
FROM subquests s
JOIN quests q ON s.quest_id = q.id
JOIN mv_availabilities a ON q.id = a.s_id AND a.source_type = 'quest'
CROSS JOIN w
WHERE s.id = ANY(w.ids)
  AND (w.availability IS NULL OR get_avl_rank(a.avl_self, w.pre_airship) = ANY(w.availability))
  AND (w.is_repeatable IS NULL OR q.is_repeatable = w.is_repeatable)
ORDER BY s.id
`

type FilterSubquestIDsByAvailabilityParams struct {
	Ids          []int32
	Availability []int32
	IsRepeatable sql.NullBool
	PreAirship   bool
}

func (q *Queries) FilterSubquestIDsByAvailability(ctx context.Context, arg FilterSubquestIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterSubquestIDsByAvailability,
		pq.Array(arg.Ids),
		pq.Array(arg.Availability),
		arg.IsRepeatable,
		arg.PreAirship,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterTreasureIDsByAvailability = `-- name: FilterTreasureIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::int[] AS availability,
        $3::boolean AS pre_airship
)
SELECT DISTINCT a.s_id
FROM mv_availabilities a
CROSS JOIN w
WHERE a.source_type = 'treasure'
  AND a.s_id = ANY(w.ids)
  AND get_avl_rank(a.avl_self, w.pre_airship) = ANY(w.availability)
ORDER BY a.s_id
`

type FilterTreasureIDsByAvailabilityParams struct {
	Ids          []int32
	Availability []int32
	PreAirship   bool
}

func (q *Queries) FilterTreasureIDsByAvailability(ctx context.Context, arg FilterTreasureIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterTreasureIDsByAvailability, pq.Array(arg.Ids), pq.Array(arg.Availability), arg.PreAirship)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var s_id int32
		if err := rows.Scan(&s_id); err != nil {
			return nil, err
		}
		items = append(items, s_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
