// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: availability.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const filterItemIDsByAvailability = `-- name: FilterItemIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::availability_type[] AS availability
)
SELECT DISTINCT i.id
FROM items i
JOIN mv_item_sources mis ON mis.master_item_id = i.master_item_id
JOIN mv_availabilities a ON mis.source_id = a.s_id AND mis.source_type = a.source_type
CROSS JOIN w
WHERE i.id = ANY(w.ids)
  AND CASE
        WHEN w.avl_type = 'self' THEN a.avl_self
        WHEN w.avl_type = 'context' THEN a.avl_context
        WHEN w.avl_type = 'area' THEN a.avl_area
      END = ANY(w.availability)
ORDER BY i.id
`

type FilterItemIDsByAvailabilityParams struct {
	Ids          []int32
	AvlType      string
	Availability []AvailabilityType
}

// might use a source type array, if the sources need to be specified
// needs to change (see monster query)
func (q *Queries) FilterItemIDsByAvailability(ctx context.Context, arg FilterItemIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterItemIDsByAvailability, pq.Array(arg.Ids), arg.AvlType, pq.Array(arg.Availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterMonsterFormationIDsByAvailability = `-- name: FilterMonsterFormationIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::availability_type[] AS availability,
        $4::int AS loc_context_id,
        $5::text AS loc_context_type
),
available_formations AS (
    SELECT 
        a.s_id,
        CASE 
            WHEN w.avl_type = 'self' THEN a.avl_self
            WHEN w.avl_type = 'context' THEN a.avl_context
            WHEN w.avl_type = 'area' THEN a.avl_area
        END as current_avl
    FROM mv_availabilities a
    JOIN mv_geography g ON a.a_id = g.area_id
    CROSS JOIN w
    WHERE a.source_type = 'monster-formation'
      AND a.s_id = ANY(w.ids)
      AND (w.loc_context_id IS NULL OR CASE
           WHEN w.loc_context_type = 'location' THEN g.location_id
           WHEN w.loc_context_type = 'sublocation' THEN g.sublocation_id
           WHEN w.loc_context_type = 'area' THEN g.area_id
          END = w.loc_context_id)
)
SELECT s_id
FROM available_formations
GROUP BY s_id
HAVING ARRAY[MIN(current_avl)] && (SELECT availability FROM w)
`

type FilterMonsterFormationIDsByAvailabilityParams struct {
	Ids            []int32
	AvlType        string
	Availability   []AvailabilityType
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
}

func (q *Queries) FilterMonsterFormationIDsByAvailability(ctx context.Context, arg FilterMonsterFormationIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterMonsterFormationIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		arg.LocContextID,
		arg.LocContextType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var s_id int32
		if err := rows.Scan(&s_id); err != nil {
			return nil, err
		}
		items = append(items, s_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterMonsterIDsByAvailability = `-- name: FilterMonsterIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::availability_type[] AS availability,
        $4::int AS loc_context_id,
        $5::text AS loc_context_type
),
available_monsters AS (
    SELECT 
        a.s_id,
        CASE 
            WHEN w.avl_type = 'self' THEN a.avl_self
            WHEN w.avl_type = 'context' THEN a.avl_context
            WHEN w.avl_type = 'area' THEN a.avl_area
        END as current_avl
    FROM mv_availabilities a
    JOIN mv_geography g ON a.a_id = g.area_id
    CROSS JOIN w
    WHERE a.source_type = 'monster'
      AND a.s_id = ANY(w.ids)
      AND (w.loc_context_id IS NULL OR CASE
           WHEN w.loc_context_type = 'location' THEN g.location_id
           WHEN w.loc_context_type = 'sublocation' THEN g.sublocation_id
           WHEN w.loc_context_type = 'area' THEN g.area_id
          END = w.loc_context_id)
)
SELECT s_id
FROM available_monsters
GROUP BY s_id
HAVING ARRAY[MIN(current_avl)] && (SELECT availability FROM w)
`

type FilterMonsterIDsByAvailabilityParams struct {
	Ids            []int32
	AvlType        string
	Availability   []AvailabilityType
	LocContextID   sql.NullInt32
	LocContextType sql.NullString
}

func (q *Queries) FilterMonsterIDsByAvailability(ctx context.Context, arg FilterMonsterIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterMonsterIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		arg.LocContextID,
		arg.LocContextType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var s_id int32
		if err := rows.Scan(&s_id); err != nil {
			return nil, err
		}
		items = append(items, s_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterShopIDsByAvailability = `-- name: FilterShopIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::text AS avl_type,
        $3::availability_type[] AS availability,
        $4::text[] AS sub_types
)
SELECT s_id
FROM (
    SELECT 
        a.s_id,
        CASE 
            WHEN w.avl_type = 'self' THEN a.avl_self
            WHEN w.avl_type = 'context' THEN a.avl_context
            WHEN w.avl_type = 'area' THEN a.avl_area
        END as current_avl
    FROM mv_availabilities a
    CROSS JOIN w
    WHERE a.source_type = 'shop'
      AND a.s_id = ANY(w.ids)
      AND (w.sub_types IS NULL OR a.sub_type = ANY(w.sub_types))
) available_shops
GROUP BY s_id
HAVING ARRAY[MIN(current_avl)] && (SELECT availability FROM w)
`

type FilterShopIDsByAvailabilityParams struct {
	Ids          []int32
	AvlType      string
	Availability []AvailabilityType
	SubTypes     []string
}

func (q *Queries) FilterShopIDsByAvailability(ctx context.Context, arg FilterShopIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterShopIDsByAvailability,
		pq.Array(arg.Ids),
		arg.AvlType,
		pq.Array(arg.Availability),
		pq.Array(arg.SubTypes),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var s_id int32
		if err := rows.Scan(&s_id); err != nil {
			return nil, err
		}
		items = append(items, s_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterTreasureIDsByAvailability = `-- name: FilterTreasureIDsByAvailability :many
WITH w AS (
    SELECT
        $1::int[] AS ids,
        $2::availability_type[] AS availability
)
SELECT DISTINCT a.s_id
FROM mv_availabilities a
CROSS JOIN w
WHERE a.source_type = 'treasure'
  AND a.s_id = ANY(w.ids)
  AND ARRAY[a.avl_self] &&  w.availability
ORDER BY a.s_id
`

type FilterTreasureIDsByAvailabilityParams struct {
	Ids          []int32
	Availability []AvailabilityType
}

func (q *Queries) FilterTreasureIDsByAvailability(ctx context.Context, arg FilterTreasureIDsByAvailabilityParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, filterTreasureIDsByAvailability, pq.Array(arg.Ids), pq.Array(arg.Availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var s_id int32
		if err := rows.Scan(&s_id); err != nil {
			return nil, err
		}
		items = append(items, s_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
