// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: characters_get.sql

package database

import (
	"context"
)

const getAeonAeonCommandIDs = `-- name: GetAeonAeonCommandIDs :many
SELECT DISTINCT ac.id
FROM aeon_commands ac
JOIN j_aeon_commands_possible_abilities j1 ON j1.aeon_command_id = ac.id
JOIN character_classes cc ON j1.character_class_id = cc.id
JOIN j_character_class_player_units j2 ON j2.class_id = cc.id
JOIN player_units pu ON j2.unit_id = pu.id
JOIN aeons a ON a.unit_id = pu.id
WHERE a.id = $1
ORDER BY ac.id
`

func (q *Queries) GetAeonAeonCommandIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAeonAeonCommandIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAeonCelestialWeaponID = `-- name: GetAeonCelestialWeaponID :one
SELECT cw.id
FROM celestial_weapons cw
JOIN aeons a ON cw.aeon_id = a.id
WHERE a.id = $1
`

func (q *Queries) GetAeonCelestialWeaponID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getAeonCelestialWeaponID, id)
	err := row.Scan(&id)
	return id, err
}

const getAeonCharClassIDs = `-- name: GetAeonCharClassIDs :many
SELECT cc.id
FROM character_classes cc
JOIN j_character_class_player_units j ON j.class_id = cc.id
JOIN player_units pu ON j.unit_id = pu.id
JOIN aeons a ON a.unit_id = pu.id
WHERE a.id = $1
ORDER BY cc.id
`

func (q *Queries) GetAeonCharClassIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAeonCharClassIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAeonDefaultAbilityIDs = `-- name: GetAeonDefaultAbilityIDs :many
SELECT pa.id
FROM player_abilities pa
JOIN abilities a ON pa.ability_id = a.id
JOIN default_abilities da ON da.ability_id = a.id
JOIN character_classes cc ON da.class_id = cc.id
JOIN j_character_class_player_units j ON j.class_id = cc.id
JOIN player_units pu ON j.unit_id = pu.id
JOIN aeons ae ON ae.unit_id = pu.id
WHERE a.type = 'player-ability' AND ae.id = $1
ORDER BY pa.id
`

func (q *Queries) GetAeonDefaultAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAeonDefaultAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAeonIDs = `-- name: GetAeonIDs :many
SELECT id FROM aeons ORDER BY id
`

func (q *Queries) GetAeonIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAeonIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAeonIDsOptional = `-- name: GetAeonIDsOptional :many
SELECT id FROM aeons WHERE is_optional = $1 ORDER BY id
`

func (q *Queries) GetAeonIDsOptional(ctx context.Context, isOptional bool) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAeonIDsOptional, isOptional)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAeonOverdriveIDs = `-- name: GetAeonOverdriveIDs :many
SELECT o.id
FROM overdrives o
JOIN character_classes cc ON o.character_class_id = cc.id
JOIN j_character_class_player_units j ON j.class_id = cc.id
JOIN player_units pu ON j.unit_id = pu.id
JOIN aeons a ON a.unit_id = pu.id
WHERE a.id = $1
ORDER BY o.id
`

func (q *Queries) GetAeonOverdriveIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAeonOverdriveIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterCelestialWeaponID = `-- name: GetCharacterCelestialWeaponID :one
SELECT cw.id
FROM celestial_weapons cw
JOIN characters c ON cw.character_id = c.id
WHERE c.id = $1
`

func (q *Queries) GetCharacterCelestialWeaponID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCharacterCelestialWeaponID, id)
	err := row.Scan(&id)
	return id, err
}

const getCharacterCharClassIDs = `-- name: GetCharacterCharClassIDs :many
SELECT cc.id
FROM character_classes cc
JOIN j_character_class_player_units j ON j.class_id = cc.id
JOIN player_units pu ON j.unit_id = pu.id
JOIN characters c ON c.unit_id = pu.id
WHERE c.id = $1
ORDER BY cc.id
`

func (q *Queries) GetCharacterCharClassIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterCharClassIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterClassDefaultAbilityIDs = `-- name: GetCharacterClassDefaultAbilityIDs :many
SELECT a.id
FROM abilities a
JOIN default_abilities da ON da.ability_id = a.id
JOIN character_classes cc ON da.class_id = cc.id
WHERE cc.id = $1
ORDER BY a.id
`

func (q *Queries) GetCharacterClassDefaultAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterClassDefaultAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterClassDefaultOverdriveIDs = `-- name: GetCharacterClassDefaultOverdriveIDs :many
SELECT o.id
FROM overdrives o
JOIN character_classes cc ON o.character_class_id = cc.id
WHERE cc.id = $1 AND o.unlock_condition IS NULL
ORDER BY o.id
`

func (q *Queries) GetCharacterClassDefaultOverdriveIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterClassDefaultOverdriveIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterClassLearnableAbilityIDs = `-- name: GetCharacterClassLearnableAbilityIDs :many
SELECT a.id
FROM abilities a
LEFT JOIN player_abilities pa ON pa.ability_id = a.id
LEFT JOIN j_player_abilities_learned_by j1 ON j1.player_ability_id = pa.id
LEFT JOIN other_abilities oa ON oa.ability_id = a.id
LEFT JOIN j_other_abilities_learned_by j2 ON j2.other_ability_id = oa.id
LEFT JOIN character_classes cc ON j1.character_class_id = cc.id OR j2.character_class_id = cc.id
WHERE cc.id = $1
ORDER BY a.id
`

func (q *Queries) GetCharacterClassLearnableAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterClassLearnableAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterClassLearnableOverdriveIDs = `-- name: GetCharacterClassLearnableOverdriveIDs :many
SELECT o.id
FROM overdrives o
JOIN character_classes cc ON o.character_class_id = cc.id
WHERE cc.id = $1 AND o.unlock_condition IS NOT NULL
ORDER BY o.id
`

func (q *Queries) GetCharacterClassLearnableOverdriveIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterClassLearnableOverdriveIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterClassSubmenuIDs = `-- name: GetCharacterClassSubmenuIDs :many
SELECT s.id
FROM submenus s
JOIN j_submenus_users j ON j.submenu_id = s.id
JOIN character_classes cc ON j.character_class_id = cc.id
WHERE cc.id = $1
ORDER BY s.id
`

func (q *Queries) GetCharacterClassSubmenuIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterClassSubmenuIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterClassUnitIDs = `-- name: GetCharacterClassUnitIDs :many
SELECT pu.id
FROM player_units pu
JOIN j_character_class_player_units j ON j.unit_id = pu.id
JOIN character_classes cc ON j.class_id = cc.id
WHERE cc.id = $1
ORDER BY pu.id
`

func (q *Queries) GetCharacterClassUnitIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterClassUnitIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterClassesIDs = `-- name: GetCharacterClassesIDs :many
SELECT id FROM character_classes ORDER BY id
`

func (q *Queries) GetCharacterClassesIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterClassesIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterClassesIDsByCategory = `-- name: GetCharacterClassesIDsByCategory :many
SELECT id FROM character_classes WHERE category = $1 ORDER BY id
`

func (q *Queries) GetCharacterClassesIDsByCategory(ctx context.Context, category CharacterClassCategory) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterClassesIDsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterDefaultAbilityIDs = `-- name: GetCharacterDefaultAbilityIDs :many
SELECT pa.id
FROM player_abilities pa
JOIN abilities a ON pa.ability_id = a.id
JOIN default_abilities da ON da.ability_id = a.id
JOIN character_classes cc ON da.class_id = cc.id
JOIN j_character_class_player_units j ON j.class_id = cc.id
JOIN player_units pu ON j.unit_id = pu.id
JOIN characters c ON c.unit_id = pu.id
WHERE a.type = 'player-ability' AND c.id = $1
ORDER BY pa.id
`

func (q *Queries) GetCharacterDefaultAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterDefaultAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterEgAbilityIDs = `-- name: GetCharacterEgAbilityIDs :many
SELECT pa.id
FROM player_abilities pa
JOIN characters c ON pa.expert_grid_char_id = c.id
WHERE c.id = $1
ORDER BY pa.id
`

func (q *Queries) GetCharacterEgAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterEgAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterIDs = `-- name: GetCharacterIDs :many
SELECT id FROM characters ORDER BY id
`

func (q *Queries) GetCharacterIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterIDsCanFightUnderwater = `-- name: GetCharacterIDsCanFightUnderwater :many
SELECT id FROM characters WHERE can_fight_underwater = $1 ORDER BY id
`

func (q *Queries) GetCharacterIDsCanFightUnderwater(ctx context.Context, canFightUnderwater bool) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterIDsCanFightUnderwater, canFightUnderwater)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterIDsStoryOnly = `-- name: GetCharacterIDsStoryOnly :many
SELECT id FROM characters WHERE story_only = $1 ORDER BY id
`

func (q *Queries) GetCharacterIDsStoryOnly(ctx context.Context, storyOnly bool) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterIDsStoryOnly, storyOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacterOverdriveCommandID = `-- name: GetCharacterOverdriveCommandID :one
SELECT oc.id
FROM overdrive_commands oc
JOIN character_classes cc ON oc.character_class_id = cc.id
JOIN j_character_class_player_units j ON j.class_id = cc.id
JOIN player_units pu ON j.unit_id = pu.id
JOIN characters c ON c.unit_id = pu.id
WHERE c.id = $1
`

func (q *Queries) GetCharacterOverdriveCommandID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCharacterOverdriveCommandID, id)
	err := row.Scan(&id)
	return id, err
}

const getCharacterSgAbilityIDs = `-- name: GetCharacterSgAbilityIDs :many
SELECT pa.id
FROM player_abilities pa
JOIN characters c ON pa.standard_grid_char_id = c.id
WHERE c.id = $1
ORDER BY pa.id
`

func (q *Queries) GetCharacterSgAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterSgAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
