// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_new_commands_menus.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createAeonCommandBulk = `-- name: CreateAeonCommandBulk :many
INSERT INTO aeon_commands (data_hash, name, description, effect, cursor)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::text[]),
    unnest($5::null_target_type[]),
    unnest($6::null_int[]),
    unnest($7::null_int[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id, data_hash
`

type CreateAeonCommandBulkParams struct {
	DataHash    []string
	Name        []string
	Description []string
	Effect      []string
	Cursor      []NullTargetType
	TopmenuID   []sql.NullInt32
	SubmenuID   []sql.NullInt32
}

type CreateAeonCommandBulkRow struct {
	ID       int32
	DataHash string
}

func (q *Queries) CreateAeonCommandBulk(ctx context.Context, arg CreateAeonCommandBulkParams) ([]CreateAeonCommandBulkRow, error) {
	rows, err := q.db.QueryContext(ctx, createAeonCommandBulk,
		pq.Array(arg.DataHash),
		pq.Array(arg.Name),
		pq.Array(arg.Description),
		pq.Array(arg.Effect),
		pq.Array(arg.Cursor),
		pq.Array(arg.TopmenuID),
		pq.Array(arg.SubmenuID),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateAeonCommandBulkRow
	for rows.Next() {
		var i CreateAeonCommandBulkRow
		if err := rows.Scan(&i.ID, &i.DataHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAeonCommandsPossibleAbilitiesJunctionBulk = `-- name: CreateAeonCommandsPossibleAbilitiesJunctionBulk :exec
INSERT INTO j_aeon_commands_possible_abilities (data_hash, aeon_command_id, character_class_id, ability_id)
SELECT
    unnest($1::text[]),
    unnest($2::int[]),
    unnest($3::int[]),
    unnest($4::int[])
ON CONFLICT(data_hash) DO NOTHING
`

type CreateAeonCommandsPossibleAbilitiesJunctionBulkParams struct {
	DataHash         []string
	AeonCommandID    []int32
	CharacterClassID []int32
	AbilityID        []int32
}

func (q *Queries) CreateAeonCommandsPossibleAbilitiesJunctionBulk(ctx context.Context, arg CreateAeonCommandsPossibleAbilitiesJunctionBulkParams) error {
	_, err := q.db.ExecContext(ctx, createAeonCommandsPossibleAbilitiesJunctionBulk,
		pq.Array(arg.DataHash),
		pq.Array(arg.AeonCommandID),
		pq.Array(arg.CharacterClassID),
		pq.Array(arg.AbilityID),
	)
	return err
}

const createOverdriveCommandBulk = `-- name: CreateOverdriveCommandBulk :many
INSERT INTO overdrive_commands (data_hash, name, description, rank)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::int[]),
    unnest($5::null_int[]),
    unnest($6::null_int[]),
    unnest($7::null_int[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id, data_hash
`

type CreateOverdriveCommandBulkParams struct {
	DataHash         []string
	Name             []string
	Description      []string
	Rank             []int32
	CharacterClassID []sql.NullInt32
	TopmenuID        []sql.NullInt32
	SubmenuID        []sql.NullInt32
}

type CreateOverdriveCommandBulkRow struct {
	ID       int32
	DataHash string
}

func (q *Queries) CreateOverdriveCommandBulk(ctx context.Context, arg CreateOverdriveCommandBulkParams) ([]CreateOverdriveCommandBulkRow, error) {
	rows, err := q.db.QueryContext(ctx, createOverdriveCommandBulk,
		pq.Array(arg.DataHash),
		pq.Array(arg.Name),
		pq.Array(arg.Description),
		pq.Array(arg.Rank),
		pq.Array(arg.CharacterClassID),
		pq.Array(arg.TopmenuID),
		pq.Array(arg.SubmenuID),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateOverdriveCommandBulkRow
	for rows.Next() {
		var i CreateOverdriveCommandBulkRow
		if err := rows.Scan(&i.ID, &i.DataHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSubmenuBulk = `-- name: CreateSubmenuBulk :many
INSERT INTO submenus (data_hash, name, topmenu_id, description, effect)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::null_int[]),
    unnest($4::null_string[]),
    unnest($5::text[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id, data_hash
`

type CreateSubmenuBulkParams struct {
	DataHash    []string
	Name        []string
	TopmenuID   []sql.NullInt32
	Description []sql.NullString
	Effect      []string
}

type CreateSubmenuBulkRow struct {
	ID       int32
	DataHash string
}

func (q *Queries) CreateSubmenuBulk(ctx context.Context, arg CreateSubmenuBulkParams) ([]CreateSubmenuBulkRow, error) {
	rows, err := q.db.QueryContext(ctx, createSubmenuBulk,
		pq.Array(arg.DataHash),
		pq.Array(arg.Name),
		pq.Array(arg.TopmenuID),
		pq.Array(arg.Description),
		pq.Array(arg.Effect),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateSubmenuBulkRow
	for rows.Next() {
		var i CreateSubmenuBulkRow
		if err := rows.Scan(&i.ID, &i.DataHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSubmenusUsersJunctionBulk = `-- name: CreateSubmenusUsersJunctionBulk :exec
INSERT INTO j_submenus_users (data_hash, submenu_id, character_class_id)
SELECT
    unnest($1::text[]),
    unnest($2::int[]),
    unnest($3::int[])
ON CONFLICT(data_hash) DO NOTHING
`

type CreateSubmenusUsersJunctionBulkParams struct {
	DataHash         []string
	SubmenuID        []int32
	CharacterClassID []int32
}

func (q *Queries) CreateSubmenusUsersJunctionBulk(ctx context.Context, arg CreateSubmenusUsersJunctionBulkParams) error {
	_, err := q.db.ExecContext(ctx, createSubmenusUsersJunctionBulk, pq.Array(arg.DataHash), pq.Array(arg.SubmenuID), pq.Array(arg.CharacterClassID))
	return err
}

const createTopmenuBulk = `-- name: CreateTopmenuBulk :many
INSERT INTO topmenus (data_hash, name)
SELECT
    unnest($1::text[]),
    unnest($2::text[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id, data_hash
`

type CreateTopmenuBulkParams struct {
	DataHash []string
	Name     []string
}

type CreateTopmenuBulkRow struct {
	ID       int32
	DataHash string
}

func (q *Queries) CreateTopmenuBulk(ctx context.Context, arg CreateTopmenuBulkParams) ([]CreateTopmenuBulkRow, error) {
	rows, err := q.db.QueryContext(ctx, createTopmenuBulk, pq.Array(arg.DataHash), pq.Array(arg.Name))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateTopmenuBulkRow
	for rows.Next() {
		var i CreateTopmenuBulkRow
		if err := rows.Scan(&i.ID, &i.DataHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
