// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_new_battle_mechanics.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createAgilitySubtierBulk = `-- name: CreateAgilitySubtierBulk :many
INSERT INTO agility_subtiers (data_hash, agility_tier_id, subtier_min_agility, subtier_max_agility, character_min_icv)
SELECT
    unnest($1::text[]),
    unnest($2::int[]),
    unnest($3::int[]),
    unnest($4::int[]),
    unnest($5::null_int[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreateAgilitySubtierBulkParams struct {
	DataHash        []string
	AgilityTierID   []int32
	MinAgility      []int32
	MaxAgility      []int32
	CharacterMinIcv []sql.NullInt32
}

func (q *Queries) CreateAgilitySubtierBulk(ctx context.Context, arg CreateAgilitySubtierBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createAgilitySubtierBulk,
		pq.Array(arg.DataHash),
		pq.Array(arg.AgilityTierID),
		pq.Array(arg.MinAgility),
		pq.Array(arg.MaxAgility),
		pq.Array(arg.CharacterMinIcv),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAgilityTierBulk = `-- name: CreateAgilityTierBulk :many
INSERT INTO agility_tiers (data_hash, min_agility, max_agility, tick_speed, monster_min_icv, monster_max_icv, character_max_icv)
SELECT
    unnest($1::text[]),
    unnest($2::int[]),
    unnest($3::int[]),
    unnest($4::int[]),
    unnest($5::null_int[]),
    unnest($6::null_int[]),
    unnest($7::null_int[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreateAgilityTierBulkParams struct {
	DataHash        []string
	MinAgility      []int32
	MaxAgility      []int32
	TickSpeed       []int32
	MonsterMinIcv   []sql.NullInt32
	MonsterMaxIcv   []sql.NullInt32
	CharacterMaxIcv []sql.NullInt32
}

func (q *Queries) CreateAgilityTierBulk(ctx context.Context, arg CreateAgilityTierBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createAgilityTierBulk,
		pq.Array(arg.DataHash),
		pq.Array(arg.MinAgility),
		pq.Array(arg.MaxAgility),
		pq.Array(arg.TickSpeed),
		pq.Array(arg.MonsterMinIcv),
		pq.Array(arg.MonsterMaxIcv),
		pq.Array(arg.CharacterMaxIcv),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBaseStatBulk = `-- name: CreateBaseStatBulk :many
INSERT INTO base_stats (data_hash, stat_id, value)
SELECT
    unnest($1::text[]),
    unnest($2::int[]),
    unnest($3::int[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreateBaseStatBulkParams struct {
	DataHash []string
	StatID   []int32
	Value    []int32
}

func (q *Queries) CreateBaseStatBulk(ctx context.Context, arg CreateBaseStatBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createBaseStatBulk, pq.Array(arg.DataHash), pq.Array(arg.StatID), pq.Array(arg.Value))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createElementBulk = `-- name: CreateElementBulk :many
INSERT INTO elements (data_hash, name)
SELECT
    unnest($1::text[]),
    unnest($2::text[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreateElementBulkParams struct {
	DataHash []string
	Name     []string
}

func (q *Queries) CreateElementBulk(ctx context.Context, arg CreateElementBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createElementBulk, pq.Array(arg.DataHash), pq.Array(arg.Name))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createElementalResistBulk = `-- name: CreateElementalResistBulk :many
INSERT INTO elemental_resists (data_hash, element_id, affinity)
SELECT
    unnest($1::text[]),
    unnest($2::int[]),
    unnest($3::elemental_affinity[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreateElementalResistBulkParams struct {
	DataHash  []string
	ElementID []int32
	Affinity  []ElementalAffinity
}

func (q *Queries) CreateElementalResistBulk(ctx context.Context, arg CreateElementalResistBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createElementalResistBulk, pq.Array(arg.DataHash), pq.Array(arg.ElementID), pq.Array(arg.Affinity))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createModifierBulk = `-- name: CreateModifierBulk :many
INSERT INTO modifiers (data_hash, name, effect, category, default_value)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::modifier_category[]),
    unnest($5::null_float[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreateModifierBulkParams struct {
	DataHash     []string
	Name         []string
	Effect       []string
	Category     []ModifierCategory
	DefaultValue []sql.NullFloat64
}

func (q *Queries) CreateModifierBulk(ctx context.Context, arg CreateModifierBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createModifierBulk,
		pq.Array(arg.DataHash),
		pq.Array(arg.Name),
		pq.Array(arg.Effect),
		pq.Array(arg.Category),
		pq.Array(arg.DefaultValue),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createODModeActionBulk = `-- name: CreateODModeActionBulk :many
INSERT INTO od_mode_actions (data_hash, user_id, amount)
SELECT
    unnest($1::text[]),
    unnest($2::int[]),
    unnest($3::int[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreateODModeActionBulkParams struct {
	DataHash []string
	UserID   []int32
	Amount   []int32
}

func (q *Queries) CreateODModeActionBulk(ctx context.Context, arg CreateODModeActionBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createODModeActionBulk, pq.Array(arg.DataHash), pq.Array(arg.UserID), pq.Array(arg.Amount))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOverdriveModeBulk = `-- name: CreateOverdriveModeBulk :many
INSERT INTO overdrive_modes (data_hash, name, description, effect, type, fill_rate)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::text[]),
    unnest($5::overdrive_mode_type[]),
    unnest($6::null_float[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreateOverdriveModeBulkParams struct {
	DataHash    []string
	Name        []string
	Description []string
	Effect      []string
	Type        []OverdriveModeType
	FillRate    []sql.NullFloat64
}

func (q *Queries) CreateOverdriveModeBulk(ctx context.Context, arg CreateOverdriveModeBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createOverdriveModeBulk,
		pq.Array(arg.DataHash),
		pq.Array(arg.Name),
		pq.Array(arg.Description),
		pq.Array(arg.Effect),
		pq.Array(arg.Type),
		pq.Array(arg.FillRate),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPropertyBulk = `-- name: CreatePropertyBulk :many
INSERT INTO properties (data_hash, name, effect, nullify_armored)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::null_nullify_armored[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreatePropertyBulkParams struct {
	DataHash       []string
	Name           []string
	Effect         []string
	NullifyArmored []NullNullifyArmored
}

func (q *Queries) CreatePropertyBulk(ctx context.Context, arg CreatePropertyBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createPropertyBulk,
		pq.Array(arg.DataHash),
		pq.Array(arg.Name),
		pq.Array(arg.Effect),
		pq.Array(arg.NullifyArmored),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createStatBulk = `-- name: CreateStatBulk :many
INSERT INTO stats (data_hash, name, effect, min_val, max_val, max_val_2, sphere_id)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::int[]),
    unnest($5::int[]),
    unnest($6::null_int[]),
    unnest($7::null_int[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreateStatBulkParams struct {
	DataHash []string
	Name     []string
	Effect   []string
	MinVal   []int32
	MaxVal   []int32
	MaxVal2  []sql.NullInt32
	SphereID []sql.NullInt32
}

func (q *Queries) CreateStatBulk(ctx context.Context, arg CreateStatBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createStatBulk,
		pq.Array(arg.DataHash),
		pq.Array(arg.Name),
		pq.Array(arg.Effect),
		pq.Array(arg.MinVal),
		pq.Array(arg.MaxVal),
		pq.Array(arg.MaxVal2),
		pq.Array(arg.SphereID),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createStatusConditionBulk = `-- name: CreateStatusConditionBulk :many
INSERT INTO status_conditions (data_hash, name, category, is_permanent, effect, visualization, nullify_armored)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::status_condition_category[]),
    unnest($4::boolean[]),
    unnest($5::text[]),
    unnest($6::null_string[]),
    unnest($7::null_nullify_armored[]),
    unnest($8::null_int[]),
    unnest($9::null_int[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreateStatusConditionBulkParams struct {
	DataHash          []string
	Name              []string
	Category          []StatusConditionCategory
	IsPermanent       []bool
	Effect            []string
	Visualization     []sql.NullString
	NullifyArmored    []NullNullifyArmored
	AddedElemResistID []sql.NullInt32
	InflictedDelayID  []sql.NullInt32
}

func (q *Queries) CreateStatusConditionBulk(ctx context.Context, arg CreateStatusConditionBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createStatusConditionBulk,
		pq.Array(arg.DataHash),
		pq.Array(arg.Name),
		pq.Array(arg.Category),
		pq.Array(arg.IsPermanent),
		pq.Array(arg.Effect),
		pq.Array(arg.Visualization),
		pq.Array(arg.NullifyArmored),
		pq.Array(arg.AddedElemResistID),
		pq.Array(arg.InflictedDelayID),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createStatusResistBulk = `-- name: CreateStatusResistBulk :many
INSERT INTO status_resists (data_hash, status_condition_id, resistance)
SELECT
    unnest($1::text[]),
    unnest($2::int[]),
    unnest($3::int[])
ON CONFLICT(data_hash) DO UPDATE SET data_hash = EXCLUDED.data_hash
RETURNING id
`

type CreateStatusResistBulkParams struct {
	DataHash          []string
	StatusConditionID []int32
	Resistance        []int32
}

func (q *Queries) CreateStatusResistBulk(ctx context.Context, arg CreateStatusResistBulkParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, createStatusResistBulk, pq.Array(arg.DataHash), pq.Array(arg.StatusConditionID), pq.Array(arg.Resistance))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateElementBulk = `-- name: UpdateElementBulk :exec
UPDATE elements AS e
SET opposite_element_id = u.opposite_id
FROM (
    SELECT 
        unnest($1::int[]) AS id,
        unnest($2::null_int[])
) AS u
WHERE e.id = u.id
`

type UpdateElementBulkParams struct {
	ID         []int32
	OppositeID []sql.NullInt32
}

func (q *Queries) UpdateElementBulk(ctx context.Context, arg UpdateElementBulkParams) error {
	_, err := q.db.ExecContext(ctx, updateElementBulk, pq.Array(arg.ID), pq.Array(arg.OppositeID))
	return err
}
