// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_equipment.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const getAutoAbilityEquipmentTableIDs = `-- name: GetAutoAbilityEquipmentTableIDs :many
SELECT j.equipment_table_id
FROM j_equipment_tables_required_auto_abilities j
WHERE j.auto_ability_id = $1

UNION

SELECT ap.equipment_table_id
FROM ability_pools ap
JOIN j_ability_pools_auto_abilities j ON j.ability_pool_id = ap.id
WHERE j.auto_ability_id = $1
ORDER BY equipment_table_id
`

func (q *Queries) GetAutoAbilityEquipmentTableIDs(ctx context.Context, autoAbilityID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAbilityEquipmentTableIDs, autoAbilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var equipment_table_id int32
		if err := rows.Scan(&equipment_table_id); err != nil {
			return nil, err
		}
		items = append(items, equipment_table_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoAbilityIDs = `-- name: GetAutoAbilityIDs :many
SELECT id FROM auto_abilities ORDER BY id
`

func (q *Queries) GetAutoAbilityIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAbilityIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoAbilityIDsByCategory = `-- name: GetAutoAbilityIDsByCategory :many
SELECT id FROM auto_abilities WHERE category = ANY($1::auto_ability_category[]) ORDER BY id
`

func (q *Queries) GetAutoAbilityIDsByCategory(ctx context.Context, autoAbilityCategory []AutoAbilityCategory) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAbilityIDsByCategory, pq.Array(autoAbilityCategory))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoAbilityIDsByEquipType = `-- name: GetAutoAbilityIDsByEquipType :many
SELECT id FROM auto_abilities WHERE type = $1 ORDER BY id
`

func (q *Queries) GetAutoAbilityIDsByEquipType(ctx context.Context, type_ EquipType) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAbilityIDsByEquipType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoAbilityIDsByMonster = `-- name: GetAutoAbilityIDsByMonster :many
SELECT DISTINCT ed.auto_ability_id
FROM equipment_drops ed
JOIN j_monster_equipment_abilities j ON j.equipment_drop_id = ed.id
JOIN monster_equipment me ON j.monster_equipment_id = me.id
WHERE me.monster_id = $1
ORDER BY ed.auto_ability_id
`

func (q *Queries) GetAutoAbilityIDsByMonster(ctx context.Context, monsterID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAbilityIDsByMonster, monsterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var auto_ability_id int32
		if err := rows.Scan(&auto_ability_id); err != nil {
			return nil, err
		}
		items = append(items, auto_ability_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoAbilityIDsByMonsterItems = `-- name: GetAutoAbilityIDsByMonsterItems :many
WITH monster_drops AS (
    SELECT ia.master_item_id
    FROM monster_items mi
    JOIN item_amounts ia ON ia.id IN (
        mi.steal_common_id,
        mi.steal_rare_id,
        mi.drop_common_id,
        mi.drop_rare_id,
        mi.secondary_drop_common_id,
        mi.secondary_drop_rare_id,
        mi.bribe_id
    )
    WHERE mi.monster_id = $1

    UNION ALL

    SELECT ia.master_item_id
    FROM monster_items mi
    JOIN j_monster_items_other_items jmio ON jmio.monster_items_id = mi.id
    JOIN possible_items pi ON pi.id = jmio.possible_item_id
    JOIN item_amounts ia ON pi.item_amount_id = ia.id
    WHERE mi.monster_id = $1
)
SELECT DISTINCT aa.id
FROM auto_abilities aa
JOIN item_amounts ia_req ON aa.required_item_amount_id = ia_req.id
JOIN monster_drops md ON ia_req.master_item_id = md.master_item_id
ORDER BY aa.id
`

func (q *Queries) GetAutoAbilityIDsByMonsterItems(ctx context.Context, monsterID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAbilityIDsByMonsterItems, monsterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoAbilityItemMonsterIDs = `-- name: GetAutoAbilityItemMonsterIDs :many
WITH target_items AS (
    SELECT mit.id AS master_item_id
    FROM auto_abilities aa
    JOIN item_amounts ia_req ON aa.required_item_amount_id = ia_req.id
    JOIN master_items mit ON ia_req.master_item_id = mit.id
    WHERE aa.id = $3
),
monster_sources AS (
    SELECT mi.monster_id, ia.master_item_id
    FROM monster_items mi
    JOIN item_amounts ia ON ia.id IN (
        mi.steal_common_id,
        mi.steal_rare_id,
        mi.drop_common_id,
        mi.drop_rare_id,
        mi.secondary_drop_common_id,
        mi.secondary_drop_rare_id,
        mi.bribe_id
    )

    UNION ALL

    SELECT mi.monster_id, ia.master_item_id
    FROM monster_items mi
    JOIN j_monster_items_other_items jmio ON jmio.monster_items_id = mi.id
    JOIN possible_items pi ON pi.id = jmio.possible_item_id
    JOIN item_amounts ia ON pi.item_amount_id = ia.id
)
SELECT DISTINCT m.id
FROM monsters m
JOIN monster_sources ms ON m.id = ms.monster_id
JOIN target_items ti ON ms.master_item_id = ti.master_item_id
WHERE ($1::BOOLEAN IS NULL OR m.is_repeatable = $1::BOOLEAN)
  AND ($2::availability_type[] IS NULL OR m.availability = ANY($2::availability_type[]))
ORDER BY m.id
`

type GetAutoAbilityItemMonsterIDsParams struct {
	Repeatable    sql.NullBool
	Availability  []AvailabilityType
	AutoAbilityID int32
}

func (q *Queries) GetAutoAbilityItemMonsterIDs(ctx context.Context, arg GetAutoAbilityItemMonsterIDsParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAbilityItemMonsterIDs, arg.Repeatable, pq.Array(arg.Availability), arg.AutoAbilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoAbilityMonsterIDs = `-- name: GetAutoAbilityMonsterIDs :many
WITH filtered_monsters AS (
    SELECT id FROM monsters
    WHERE (
        $2::BOOLEAN IS NULL
        OR
        is_repeatable = $2::BOOLEAN
    )
    AND (
        $3::availability_type[] IS NULL
        OR
        availability = ANY($3::availability_type[])
    )
)
SELECT DISTINCT fm.id
FROM filtered_monsters fm
JOIN monster_equipment me ON me.monster_id = fm.id
JOIN j_monster_equipment_abilities j ON j.monster_equipment_id = me.id
JOIN equipment_drops ed ON j.equipment_drop_id = ed.id
WHERE ed.auto_ability_id = $1
ORDER BY fm.id
`

type GetAutoAbilityMonsterIDsParams struct {
	AutoAbilityID int32
	Repeatable    sql.NullBool
	Availability  []AvailabilityType
}

func (q *Queries) GetAutoAbilityMonsterIDs(ctx context.Context, arg GetAutoAbilityMonsterIDsParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAbilityMonsterIDs, arg.AutoAbilityID, arg.Repeatable, pq.Array(arg.Availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoAbilityShopIDsPost = `-- name: GetAutoAbilityShopIDsPost :many
SELECT DISTINCT sh.id
FROM shops sh
JOIN shop_equipment_pieces se ON se.shop_id = sh.id
JOIN j_shop_equipment_abilities j ON j.shop_equipment_id = se.id
WHERE (
    $2::availability_type[] IS NULL
    OR
    sh.availability = ANY($2::availability_type[])
)
AND se.shop_type = 'post-airship'
AND j.auto_ability_id = $1
ORDER BY sh.id
`

type GetAutoAbilityShopIDsPostParams struct {
	AutoAbilityID int32
	Availability  []AvailabilityType
}

func (q *Queries) GetAutoAbilityShopIDsPost(ctx context.Context, arg GetAutoAbilityShopIDsPostParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAbilityShopIDsPost, arg.AutoAbilityID, pq.Array(arg.Availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoAbilityShopIDsPre = `-- name: GetAutoAbilityShopIDsPre :many
SELECT DISTINCT sh.id
FROM shops sh
JOIN shop_equipment_pieces se ON se.shop_id = sh.id
JOIN j_shop_equipment_abilities j ON j.shop_equipment_id = se.id
WHERE (
    $2::availability_type[] IS NULL
    OR
    sh.availability = ANY($2::availability_type[])
)
AND se.shop_type = 'pre-airship'
AND j.auto_ability_id = $1
ORDER BY sh.id
`

type GetAutoAbilityShopIDsPreParams struct {
	AutoAbilityID int32
	Availability  []AvailabilityType
}

func (q *Queries) GetAutoAbilityShopIDsPre(ctx context.Context, arg GetAutoAbilityShopIDsPreParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAbilityShopIDsPre, arg.AutoAbilityID, pq.Array(arg.Availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutoAbilityTreasureIDs = `-- name: GetAutoAbilityTreasureIDs :many
SELECT DISTINCT t.id
FROM treasures t
JOIN treasure_equipment_pieces te ON te.treasure_id = t.id
JOIN j_treasure_equipment_abilities j ON j.treasure_equipment_id = te.id
WHERE (
    $1::availability_type[] IS NULL
    OR
    t.availability = ANY($1::availability_type[])
)
AND j.auto_ability_id = $2
ORDER BY t.id
`

type GetAutoAbilityTreasureIDsParams struct {
	Availability  []AvailabilityType
	AutoAbilityID int32
}

func (q *Queries) GetAutoAbilityTreasureIDs(ctx context.Context, arg GetAutoAbilityTreasureIDsParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAutoAbilityTreasureIDs, pq.Array(arg.Availability), arg.AutoAbilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCelestialWeaponAutoAbilityIDs = `-- name: GetCelestialWeaponAutoAbilityIDs :many
SELECT DISTINCT j1.auto_ability_id
FROM j_equipment_tables_required_auto_abilities j1
JOIN j_equipment_tables_names j2 ON j1.equipment_table_id = j2.equipment_table_id
WHERE j2.celestial_weapon_id = $1::int
  AND j2.equipment_table_id = $2::int
ORDER BY j1.auto_ability_id
`

type GetCelestialWeaponAutoAbilityIDsParams struct {
	CelestialWeaponID int32
	EquipmentTableID  int32
}

func (q *Queries) GetCelestialWeaponAutoAbilityIDs(ctx context.Context, arg GetCelestialWeaponAutoAbilityIDsParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCelestialWeaponAutoAbilityIDs, arg.CelestialWeaponID, arg.EquipmentTableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var auto_ability_id int32
		if err := rows.Scan(&auto_ability_id); err != nil {
			return nil, err
		}
		items = append(items, auto_ability_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCelestialWeaponIDs = `-- name: GetCelestialWeaponIDs :many
SELECT id FROM celestial_weapons ORDER BY id
`

func (q *Queries) GetCelestialWeaponIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCelestialWeaponIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCelestialWeaponIDsByFormula = `-- name: GetCelestialWeaponIDsByFormula :many
SELECT id FROM celestial_weapons WHERE formula = $1 ORDER BY id
`

func (q *Queries) GetCelestialWeaponIDsByFormula(ctx context.Context, formula CelestialFormula) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getCelestialWeaponIDsByFormula, formula)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCelestialWeaponTreasureID = `-- name: GetCelestialWeaponTreasureID :one
SELECT te.treasure_id
FROM treasure_equipment_pieces te
JOIN equipment_names en ON te.equipment_name_id = en.id
JOIN j_equipment_tables_names j ON j.equipment_name_id = en.id
WHERE j.celestial_weapon_id = $1
`

func (q *Queries) GetCelestialWeaponTreasureID(ctx context.Context, celestialWeaponID sql.NullInt32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCelestialWeaponTreasureID, celestialWeaponID)
	var treasure_id int32
	err := row.Scan(&treasure_id)
	return treasure_id, err
}

const getEquipmentEquipmentTableIDs = `-- name: GetEquipmentEquipmentTableIDs :many
SELECT equipment_table_id FROM j_equipment_tables_names WHERE equipment_name_id = $1 ORDER BY equipment_table_id
`

func (q *Queries) GetEquipmentEquipmentTableIDs(ctx context.Context, equipmentNameID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentEquipmentTableIDs, equipmentNameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var equipment_table_id int32
		if err := rows.Scan(&equipment_table_id); err != nil {
			return nil, err
		}
		items = append(items, equipment_table_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentIDs = `-- name: GetEquipmentIDs :many
SELECT id FROM equipment_names ORDER BY id
`

func (q *Queries) GetEquipmentIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentIDsByAutoAbilty = `-- name: GetEquipmentIDsByAutoAbilty :many
WITH all_matches AS (
    SELECT en.id AS equipment_name_id, jreq.auto_ability_id
    FROM equipment_names en
    JOIN j_equipment_tables_names j ON j.equipment_name_id = en.id
    JOIN equipment_tables et ON j.equipment_table_id = et.id
    JOIN j_equipment_tables_required_auto_abilities jreq ON jreq.equipment_table_id = et.id
                
    UNION                                  
                         
    SELECT en.id AS equipment_name_id, jpool.auto_ability_id
    FROM equipment_names en
    JOIN j_equipment_tables_names j ON j.equipment_name_id = en.id
    JOIN equipment_tables et ON j.equipment_table_id = et.id
    JOIN ability_pools ap ON ap.equipment_table_id = et.id
    JOIN j_ability_pools_auto_abilities jpool ON jpool.ability_pool_id = ap.id
)                                                               
SELECT m.equipment_name_id
FROM all_matches m
CROSS JOIN (SELECT $1::int[] AS ids) w
WHERE m.auto_ability_id = ANY(w.ids)
GROUP BY m.equipment_name_id, w.ids
HAVING COUNT(DISTINCT m.auto_ability_id) = cardinality(w.ids)
ORDER BY m.equipment_name_id
`

func (q *Queries) GetEquipmentIDsByAutoAbilty(ctx context.Context, autoAbilityIds []int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentIDsByAutoAbilty, pq.Array(autoAbilityIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var equipment_name_id int32
		if err := rows.Scan(&equipment_name_id); err != nil {
			return nil, err
		}
		items = append(items, equipment_name_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentIDsByCharacter = `-- name: GetEquipmentIDsByCharacter :many
SELECT id FROM equipment_names WHERE character_id = $1 ORDER BY id
`

func (q *Queries) GetEquipmentIDsByCharacter(ctx context.Context, characterID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentIDsByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentIDsByEquipType = `-- name: GetEquipmentIDsByEquipType :many
SELECT DISTINCT j.equipment_name_id
FROM j_equipment_tables_names j
JOIN equipment_tables et ON j.equipment_table_id = et.id
WHERE et.type = $1
ORDER BY j.equipment_name_id
`

func (q *Queries) GetEquipmentIDsByEquipType(ctx context.Context, type_ EquipType) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentIDsByEquipType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var equipment_name_id int32
		if err := rows.Scan(&equipment_name_id); err != nil {
			return nil, err
		}
		items = append(items, equipment_name_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentIDsCelestialWeapon = `-- name: GetEquipmentIDsCelestialWeapon :many
SELECT DISTINCT j.equipment_name_id
FROM j_equipment_tables_names j
JOIN equipment_tables et ON j.equipment_table_id = et.id
WHERE et.classification = 'celestial-weapon'
ORDER BY j.equipment_name_id
`

func (q *Queries) GetEquipmentIDsCelestialWeapon(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentIDsCelestialWeapon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var equipment_name_id int32
		if err := rows.Scan(&equipment_name_id); err != nil {
			return nil, err
		}
		items = append(items, equipment_name_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentShopIDs = `-- name: GetEquipmentShopIDs :many
SELECT DISTINCT se.shop_id
FROM shop_equipment_pieces se
JOIN equipment_names en ON se.equipment_name_id = en.id
CROSS JOIN (SELECT $1::availability_type[] AS values) w
CROSS JOIN LATERAL (
    SELECT CASE se.shop_type
        WHEN 'pre-airship' THEN 'pre-story'::availability_type
        WHEN 'post-airship' THEN 'post'::availability_type
    END AS shop_availability
) calc
WHERE en.id = $2::int
  AND (w.values IS NULL OR calc.shop_availability = ANY(w.values))
ORDER BY se.shop_id
`

type GetEquipmentShopIDsParams struct {
	Availability []AvailabilityType
	EquipmentID  int32
}

func (q *Queries) GetEquipmentShopIDs(ctx context.Context, arg GetEquipmentShopIDsParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentShopIDs, pq.Array(arg.Availability), arg.EquipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var shop_id int32
		if err := rows.Scan(&shop_id); err != nil {
			return nil, err
		}
		items = append(items, shop_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentTableCelestialWeaponID = `-- name: GetEquipmentTableCelestialWeaponID :one
SELECT celestial_weapon_id::int FROM j_equipment_tables_names WHERE equipment_table_id = $1
`

func (q *Queries) GetEquipmentTableCelestialWeaponID(ctx context.Context, equipmentTableID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getEquipmentTableCelestialWeaponID, equipmentTableID)
	var celestial_weapon_id int32
	err := row.Scan(&celestial_weapon_id)
	return celestial_weapon_id, err
}

const getEquipmentTableIDs = `-- name: GetEquipmentTableIDs :many
SELECT id FROM equipment_tables ORDER BY id
`

func (q *Queries) GetEquipmentTableIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentTableIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentTableIDsByAutoAbilty = `-- name: GetEquipmentTableIDsByAutoAbilty :many
WITH wanted AS (
    SELECT $1::int[] AS ids
),
all_matches AS (
    SELECT equipment_table_id, auto_ability_id
    FROM j_equipment_tables_required_auto_abilities

    UNION

    SELECT ap.equipment_table_id, jpool.auto_ability_id
    FROM ability_pools ap
    JOIN j_ability_pools_auto_abilities jpool ON jpool.ability_pool_id = ap.id
)
SELECT m.equipment_table_id
FROM all_matches m
JOIN wanted w ON m.auto_ability_id = ANY(w.ids)
GROUP BY m.equipment_table_id, w.ids
HAVING COUNT(DISTINCT m.auto_ability_id) = cardinality(w.ids)
ORDER BY m.equipment_table_id
`

func (q *Queries) GetEquipmentTableIDsByAutoAbilty(ctx context.Context, autoAbilityIds []int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentTableIDsByAutoAbilty, pq.Array(autoAbilityIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var equipment_table_id int32
		if err := rows.Scan(&equipment_table_id); err != nil {
			return nil, err
		}
		items = append(items, equipment_table_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentTableIDsCelestialWeapon = `-- name: GetEquipmentTableIDsCelestialWeapon :many
SELECT id FROM equipment_tables WHERE classification = 'celestial-weapon' ORDER BY id
`

func (q *Queries) GetEquipmentTableIDsCelestialWeapon(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentTableIDsCelestialWeapon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentTableIDsEquipType = `-- name: GetEquipmentTableIDsEquipType :many
SELECT id FROM equipment_tables WHERE type = $1 ORDER BY id
`

func (q *Queries) GetEquipmentTableIDsEquipType(ctx context.Context, type_ EquipType) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentTableIDsEquipType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentTreasureIDs = `-- name: GetEquipmentTreasureIDs :many
SELECT DISTINCT t.id
FROM treasures t
JOIN treasure_equipment_pieces te ON te.treasure_id = t.id
JOIN equipment_names en ON te.equipment_name_id = en.id
CROSS JOIN (SELECT $1::availability_type[] AS values) w
WHERE en.id = $2::int
  AND (w.values IS NULL OR t.availability = ANY(w.values))
ORDER BY t.id
`

type GetEquipmentTreasureIDsParams struct {
	Availability []AvailabilityType
	EquipmentID  int32
}

func (q *Queries) GetEquipmentTreasureIDs(ctx context.Context, arg GetEquipmentTreasureIDsParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentTreasureIDs, pq.Array(arg.Availability), arg.EquipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
