// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_items.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const getItemAutoAbilityIDs = `-- name: GetItemAutoAbilityIDs :many
SELECT DISTINCT aa.id
FROM auto_abilities aa
JOIN item_amounts ia ON aa.required_item_amount_id = ia.id
JOIN master_items mi ON ia.master_item_id = mi.id
JOIN items i ON i.master_item_id = mi.id
WHERE i.id = $1
ORDER BY aa.id
`

func (q *Queries) GetItemAutoAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemAutoAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemBlitzballPrizeIDs = `-- name: GetItemBlitzballPrizeIDs :many
SELECT DISTINCT bp.id
FROM blitzball_positions bp
JOIN blitzball_items bi ON bi.position_id = bp.id
JOIN possible_items pi ON bi.possible_item_id = pi.id
JOIN item_amounts ia ON pi.item_amount_id = ia.id
JOIN master_items mi ON ia.master_item_id = mi.id
JOIN items i ON i.master_item_id = mi.id
WHERE i.id = $1
ORDER BY bp.id
`

func (q *Queries) GetItemBlitzballPrizeIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemBlitzballPrizeIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemIDs = `-- name: GetItemIDs :many
SELECT id FROM items ORDER BY id
`

func (q *Queries) GetItemIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemIDsByRelatedStat = `-- name: GetItemIDsByRelatedStat :many
SELECT i.id
FROM items i
JOIN j_items_related_stats j ON j.item_id = i.id
JOIN stats s ON j.stat_id = s.id
WHERE s.id = $1
ORDER BY i.id
`

func (q *Queries) GetItemIDsByRelatedStat(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemIDsByRelatedStat, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemIDsCategory = `-- name: GetItemIDsCategory :many
SELECT id FROM items WHERE category = ANY($1::item_category[]) ORDER BY id
`

func (q *Queries) GetItemIDsCategory(ctx context.Context, category []ItemCategory) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemIDsCategory, pq.Array(category))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemIDsMonster = `-- name: GetItemIDsMonster :many
SELECT DISTINCT i.id
FROM items i
WHERE EXISTS (
    SELECT 1
    FROM monsters m
    JOIN monster_items mi ON mi.monster_id = m.id
    JOIN item_amounts ia ON ia.id IN (
        mi.steal_common_id,
        mi.steal_rare_id,
        mi.drop_common_id,
        mi.drop_rare_id,
        mi.secondary_drop_common_id,
        mi.secondary_drop_rare_id,
        mi.bribe_id
    )
    JOIN master_items mit ON mit.id = ia.master_item_id
    WHERE mit.id = i.master_item_id
)
OR EXISTS (
    SELECT 1
    FROM monsters m
    JOIN monster_items mi ON mi.monster_id = m.id
    JOIN j_monster_items_other_items jmio ON jmio.monster_items_id = mi.id
    JOIN possible_items pi ON pi.id = jmio.possible_item_id
    JOIN item_amounts ia ON ia.id = pi.item_amount_id
    JOIN master_items mit ON mit.id = ia.master_item_id
    WHERE mit.id = i.master_item_id
)
ORDER BY i.id
`

func (q *Queries) GetItemIDsMonster(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemIDsMonster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemIDsQuest = `-- name: GetItemIDsQuest :many
SELECT DISTINCT i.id
FROM items i
JOIN master_items mi ON i.master_item_id = mi.id
JOIN item_amounts ia ON ia.master_item_id = mi.id
JOIN quest_completions qc ON qc.item_amount_id = ia.id
JOIN quests q ON q.completion_id = qc.id
ORDER BY i.id
`

func (q *Queries) GetItemIDsQuest(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemIDsQuest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemIDsShop = `-- name: GetItemIDsShop :many
SELECT DISTINCT i.id
FROM items i
JOIN shop_items si ON si.item_id = i.id
JOIN j_shops_items j ON j.shop_item_id = si.id
JOIN shops s ON j.shop_id = s.id
ORDER BY i.id
`

func (q *Queries) GetItemIDsShop(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemIDsShop)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemIDsTreasure = `-- name: GetItemIDsTreasure :many
SELECT DISTINCT i.id
FROM items i
JOIN master_items mi ON i.master_item_id = mi.id
JOIN item_amounts ia ON ia.master_item_id = mi.id
JOIN j_treasures_items j ON j.item_amount_id = ia.id
JOIN treasures t ON j.treasure_id = t.id
ORDER BY i.id
`

func (q *Queries) GetItemIDsTreasure(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemIDsTreasure)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemIDsWithAbility = `-- name: GetItemIDsWithAbility :many
SELECT i.id
FROM items i
JOIN item_abilities ia ON ia.item_id = i.id
ORDER BY i.id
`

func (q *Queries) GetItemIDsWithAbility(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemIDsWithAbility)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemMixIDs = `-- name: GetItemMixIDs :many
SELECT DISTINCT m.id
FROM mixes m
JOIN mix_combinations mc ON mc.mix_id = m.id
JOIN items i ON mc.first_item_id = i.id OR mc.second_item_id = i.id
WHERE i.id = $1
ORDER BY m.id
`

func (q *Queries) GetItemMixIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemMixIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemMonsterIDs = `-- name: GetItemMonsterIDs :many
SELECT DISTINCT m.id
FROM monsters m
JOIN monster_items mi ON mi.monster_id = m.id
WHERE ($1::BOOLEAN IS NULL OR m.is_repeatable = $1::BOOLEAN)
  AND ($2::availability_type[] IS NULL OR m.availability = ANY($2::availability_type[]))
  AND (
    EXISTS (
      SELECT 1
      FROM item_amounts ia
      JOIN master_items mit ON ia.master_item_id = mit.id
      JOIN items i ON i.master_item_id = mit.id
      WHERE ia.id IN (
          mi.steal_common_id,
          mi.steal_rare_id,
          mi.drop_common_id,
          mi.drop_rare_id,
          mi.secondary_drop_common_id,
          mi.secondary_drop_rare_id,
          mi.bribe_id
      )
      AND i.id = $3
  )
    OR EXISTS (
      SELECT 1
      FROM j_monster_items_other_items jmio
      JOIN possible_items pi ON pi.id = jmio.possible_item_id
      JOIN item_amounts ia ON pi.item_amount_id = ia.id
      JOIN master_items mit ON ia.master_item_id = mit.id
      JOIN items i ON i.master_item_id = mit.id
      WHERE jmio.monster_items_id = mi.id
        AND i.id = $3
    )
  )
ORDER BY m.id
`

type GetItemMonsterIDsParams struct {
	Repeatable   sql.NullBool
	Availability []AvailabilityType
	ItemID       int32
}

func (q *Queries) GetItemMonsterIDs(ctx context.Context, arg GetItemMonsterIDsParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemMonsterIDs, arg.Repeatable, pq.Array(arg.Availability), arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemPlayerAbilityIDs = `-- name: GetItemPlayerAbilityIDs :many
SELECT DISTINCT pa.id
FROM player_abilities pa
JOIN item_amounts ia ON pa.aeon_learn_item_id = ia.id
JOIN master_items mi ON ia.master_item_id = mi.id
JOIN items i ON i.master_item_id = mi.id
WHERE i.id = $1
ORDER BY pa.id
`

func (q *Queries) GetItemPlayerAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemPlayerAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemQuestIDs = `-- name: GetItemQuestIDs :many
SELECT DISTINCT q.id
FROM quests q
JOIN quest_completions qc ON q.completion_id = qc.id
JOIN item_amounts ia ON qc.item_amount_id = ia.id
JOIN master_items mi ON ia.master_item_id = mi.id
JOIN items i ON i.master_item_id = mi.id
WHERE
  i.id = $1
  AND ($2::BOOLEAN IS NULL OR q.is_repeatable = $2::BOOLEAN)
  AND ($3::availability_type[] IS NULL OR q.availability = ANY($3::availability_type[]))
ORDER BY q.id
`

type GetItemQuestIDsParams struct {
	ItemID       int32
	Repeatable   sql.NullBool
	Availability []AvailabilityType
}

func (q *Queries) GetItemQuestIDs(ctx context.Context, arg GetItemQuestIDsParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemQuestIDs, arg.ItemID, arg.Repeatable, pq.Array(arg.Availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemShopIDs = `-- name: GetItemShopIDs :many
SELECT DISTINCT s.id
FROM shops s
JOIN j_shops_items j ON j.shop_id = s.id
JOIN shop_items si ON j.shop_item_id = si.id
JOIN items i ON si.item_id = i.id
WHERE
  i.id = $1
  AND ($2::availability_type[] IS NULL OR s.availability = ANY($2::availability_type[]))
ORDER BY s.id
`

type GetItemShopIDsParams struct {
	ItemID       int32
	Availability []AvailabilityType
}

func (q *Queries) GetItemShopIDs(ctx context.Context, arg GetItemShopIDsParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemShopIDs, arg.ItemID, pq.Array(arg.Availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemTreasureIDs = `-- name: GetItemTreasureIDs :many
SELECT DISTINCT t.id
FROM treasures t
JOIN j_treasures_items j ON j.treasure_id = t.id
JOIN item_amounts ia ON j.item_amount_id = ia.id
JOIN master_items mi ON ia.master_item_id = mi.id
JOIN items i ON i.master_item_id = mi.id
WHERE
  i.id = $1
  AND ($2::availability_type[] IS NULL OR t.availability = ANY($2::availability_type[]))
ORDER BY t.id
`

type GetItemTreasureIDsParams struct {
	ItemID       int32
	Availability []AvailabilityType
}

func (q *Queries) GetItemTreasureIDs(ctx context.Context, arg GetItemTreasureIDsParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getItemTreasureIDs, arg.ItemID, pq.Array(arg.Availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKeyItemAreaIDs = `-- name: GetKeyItemAreaIDs :many
SELECT DISTINCT a.id
FROM areas a
WHERE
  EXISTS (
    SELECT 1
    FROM completion_areas ca
    JOIN quest_completions qc ON ca.completion_id = qc.id
    JOIN item_amounts ia ON qc.item_amount_id = ia.id
    JOIN master_items mi ON ia.master_item_id = mi.id
    JOIN key_items ki ON ki.master_item_id = mi.id
    WHERE ca.area_id = a.id
      AND ki.id = $1
  )
  OR
  EXISTS (
    SELECT 1
    FROM treasures t
    JOIN j_treasures_items j ON j.treasure_id = t.id
    JOIN item_amounts ia ON j.item_amount_id = ia.id
    JOIN master_items mi ON ia.master_item_id = mi.id
    JOIN key_items ki ON ki.master_item_id = mi.id
    WHERE t.area_id = a.id
      AND ki.id = $1
  )
ORDER BY a.id
`

func (q *Queries) GetKeyItemAreaIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getKeyItemAreaIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKeyItemCelestialWeapon = `-- name: GetKeyItemCelestialWeapon :one
SELECT id FROM celestial_weapons WHERE key_item_base = $1
`

func (q *Queries) GetKeyItemCelestialWeapon(ctx context.Context, keyItemBase KeyItemBase) (int32, error) {
	row := q.db.QueryRowContext(ctx, getKeyItemCelestialWeapon, keyItemBase)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getKeyItemIDs = `-- name: GetKeyItemIDs :many
SELECT id FROM key_items ORDER BY id
`

func (q *Queries) GetKeyItemIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getKeyItemIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKeyItemIDsByAvailability = `-- name: GetKeyItemIDsByAvailability :many
SELECT DISTINCT ki.id
FROM key_items ki
JOIN master_items mi ON ki.master_item_id = mi.id
JOIN item_amounts ia ON ia.master_item_id = mi.id
WHERE
  EXISTS (
    SELECT 1
    FROM j_treasures_items j
    JOIN treasures t ON j.treasure_id = t.id
    WHERE j.item_amount_id = ia.id
      AND ($1::availability_type[] IS NULL OR t.availability = ANY($1::availability_type[]))
  )
  OR
  EXISTS (
    SELECT 1
    FROM quest_completions qc
    JOIN quests q ON q.completion_id = qc.id
    WHERE qc.item_amount_id = ia.id
      AND ($1::availability_type[] IS NULL OR q.availability = ANY($1::availability_type[]))
  )
ORDER BY ki.id
`

func (q *Queries) GetKeyItemIDsByAvailability(ctx context.Context, availability []AvailabilityType) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getKeyItemIDsByAvailability, pq.Array(availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKeyItemIDsCategory = `-- name: GetKeyItemIDsCategory :many
SELECT id FROM key_items WHERE category = ANY($1::key_item_category[]) ORDER BY id
`

func (q *Queries) GetKeyItemIDsCategory(ctx context.Context, category []KeyItemCategory) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getKeyItemIDsCategory, pq.Array(category))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKeyItemIDsQuest = `-- name: GetKeyItemIDsQuest :many
SELECT DISTINCT ki.id
FROM key_items ki
JOIN master_items mi ON ki.master_item_id = mi.id
JOIN item_amounts ia ON ia.master_item_id = mi.id
JOIN quest_completions qc ON qc.item_amount_id = ia.id
JOIN quests q ON q.completion_id = qc.id
ORDER BY ki.id
`

func (q *Queries) GetKeyItemIDsQuest(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getKeyItemIDsQuest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKeyItemIDsTreasure = `-- name: GetKeyItemIDsTreasure :many
SELECT DISTINCT ki.id
FROM key_items ki
JOIN master_items mi ON ki.master_item_id = mi.id
JOIN item_amounts ia ON ia.master_item_id = mi.id
JOIN j_treasures_items j ON j.item_amount_id = ia.id
JOIN treasures t ON j.treasure_id = t.id
ORDER BY ki.id
`

func (q *Queries) GetKeyItemIDsTreasure(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getKeyItemIDsTreasure)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKeyItemQuestIDs = `-- name: GetKeyItemQuestIDs :many
SELECT DISTINCT q.id
FROM quests q
JOIN quest_completions qc ON q.completion_id = qc.id
JOIN item_amounts ia ON qc.item_amount_id = ia.id
JOIN master_items mi ON ia.master_item_id = mi.id
JOIN key_items ki ON ki.master_item_id = mi.id
WHERE ki.id = $1
ORDER BY q.id
`

func (q *Queries) GetKeyItemQuestIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getKeyItemQuestIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKeyItemTreasureIDs = `-- name: GetKeyItemTreasureIDs :many
SELECT DISTINCT t.id
FROM treasures t
JOIN j_treasures_items j ON j.treasure_id = t.id
JOIN item_amounts ia ON j.item_amount_id = ia.id
JOIN master_items mi ON ia.master_item_id = mi.id
JOIN key_items ki ON ki.master_item_id = mi.id
WHERE ki.id = $1
ORDER BY t.id
`

func (q *Queries) GetKeyItemTreasureIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getKeyItemTreasureIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterItemIDs = `-- name: GetMasterItemIDs :many
SELECT id FROM master_items ORDER BY id
`

func (q *Queries) GetMasterItemIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMasterItemIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterItemIDsByType = `-- name: GetMasterItemIDsByType :many
SELECT id FROM master_items WHERE type = ANY($1::item_type[]) ORDER BY id
`

func (q *Queries) GetMasterItemIDsByType(ctx context.Context, itemType []ItemType) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMasterItemIDsByType, pq.Array(itemType))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterItemIDsMonster = `-- name: GetMasterItemIDsMonster :many
SELECT DISTINCT mit.id
FROM master_items mit
WHERE EXISTS (
    SELECT 1
    FROM monsters m
    JOIN monster_items mi ON mi.monster_id = m.id
    JOIN item_amounts ia ON ia.id IN (
        mi.steal_common_id,
        mi.steal_rare_id,
        mi.drop_common_id,
        mi.drop_rare_id,
        mi.secondary_drop_common_id,
        mi.secondary_drop_rare_id,
        mi.bribe_id
    )
    WHERE mit.id = ia.master_item_id
)
OR EXISTS (
    SELECT 1
    FROM monsters m
    JOIN monster_items mi ON mi.monster_id = m.id
    JOIN j_monster_items_other_items jmio ON jmio.monster_items_id = mi.id
    JOIN possible_items pi ON pi.id = jmio.possible_item_id
    JOIN item_amounts ia ON ia.id = pi.item_amount_id
    WHERE mit.id = ia.master_item_id
)
ORDER BY mit.id
`

func (q *Queries) GetMasterItemIDsMonster(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMasterItemIDsMonster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterItemIDsQuest = `-- name: GetMasterItemIDsQuest :many
SELECT DISTINCT mi.id
FROM master_items mi
JOIN item_amounts ia ON ia.master_item_id = mi.id
JOIN quest_completions qc ON qc.item_amount_id = ia.id
JOIN quests q ON q.completion_id = qc.id
ORDER BY mi.id
`

func (q *Queries) GetMasterItemIDsQuest(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMasterItemIDsQuest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterItemIDsShop = `-- name: GetMasterItemIDsShop :many
SELECT DISTINCT mi.id
FROM master_items mi
JOIN items i ON i.master_item_id = mi.id
JOIN shop_items si ON si.item_id = i.id
JOIN j_shops_items j ON j.shop_item_id = si.id
JOIN shops s ON j.shop_id = s.id
ORDER BY mi.id
`

func (q *Queries) GetMasterItemIDsShop(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMasterItemIDsShop)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterItemIDsTreasure = `-- name: GetMasterItemIDsTreasure :many
SELECT DISTINCT mi.id
FROM master_items mi
JOIN item_amounts ia ON ia.master_item_id = mi.id
JOIN j_treasures_items j ON j.item_amount_id = ia.id
JOIN treasures t ON j.treasure_id = t.id
ORDER BY mi.id
`

func (q *Queries) GetMasterItemIDsTreasure(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMasterItemIDsTreasure)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterItemMonsterIDs = `-- name: GetMasterItemMonsterIDs :many
SELECT DISTINCT m.id
FROM monsters m
JOIN monster_items mi ON mi.monster_id = m.id
WHERE EXISTS (
    SELECT 1
    FROM item_amounts ia
    JOIN master_items mit ON ia.master_item_id = mit.id
    WHERE ia.id IN (
        mi.steal_common_id,
        mi.steal_rare_id,
        mi.drop_common_id,
        mi.drop_rare_id,
        mi.secondary_drop_common_id,
        mi.secondary_drop_rare_id,
        mi.bribe_id
    )
    AND mit.id = $1
)
OR EXISTS (
  SELECT 1
  FROM j_monster_items_other_items jmio
  JOIN possible_items pi ON pi.id = jmio.possible_item_id
  JOIN item_amounts ia ON pi.item_amount_id = ia.id
  JOIN master_items mit ON ia.master_item_id = mit.id
  WHERE jmio.monster_items_id = mi.id
    AND mit.id = $1
)
ORDER BY m.id
`

func (q *Queries) GetMasterItemMonsterIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMasterItemMonsterIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterItemQuestIDs = `-- name: GetMasterItemQuestIDs :many
SELECT DISTINCT q.id
FROM quests q
JOIN quest_completions qc ON q.completion_id = qc.id
JOIN item_amounts ia ON qc.item_amount_id = ia.id
JOIN master_items mi ON ia.master_item_id = mi.id
WHERE mi.id = $1
ORDER BY q.id
`

func (q *Queries) GetMasterItemQuestIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMasterItemQuestIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterItemShopIDs = `-- name: GetMasterItemShopIDs :many
SELECT DISTINCT s.id
FROM shops s
JOIN j_shops_items j ON j.shop_id = s.id
JOIN shop_items si ON j.shop_item_id = si.id
JOIN items i ON si.item_id = i.id
JOIN master_items mi ON i.master_item_id = mi.id
WHERE mi.id = $1
ORDER BY s.id
`

func (q *Queries) GetMasterItemShopIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMasterItemShopIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterItemTreasureIDs = `-- name: GetMasterItemTreasureIDs :many
SELECT DISTINCT t.id
FROM treasures t
JOIN j_treasures_items j ON j.treasure_id = t.id
JOIN item_amounts ia ON j.item_amount_id = ia.id
JOIN master_items mi ON ia.master_item_id = mi.id
WHERE mi.id = $1
ORDER BY t.id
`

func (q *Queries) GetMasterItemTreasureIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMasterItemTreasureIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimerAreaIDs = `-- name: GetPrimerAreaIDs :many
SELECT DISTINCT a.id
FROM areas a
JOIN treasures t ON t.area_id = a.id
JOIN j_treasures_items j ON j.treasure_id = t.id
JOIN item_amounts ia ON j.item_amount_id = ia.id
JOIN master_items mi ON ia.master_item_id = mi.id
JOIN key_items ki ON ki.master_item_id = mi.id
JOIN primers p ON p.key_item_id = ki.id
WHERE p.id = $1
ORDER BY a.id
`

func (q *Queries) GetPrimerAreaIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getPrimerAreaIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimerIDs = `-- name: GetPrimerIDs :many
SELECT id FROM primers ORDER BY id
`

func (q *Queries) GetPrimerIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getPrimerIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimerIDsByAvailability = `-- name: GetPrimerIDsByAvailability :many
SELECT DISTINCT p.id
FROM primers p
JOIN key_items ki ON p.key_item_id = ki.id
JOIN master_items mi ON ki.master_item_id = mi.id
JOIN item_amounts ia ON ia.master_item_id = mi.id
JOIN j_treasures_items j ON j.item_amount_id = ia.id
JOIN treasures t ON j.treasure_id = t.id
WHERE t.availability = ANY($1::availability_type[])
ORDER BY p.id
`

func (q *Queries) GetPrimerIDsByAvailability(ctx context.Context, availability []AvailabilityType) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getPrimerIDsByAvailability, pq.Array(availability))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimerTreasureIDs = `-- name: GetPrimerTreasureIDs :many
SELECT DISTINCT t.id
FROM treasures t
JOIN j_treasures_items j ON j.treasure_id = t.id
JOIN item_amounts ia ON j.item_amount_id = ia.id
JOIN master_items mi ON ia.master_item_id = mi.id
JOIN key_items ki ON ki.master_item_id = mi.id
JOIN primers p ON p.key_item_id = ki.id
WHERE p.id = $1
ORDER BY t.id
`

func (q *Queries) GetPrimerTreasureIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getPrimerTreasureIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
