// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_commands_menus.sql

package database

import (
	"context"
	"database/sql"
)

const getOverdriveCommandIDs = `-- name: GetOverdriveCommandIDs :many
SELECT id FROM overdrive_commands ORDER BY id
`

func (q *Queries) GetOverdriveCommandIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getOverdriveCommandIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverdriveCommandOverdriveAbilityIDs = `-- name: GetOverdriveCommandOverdriveAbilityIDs :many
SELECT oa.id
FROM overdrive_abilities oa
JOIN j_overdrives_overdrive_abilities j ON j.overdrive_ability_id = oa.id
JOIN overdrives o ON j.overdrive_id = o.id
JOIN overdrive_commands oc ON o.od_command_id = oc.id
WHERE oc.id = $1
ORDER BY oa.id
`

func (q *Queries) GetOverdriveCommandOverdriveAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getOverdriveCommandOverdriveAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverdriveCommandOverdriveIDs = `-- name: GetOverdriveCommandOverdriveIDs :many
SELECT o.id
FROM overdrives o
JOIN overdrive_commands oc ON o.od_command_id = oc.id
WHERE oc.id = $1
ORDER BY o.id
`

func (q *Queries) GetOverdriveCommandOverdriveIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getOverdriveCommandOverdriveIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmenuAbilityIDs = `-- name: GetSubmenuAbilityIDs :many
SELECT a.id
FROM abilities a
LEFT JOIN player_abilities pa ON pa.ability_id = a.id
LEFT JOIN unspecified_abilities ua ON ua.ability_id = a.id
WHERE pa.submenu_id = $1 OR ua.submenu_id = $1
ORDER BY a.id
`

func (q *Queries) GetSubmenuAbilityIDs(ctx context.Context, submenuID sql.NullInt32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getSubmenuAbilityIDs, submenuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmenuIDs = `-- name: GetSubmenuIDs :many
SELECT id FROM submenus ORDER BY id
`

func (q *Queries) GetSubmenuIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getSubmenuIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmenuOpenedByAbilityID = `-- name: GetSubmenuOpenedByAbilityID :one
SELECT a.id
FROM abilities a
LEFT JOIN player_abilities pa ON pa.ability_id = a.id
LEFT JOIN unspecified_abilities ua ON ua.ability_id = a.id
WHERE pa.open_submenu_id = $1 OR ua.open_submenu_id = $1
`

func (q *Queries) GetSubmenuOpenedByAbilityID(ctx context.Context, openSubmenuID sql.NullInt32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getSubmenuOpenedByAbilityID, openSubmenuID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getSubmenuOpenedByAeonCommandID = `-- name: GetSubmenuOpenedByAeonCommandID :one
SELECT id FROM aeon_commands WHERE submenu_id = $1
`

func (q *Queries) GetSubmenuOpenedByAeonCommandID(ctx context.Context, submenuID sql.NullInt32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getSubmenuOpenedByAeonCommandID, submenuID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getSubmenuOpenedByOverdriveCommandIDs = `-- name: GetSubmenuOpenedByOverdriveCommandIDs :many
SELECT oc.id
FROM overdrive_commands oc
JOIN submenus s ON oc.submenu_id = s.id
WHERE s.id = $1
ORDER BY oc.id
`

func (q *Queries) GetSubmenuOpenedByOverdriveCommandIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getSubmenuOpenedByOverdriveCommandIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopmenuAbilityIDs = `-- name: GetTopmenuAbilityIDs :many
SELECT a.id
FROM abilities a
LEFT JOIN player_abilities pa ON pa.ability_id = a.id
LEFT JOIN unspecified_abilities ua ON ua.ability_id = a.id
LEFT JOIN trigger_commands tc ON tc.ability_id = a.id
WHERE pa.topmenu_id = $1 OR ua.topmenu_id = $1 OR tc.topmenu_id = $1
ORDER BY a.id
`

func (q *Queries) GetTopmenuAbilityIDs(ctx context.Context, topmenuID sql.NullInt32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getTopmenuAbilityIDs, topmenuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopmenuAeonCommandIDs = `-- name: GetTopmenuAeonCommandIDs :many
SELECT ac.id
FROM aeon_commands ac
JOIN topmenus t ON ac.topmenu_id = t.id
WHERE t.id = $1
ORDER BY ac.id
`

func (q *Queries) GetTopmenuAeonCommandIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getTopmenuAeonCommandIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopmenuIDs = `-- name: GetTopmenuIDs :many
SELECT id FROM topmenus ORDER BY id
`

func (q *Queries) GetTopmenuIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getTopmenuIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopmenuOverdriveCommandIDs = `-- name: GetTopmenuOverdriveCommandIDs :many
SELECT oc.id
FROM overdrive_commands oc
JOIN topmenus t ON oc.topmenu_id = t.id
WHERE t.id = $1
ORDER BY oc.id
`

func (q *Queries) GetTopmenuOverdriveCommandIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getTopmenuOverdriveCommandIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopmenuOverdriveIDs = `-- name: GetTopmenuOverdriveIDs :many
SELECT o.id
FROM overdrives o
JOIN topmenus t ON o.topmenu_id = t.id
WHERE t.id = $1
ORDER BY o.id
`

func (q *Queries) GetTopmenuOverdriveIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getTopmenuOverdriveIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopmenuSubmenuIDs = `-- name: GetTopmenuSubmenuIDs :many
SELECT s.id
FROM submenus s
JOIN topmenus t ON s.topmenu_id = t.id
WHERE t.id = $1
ORDER BY s.id
`

func (q *Queries) GetTopmenuSubmenuIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getTopmenuSubmenuIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
