// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_battle_mechanics.sql

package database

import (
	"context"
)

const getAgilityTierByAgility = `-- name: GetAgilityTierByAgility :one
SELECT id, data_hash, min_agility, max_agility, tick_speed, monster_min_icv, monster_max_icv, character_max_icv FROM agility_tiers
WHERE ($1::int) >= min_agility
AND ($1::int) <= max_agility
`

func (q *Queries) GetAgilityTierByAgility(ctx context.Context, agility int32) (AgilityTier, error) {
	row := q.db.QueryRowContext(ctx, getAgilityTierByAgility, agility)
	var i AgilityTier
	err := row.Scan(
		&i.ID,
		&i.DataHash,
		&i.MinAgility,
		&i.MaxAgility,
		&i.TickSpeed,
		&i.MonsterMinIcv,
		&i.MonsterMaxIcv,
		&i.CharacterMaxIcv,
	)
	return i, err
}

const getElementAutoAbilityIDs = `-- name: GetElementAutoAbilityIDs :many
SELECT DISTINCT aa.id
FROM auto_abilities aa
WHERE EXISTS (
    SELECT 1
    FROM elemental_resists er
    JOIN elements e ON er.element_id = e.id
    WHERE aa.added_elem_resist_id = er.id
      AND e.id = $1

    UNION ALL

    SELECT 1
    FROM elements e
    WHERE aa.on_hit_element_id = e.id
      AND e.id = $1
)
ORDER BY aa.id
`

func (q *Queries) GetElementAutoAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getElementAutoAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElementEnemyAbilityIDs = `-- name: GetElementEnemyAbilityIDs :many
SELECT DISTINCT ea.id
FROM enemy_abilities ea
JOIN abilities a ON ea.ability_id = a.id
JOIN j_abilities_battle_interactions j1 ON j1.ability_id = a.id
JOIN battle_interactions bi ON j1.battle_interaction_id = bi.id
JOIN j_battle_interactions_damage j2 ON j2.ability_id = a.id AND j2.battle_interaction_id = bi.id
JOIN damages d ON j2.damage_id = d.id
JOIN elements e ON d.element_id = e.id
WHERE e.id = $1
ORDER BY ea.id
`

func (q *Queries) GetElementEnemyAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getElementEnemyAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElementIDs = `-- name: GetElementIDs :many
SELECT id FROM elements ORDER BY id
`

func (q *Queries) GetElementIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getElementIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElementItemAbilityIDs = `-- name: GetElementItemAbilityIDs :many
SELECT DISTINCT ia.id
FROM item_abilities ia
JOIN abilities a ON ia.ability_id = a.id
JOIN j_abilities_battle_interactions j1 ON j1.ability_id = a.id
JOIN battle_interactions bi ON j1.battle_interaction_id = bi.id
JOIN j_battle_interactions_damage j2 ON j2.ability_id = a.id AND j2.battle_interaction_id = bi.id
JOIN damages d ON j2.damage_id = d.id
JOIN elements e ON d.element_id = e.id
WHERE e.id = $1
ORDER BY ia.id
`

func (q *Queries) GetElementItemAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getElementItemAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElementMonsterIDsAbsorb = `-- name: GetElementMonsterIDsAbsorb :many
SELECT DISTINCT m.id
FROM monsters m
JOIN j_monsters_elem_resists j ON j.monster_id = m.id
JOIN elemental_resists er ON j.elem_resist_id = er.id
WHERE er.element_id = $1 AND er.affinity = 'absorb'
ORDER BY m.id
`

func (q *Queries) GetElementMonsterIDsAbsorb(ctx context.Context, elementID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getElementMonsterIDsAbsorb, elementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElementMonsterIDsHalved = `-- name: GetElementMonsterIDsHalved :many
SELECT DISTINCT m.id
FROM monsters m
JOIN j_monsters_elem_resists j ON j.monster_id = m.id
JOIN elemental_resists er ON j.elem_resist_id = er.id
WHERE er.element_id = $1 AND er.affinity = 'halved'
ORDER BY m.id
`

func (q *Queries) GetElementMonsterIDsHalved(ctx context.Context, elementID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getElementMonsterIDsHalved, elementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElementMonsterIDsImmune = `-- name: GetElementMonsterIDsImmune :many
SELECT DISTINCT m.id
FROM monsters m
JOIN j_monsters_elem_resists j ON j.monster_id = m.id
JOIN elemental_resists er ON j.elem_resist_id = er.id
WHERE er.element_id = $1 AND er.affinity = 'immune'
ORDER BY m.id
`

func (q *Queries) GetElementMonsterIDsImmune(ctx context.Context, elementID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getElementMonsterIDsImmune, elementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElementMonsterIDsWeak = `-- name: GetElementMonsterIDsWeak :many
SELECT DISTINCT m.id
FROM monsters m
JOIN j_monsters_elem_resists j ON j.monster_id = m.id
JOIN elemental_resists er ON j.elem_resist_id = er.id
WHERE er.element_id = $1 AND er.affinity = 'weak'
ORDER BY m.id
`

func (q *Queries) GetElementMonsterIDsWeak(ctx context.Context, elementID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getElementMonsterIDsWeak, elementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElementOverdriveAbilityIDs = `-- name: GetElementOverdriveAbilityIDs :many
SELECT DISTINCT oa.id
FROM overdrive_abilities oa
JOIN abilities a ON oa.ability_id = a.id
JOIN j_abilities_battle_interactions j1 ON j1.ability_id = a.id
JOIN battle_interactions bi ON j1.battle_interaction_id = bi.id
JOIN j_battle_interactions_damage j2 ON j2.ability_id = a.id AND j2.battle_interaction_id = bi.id
JOIN damages d ON j2.damage_id = d.id
JOIN elements e ON d.element_id = e.id
WHERE e.id = $1
ORDER BY oa.id
`

func (q *Queries) GetElementOverdriveAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getElementOverdriveAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElementPlayerAbilityIDs = `-- name: GetElementPlayerAbilityIDs :many
SELECT DISTINCT pa.id
FROM player_abilities pa
JOIN abilities a ON pa.ability_id = a.id
JOIN j_abilities_battle_interactions j1 ON j1.ability_id = a.id
JOIN battle_interactions bi ON j1.battle_interaction_id = bi.id
JOIN j_battle_interactions_damage j2 ON j2.ability_id = a.id AND j2.battle_interaction_id = bi.id
JOIN damages d ON j2.damage_id = d.id
JOIN elements e ON d.element_id = e.id
WHERE e.id = $1
ORDER BY pa.id
`

func (q *Queries) GetElementPlayerAbilityIDs(ctx context.Context, id int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getElementPlayerAbilityIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElementStatusConditionID = `-- name: GetElementStatusConditionID :one
SELECT sc.id
FROM status_conditions sc
JOIN elemental_resists er ON sc.added_elem_resist_id = er.id
JOIN elements e ON er.element_id = e.id
WHERE e.id = $1
`

func (q *Queries) GetElementStatusConditionID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getElementStatusConditionID, id)
	err := row.Scan(&id)
	return id, err
}

const getOverdriveModeIDs = `-- name: GetOverdriveModeIDs :many
SELECT id FROM overdrive_modes ORDER BY id
`

func (q *Queries) GetOverdriveModeIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getOverdriveModeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverdriveModeIDsByType = `-- name: GetOverdriveModeIDsByType :many
SELECT id FROM overdrive_modes WHERE type = $1 ORDER BY id
`

func (q *Queries) GetOverdriveModeIDsByType(ctx context.Context, type_ OverdriveModeType) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getOverdriveModeIDsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
