// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sidequests_get.sql

package database

import (
	"context"
	"database/sql"
)

const getArenaCreationIDs = `-- name: GetArenaCreationIDs :many
SELECT id FROM monster_arena_creations ORDER BY id
`

func (q *Queries) GetArenaCreationIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getArenaCreationIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArenaCreationIDsByCategory = `-- name: GetArenaCreationIDsByCategory :many
SELECT id FROM monster_arena_creations WHERE category = $1 ORDER BY id
`

func (q *Queries) GetArenaCreationIDsByCategory(ctx context.Context, category MaCreationCategory) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getArenaCreationIDsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlitzballPrizeIDs = `-- name: GetBlitzballPrizeIDs :many
SELECT id FROM blitzball_positions ORDER BY id
`

func (q *Queries) GetBlitzballPrizeIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getBlitzballPrizeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlitzballPrizeIDsByCategory = `-- name: GetBlitzballPrizeIDsByCategory :many
SELECT id FROM blitzball_positions WHERE category = $1 ORDER BY id
`

func (q *Queries) GetBlitzballPrizeIDsByCategory(ctx context.Context, category BlitzballTournamentCategory) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getBlitzballPrizeIDsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParentSidequest = `-- name: GetParentSidequest :one
SELECT q.id, q.data_hash, q.name, q.type
FROM subquests su
LEFT JOIN sidequests si ON su.sidequest_id = si.id
LEFT JOIN quests q ON si.quest_id = q.id
WHERE su.id = $1
`

type GetParentSidequestRow struct {
	ID       sql.NullInt32
	DataHash sql.NullString
	Name     sql.NullString
	Type     NullQuestType
}

func (q *Queries) GetParentSidequest(ctx context.Context, id int32) (GetParentSidequestRow, error) {
	row := q.db.QueryRowContext(ctx, getParentSidequest, id)
	var i GetParentSidequestRow
	err := row.Scan(
		&i.ID,
		&i.DataHash,
		&i.Name,
		&i.Type,
	)
	return i, err
}

const getSidequestIDs = `-- name: GetSidequestIDs :many
SELECT id FROM sidequests ORDER BY id
`

func (q *Queries) GetSidequestIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getSidequestIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSidequestSubquestIDs = `-- name: GetSidequestSubquestIDs :many
SELECT id FROM subquests WHERE sidequest_id = $1 ORDER BY id
`

func (q *Queries) GetSidequestSubquestIDs(ctx context.Context, sidequestID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getSidequestSubquestIDs, sidequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubquestIDs = `-- name: GetSubquestIDs :many
SELECT id FROM subquests ORDER BY id
`

func (q *Queries) GetSubquestIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getSubquestIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
