package api


type EnumEndpoint EndpointName

const (
	enumEpAbilityType					EnumEndpoint = "ability-type"
	enumEpUnitType						EnumEndpoint = "unit-type"
	enumEpItemType						EnumEndpoint = "item-type"
	enumEpQuestType						EnumEndpoint = "quest-type"

	enumEpAaActivationCondition			EnumEndpoint = "auto-ability-activation-condition"
	enumEpAlterationType				EnumEndpoint = "alteration-type"
	enumEpAreaConnectionType			EnumEndpoint = "area-connection-type"
	enumEpArenaCreationCategory			EnumEndpoint = "arena-creation-category"
	enumEpArmorType						EnumEndpoint = "armor-type"
	enumEpArranger						EnumEndpoint = "arranger"
	enumEpAutoAbilityCategory			EnumEndpoint = "auto-ability-category"
	enumEpAvailabilityType				EnumEndpoint = "availability-type"
	enumEpBgReplacementType				EnumEndpoint = "bg-replacement-type"
	enumEpBlitzballPositionSlot			EnumEndpoint = "blitzball-position-slot"
	enumEpBlitzballTournamentCategory	EnumEndpoint = "blitzball-tournament-category"
	enumEpCelestialFormula				EnumEndpoint = "celestial-formula"
	enumEpCharacterClassCategory		EnumEndpoint = "character-class-category"
	enumEpComposer						EnumEndpoint = "composer"
	enumEpCounterType					EnumEndpoint = "counter-type"
	enumEpCreationArea					EnumEndpoint = "creation-area"
	enumEpCreationsUnlockedCategory		EnumEndpoint = "creations-unlocked-category"
	enumEpCTBIconType					EnumEndpoint = "ctb-icon-type"
	enumEpElementalAffinity				EnumEndpoint = "elemental-affinity"
	enumEpEquipClass					EnumEndpoint = "equip-class"
	enumEpEquipType						EnumEndpoint = "equip-type"
	enumEpItemCategory					EnumEndpoint = "item-category"
	enumEpKeyItemCategory				EnumEndpoint = "key-item-category"
	enumEpLootType						EnumEndpoint = "loot-type"
	enumEpMixCategory					EnumEndpoint = "mix-category"
	enumEpModifierCategory				EnumEndpoint = "modifier-category"
	enumEpMonsterCategory				EnumEndpoint = "monster-category"
	enumEpMonsterFormationCategory		EnumEndpoint = "monster-formation-category"
	enumEpMonsterSpecies				EnumEndpoint = "monster-species"
	enumEpMusicUseCase					EnumEndpoint = "music-use-case"
	enumEpNodePosition					EnumEndpoint = "node-position"
	enumEpNodeState						EnumEndpoint = "node-state"
	enumEpNodeType						EnumEndpoint = "node-type"
	enumEpNullifyArmored				EnumEndpoint = "nullify-armored"
	enumEpOverdriveModeType				EnumEndpoint = "overdrive-mode-type"
	enumEpPlayerAbilityCategory			EnumEndpoint = "player-ability-category"
	enumEpShopCategory					EnumEndpoint = "shop-category"
	enumEpShopType						EnumEndpoint = "shop-type"
	enumEpSpecialActionType				EnumEndpoint = "special-action-type"
	enumEpSphereColor					EnumEndpoint = "sphere-color"
	enumEpSphereEffect					EnumEndpoint = "sphere-effect"
	enumEpSphereGridType				EnumEndpoint = "sphere-grid-type"
	enumEpStatusConditionCategory		EnumEndpoint = "status-condition-category"
	enumEpTreasureType					EnumEndpoint = "treasure-type"
	enumEpWeaponType					EnumEndpoint = "weapon-type"

	enumEpAccSourceType					EnumEndpoint = "accuracy-source-type"
	enumEpAttackType					EnumEndpoint = "attack-type"
	enumEpBreakDmgLimitType				EnumEndpoint = "break-dmg-limit-type"
	enumEpCalculationType				EnumEndpoint = "calculation-type"
	enumEpCriticalType					EnumEndpoint = "critical-type"
	enumEpCtbAttackType					EnumEndpoint = "ctb-attack-type"
	enumEpDamageFormula					EnumEndpoint = "damage-formula"
	enumEpDamageType					EnumEndpoint = "damage-type"
	enumEpDelayType						EnumEndpoint = "delay-type"
	enumEpDurationType					EnumEndpoint = "duration-type"
	enumEpTargetType					EnumEndpoint = "target-type"
)



type EnumName string

const (
	enumNameAbilityType 				EnumName = "ability type"
	enumNameUnitType    				EnumName = "unit type"
	enumNameItemType    				EnumName = "item type"
	enumNameQuestType   				EnumName = "quest type"
	enumNameAaActivationCondition       EnumName = "auto-ability activation condition"
	enumNameAlterationType              EnumName = "alteration type"
	enumNameAreaConnectionType          EnumName = "area connection type"
	enumNameArenaCreationCategory       EnumName = "arena creation category"
	enumNameArmorType                   EnumName = "armor type"
	enumNameArranger                    EnumName = "arranger"
	enumNameAutoAbilityCategory         EnumName = "auto-ability category"
	enumNameAvailabilityType            EnumName = "availability type"
	enumNameBgReplacementType           EnumName = "bg replacement type"
	enumNameBlitzballPositionSlot       EnumName = "blitzball-position slot"
	enumNameBlitzballTournamentCategory EnumName = "blitzball-tournament category"
	enumNameCelestialFormula            EnumName = "celestial formula"
	enumNameCharacterClassCategory      EnumName = "character class category"
	enumNameComposer                    EnumName = "composer"
	enumNameCounterType                 EnumName = "counter type"
	enumNameCreationArea                EnumName = "creation area"
	enumNameCreationsUnlockedCategory   EnumName = "creations unlocked category"
	enumNameCTBIconType                 EnumName = "ctb icon type"
	enumNameElementalAffinity           EnumName = "elemental affinity"
	enumNameEquipClass                  EnumName = "equip class"
	enumNameEquipType                   EnumName = "equip type"
	enumNameItemCategory                EnumName = "item category"
	enumNameKeyItemCategory             EnumName = "key-item category"
	enumNameLootType                    EnumName = "loot type"
	enumNameMixCategory                 EnumName = "mix category"
	enumNameModifierCategory            EnumName = "modifier category"
	enumNameMonsterCategory             EnumName = "monster category"
	enumNameMonsterFormationCategory    EnumName = "monster-formation category"
	enumNameMonsterSpecies              EnumName = "monster species"
	enumNameMusicUseCase                EnumName = "music use case"
	enumNameNodePosition                EnumName = "node position"
	enumNameNodeState                   EnumName = "node state"
	enumNameNodeType                    EnumName = "node type"
	enumNameNullifyArmored              EnumName = "nullify armored"
	enumNameOverdriveModeType           EnumName = "overdrive mode type"
	enumNamePlayerAbilityCategory       EnumName = "player ability category"
	enumNameShopCategory                EnumName = "shop category"
	enumNameShopType                    EnumName = "shop type"
	enumNameSpecialActionType           EnumName = "special action type"
	enumNameSphereColor                 EnumName = "sphere color"
	enumNameSphereEffect                EnumName = "sphere effect"
	enumNameSphereGridType              EnumName = "sphere grid type"
	enumNameStatusConditionCategory     EnumName = "status condition category"
	enumNameTreasureType                EnumName = "treasure type"
	enumNameWeaponType                  EnumName = "weapon type"

	enumNameAccSourceType     			EnumName = "accuracy source type"
	enumNameAttackType        			EnumName = "attack type"
	enumNameBreakDmgLimitType 			EnumName = "break dmg limit type"
	enumNameCalculationType   			EnumName = "calculation type"
	enumNameCriticalType      			EnumName = "critical type"
	enumNameCtbAttackType     			EnumName = "ctb attack type"
	enumNameDamageFormula    			EnumName = "damage formula"
	enumNameDamageType        			EnumName = "damage type"
	enumNameDelayType         			EnumName = "delay type"
	enumNameDurationType      			EnumName = "duration type"
	enumNameTargetType        			EnumName = "target type"
)
