package api

type EndpointName string

const (
	epLocations                EndpointName = "locations"
	epSublocations             EndpointName = "sublocations"
	epAreas                    EndpointName = "areas"
	epMonsterFormations        EndpointName = "monster-formations"
	epShops                    EndpointName = "shops"
	epTreasures                EndpointName = "treasures"
	epQuests                   EndpointName = "quests"
	epSidequests               EndpointName = "sidequests"
	epSubquests                EndpointName = "subquests"
	epArenaCreations           EndpointName = "arena-creations"
	epBlitzballPrizes          EndpointName = "blitzball-prizes"
	epSongs                    EndpointName = "songs"
	epFMVs                     EndpointName = "fmvs"
	epPlayerUnits              EndpointName = "player-units"
	epCharacters               EndpointName = "characters"
	epAeons                    EndpointName = "aeons"
	epCharacterClasses         EndpointName = "character-classes"
	epMonsters                 EndpointName = "monsters"
	epAbilities                EndpointName = "abilities"
	epPlayerAbilities          EndpointName = "player-abilities"
	epOverdriveAbilities       EndpointName = "overdrive-abilities"
	epItemAbilities            EndpointName = "item-abilities"
	epTriggerCommands          EndpointName = "trigger-commands"
	epMiscAbilities            EndpointName = "misc-abilities"
	epEnemyAbilities           EndpointName = "enemy-abilities"
	epAeonCommands             EndpointName = "aeon-commands"
	epOverdriveCommands        EndpointName = "overdrive-commands"
	epOverdrives               EndpointName = "overdrives"
	epRonsoRages               EndpointName = "ronso-rages"
	epSubmenus                 EndpointName = "submenus"
	epTopmenus                 EndpointName = "topmenus"
	epAllItems                 EndpointName = "all-items"
	epItems                    EndpointName = "items"
	epSpheres                  EndpointName = "spheres"
	epKeyItems                 EndpointName = "key-items"
	epPrimers                  EndpointName = "primers"
	epMixes                    EndpointName = "mixes"
	epAutoAbilities            EndpointName = "auto-abilities"
	epEquipmentTables          EndpointName = "equipment-tables"
	epEquipment                EndpointName = "equipment"
	epCelestialWeapons         EndpointName = "celestial-weapons"
	epStats                    EndpointName = "stats"
	epProperties               EndpointName = "properties"
	epOverdriveModes           EndpointName = "overdrive-modes"
	epElements                 EndpointName = "elements"
	epStatusConditions         EndpointName = "status-conditions"
	epModifiers                EndpointName = "modifiers"
	epAgilityTiers             EndpointName = "agility-tiers"
)

type ResTypeSingle string

const (
	rtsLocations                ResTypeSingle = "location"
	rtsSublocations             ResTypeSingle = "sublocation"
	rtsAreas                    ResTypeSingle = "area"
	rtsMonsterFormations        ResTypeSingle = "monster-formation"
	rtsShops                    ResTypeSingle = "shop"
	rtsTreasures                ResTypeSingle = "treasure"
	rtsQuests                   ResTypeSingle = "quest"
	rtsSidequests               ResTypeSingle = "sidequest"
	rtsSubquests                ResTypeSingle = "subquest"
	rtsArenaCreations           ResTypeSingle = "arena creation"
	rtsBlitzballPrizes          ResTypeSingle = "blitzball prize table"
	rtsSongs                    ResTypeSingle = "song"
	rtsFMVs                     ResTypeSingle = "fmv"
	rtsPlayerUnits              ResTypeSingle = "player unit"
	rtsCharacters               ResTypeSingle = "character"
	rtsAeons                    ResTypeSingle = "aeon"
	rtsCharacterClasses         ResTypeSingle = "character class"
	rtsMonsters                 ResTypeSingle = "monster"
	rtsAbilities                ResTypeSingle = "ability"
	rtsPlayerAbilities          ResTypeSingle = "player ability"
	rtsOverdriveAbilities       ResTypeSingle = "overdrive ability"
	rtsItemAbilities            ResTypeSingle = "item ability"
	rtsTriggerCommands          ResTypeSingle = "trigger command"
	rtsMiscAbilities            ResTypeSingle = "misc ability"
	rtsEnemyAbilities           ResTypeSingle = "enemy ability"
	rtsAeonCommands             ResTypeSingle = "aeon command"
	rtsOverdriveCommands        ResTypeSingle = "overdrive command"
	rtsOverdrives               ResTypeSingle = "overdrive"
	rtsRonsoRages               ResTypeSingle = "ronso rage"
	rtsSubmenus                 ResTypeSingle = "submenu"
	rtsTopmenus                 ResTypeSingle = "topmenu"
	rtsAllItems                 ResTypeSingle = "all item"
	rtsItems                    ResTypeSingle = "item"
	rtsSpheres                  ResTypeSingle = "sphere"
	rtsKeyItems                 ResTypeSingle = "key-item"
	rtsPrimers                  ResTypeSingle = "primer"
	rtsMixes                    ResTypeSingle = "mix"
	rtsAutoAbilities            ResTypeSingle = "auto-ability"
	rtsEquipmentTables          ResTypeSingle = "equipment table"
	rtsEquipment                ResTypeSingle = "equipment"
	rtsCelestialWeapons         ResTypeSingle = "celestial weapon"
	rtsStats                    ResTypeSingle = "stat"
	rtsProperties               ResTypeSingle = "property"
	rtsOverdriveModes           ResTypeSingle = "overdrive mode"
	rtsElements                 ResTypeSingle = "element"
	rtsStatusConditions         ResTypeSingle = "status condition"
	rtsModifiers                ResTypeSingle = "modifier"
	rtsAgilityTiers             ResTypeSingle = "agility tier"
)

type ResTypePlural string

const (
	rtpLocations                ResTypePlural = "locations"
	rtpSublocations             ResTypePlural = "sublocations"
	rtpAreas                    ResTypePlural = "areas"
	rtpMonsterFormations        ResTypePlural = "monster-formations"
	rtpShops                    ResTypePlural = "shops"
	rtpTreasures                ResTypePlural = "treasures"
	rtpQuests                   ResTypePlural = "quests"
	rtpSidequests               ResTypePlural = "sidequests"
	rtpSubquests                ResTypePlural = "subquests"
	rtpArenaCreations           ResTypePlural = "arena creations"
	rtpBlitzballPrizes          ResTypePlural = "blitzball prize tables"
	rtpSongs                    ResTypePlural = "songs"
	rtpFMVs                     ResTypePlural = "fmvs"
	rtpPlayerUnits              ResTypePlural = "player units"
	rtpCharacters               ResTypePlural = "characters"
	rtpAeons                    ResTypePlural = "aeons"
	rtpCharacterClasses         ResTypePlural = "character classes"
	rtpMonsters                 ResTypePlural = "monsters"
	rtpAbilities                ResTypePlural = "abilities"
	rtpPlayerAbilities          ResTypePlural = "player abilities"
	rtpOverdriveAbilities       ResTypePlural = "overdrive abilities"
	rtpItemAbilities            ResTypePlural = "item abilities"
	rtpTriggerCommands          ResTypePlural = "trigger commands"
	rtpMiscAbilities            ResTypePlural = "misc abilities"
	rtpEnemyAbilities           ResTypePlural = "enemy abilities"
	rtpAeonCommands             ResTypePlural = "aeon commands"
	rtpOverdriveCommands        ResTypePlural = "overdrive commands"
	rtpOverdrives               ResTypePlural = "overdrives"
	rtpRonsoRages               ResTypePlural = "ronso rages"
	rtpSubmenus                 ResTypePlural = "submenus"
	rtpTopmenus                 ResTypePlural = "topmenus"
	rtpAllItems                 ResTypePlural = "all items"
	rtpItems                    ResTypePlural = "items"
	rtpSpheres                  ResTypePlural = "spheres"
	rtpKeyItems                 ResTypePlural = "key-items"
	rtpPrimers                  ResTypePlural = "primers"
	rtpMixes                    ResTypePlural = "mixes"
	rtpAutoAbilities            ResTypePlural = "auto-abilities"
	rtpEquipmentTables          ResTypePlural = "equipment tables"
	rtpEquipment                ResTypePlural = "equipment"
	rtpCelestialWeapons         ResTypePlural = "celestial weapons"
	rtpStats                    ResTypePlural = "stats"
	rtpProperties               ResTypePlural = "properties"
	rtpOverdriveModes           ResTypePlural = "overdrive modes"
	rtpElements                 ResTypePlural = "elements"
	rtpStatusConditions         ResTypePlural = "status conditions"
	rtpModifiers                ResTypePlural = "modifiers"
	rtpAgilityTiers             ResTypePlural = "agility tiers"
)
