package api

import h "github.com/andreasSchauer/finalfantasyxapi/internal/helpers"


type EnumName string

const (
	enumNameAbilityType 				EnumName = "ability type"
	enumNameUnitType    				EnumName = "unit type"
	enumNameItemType    				EnumName = "item type"
	enumNameQuestType   				EnumName = "quest type"
	enumNameAaActivationCondition       EnumName = "auto-ability activation condition"
	enumNameAlterationType              EnumName = "alteration type"
	enumNameAreaConnectionType          EnumName = "area connection type"
	enumNameArenaCreationCategory       EnumName = "arena creation category"
	enumNameArmorType                   EnumName = "armor type"
	enumNameArranger                    EnumName = "arranger"
	enumNameAutoAbilityCategory         EnumName = "auto-ability category"
	enumNameAvailabilityType            EnumName = "availability type"
	enumNameBgReplacementType           EnumName = "bg replacement type"
	enumNameBlitzballPositionSlot       EnumName = "blitzball-position slot"
	enumNameBlitzballTournamentCategory EnumName = "blitzball-tournament category"
	enumNameCelestialFormula            EnumName = "celestial formula"
	enumNameCharacterClassCategory      EnumName = "character class category"
	enumNameComposer                    EnumName = "composer"
	enumNameCounterType                 EnumName = "counter type"
	enumNameCreationArea                EnumName = "creation area"
	enumNameCreationsUnlockedCategory   EnumName = "creations unlocked category"
	enumNameCTBIconType                 EnumName = "ctb icon type"
	enumNameElementalAffinity           EnumName = "elemental affinity"
	enumNameEquipClass                  EnumName = "equip class"
	enumNameEquipType                   EnumName = "equip type"
	enumNameItemCategory                EnumName = "item category"
	enumNameKeyItemCategory             EnumName = "key-item category"
	enumNameLootType                    EnumName = "loot type"
	enumNameMixCategory                 EnumName = "mix category"
	enumNameModifierCategory            EnumName = "modifier category"
	enumNameMonsterCategory             EnumName = "monster category"
	enumNameMonsterFormationCategory    EnumName = "monster-formation category"
	enumNameMonsterSpecies              EnumName = "monster species"
	enumNameMusicUseCase                EnumName = "music use case"
	enumNameNodePosition                EnumName = "node position"
	enumNameNodeState                   EnumName = "node state"
	enumNameNodeType                    EnumName = "node type"
	enumNameNullifyArmored              EnumName = "nullify armored"
	enumNameOverdriveModeType           EnumName = "overdrive mode type"
	enumNamePlayerAbilityCategory       EnumName = "player ability category"
	enumNameShopCategory                EnumName = "shop category"
	enumNameShopType                    EnumName = "shop type"
	enumNameSpecialActionType           EnumName = "special action type"
	enumNameSphereColor                 EnumName = "sphere color"
	enumNameSphereEffect                EnumName = "sphere effect"
	enumNameSphereGridType              EnumName = "sphere grid type"
	enumNameStatusConditionCategory     EnumName = "status condition category"
	enumNameTreasureType                EnumName = "treasure type"
	enumNameWeaponType                  EnumName = "weapon type"

	enumNameAccSourceType     			EnumName = "accuracy source type"
	enumNameAttackType        			EnumName = "attack type"
	enumNameBreakDmgLimitType 			EnumName = "break dmg limit type"
	enumNameCalculationType   			EnumName = "calculation type"
	enumNameCriticalType      			EnumName = "critical type"
	enumNameCtbAttackType     			EnumName = "ctb attack type"
	enumNameDamageFormula    			EnumName = "damage formula"
	enumNameDamageType        			EnumName = "damage type"
	enumNameDelayType         			EnumName = "delay type"
	enumNameDurationType      			EnumName = "duration type"
	enumNameTargetType        			EnumName = "target type"
)


func getEnumKey(e EnumName) string {
	return h.GetNameWithUnderscores(string(e))
}